<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Chapter 4 Statistical Analyses of Two Variables | Media Analytics With R</title>
  <meta name="description" content="Chapter 4 Statistical Analyses of Two Variables | Media Analytics With R" />
  <meta name="generator" content="bookdown 0.26 and GitBook 2.6.7" />

  <meta property="og:title" content="Chapter 4 Statistical Analyses of Two Variables | Media Analytics With R" />
  <meta property="og:type" content="book" />
  
  
  

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Chapter 4 Statistical Analyses of Two Variables | Media Analytics With R" />
  
  
  

<meta name="author" content="Jenny Jiang &amp; Brian Walsh" />


<meta name="date" content="2023-03-16" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="statistical-analyses-of-a-single-variable.html"/>
<link rel="next" href="statistical-analyses-of-three-or-more-variables-modelling.html"/>
<script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fuse.js@6.4.6/dist/fuse.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />








<link href="libs/anchor-sections-1.1.0/anchor-sections.css" rel="stylesheet" />
<link href="libs/anchor-sections-1.1.0/anchor-sections-hash.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.1.0/anchor-sections.js"></script>
<script src="libs/kePrint-0.0.1/kePrint.js"></script>
<link href="libs/lightable-0.0.1/lightable.css" rel="stylesheet" />
<link href="libs/font-awesome-5.13.0/css/all.min.css" rel="stylesheet" />
<link href="libs/font-awesome-5.13.0/css/v4-shims.min.css" rel="stylesheet" />
<script src="libs/htmlwidgets-1.5.4/htmlwidgets.js"></script>
<link href="libs/wordcloud2-0.0.1/wordcloud.css" rel="stylesheet" />
<script src="libs/wordcloud2-0.0.1/wordcloud2-all.js"></script>
<script src="libs/wordcloud2-0.0.1/hover.js"></script>
<script src="libs/wordcloud2-binding-0.2.1/wordcloud2.js"></script>


<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>


<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">Media Analytics with R</a></li>

<li class="divider"></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>Preface</a>
<ul>
<li class="chapter" data-level="0.1" data-path="index.html"><a href="index.html#who-is-this-book-for"><i class="fa fa-check"></i><b>0.1</b> Who is this book for?</a></li>
<li class="chapter" data-level="0.2" data-path="index.html"><a href="index.html#why-r"><i class="fa fa-check"></i><b>0.2</b> Why R?</a></li>
<li class="chapter" data-level="0.3" data-path="index.html"><a href="index.html#what-will-we-learn-to-do-with-r-in-this-book"><i class="fa fa-check"></i><b>0.3</b> What will we learn to do with R in this book?</a></li>
<li class="chapter" data-level="0.4" data-path="index.html"><a href="index.html#installing-the-software"><i class="fa fa-check"></i><b>0.4</b> Installing the Software</a></li>
<li class="chapter" data-level="0.5" data-path="index.html"><a href="index.html#getting-started"><i class="fa fa-check"></i><b>0.5</b> Getting Started</a></li>
<li class="chapter" data-level="0.6" data-path="index.html"><a href="index.html#r-studio-projects"><i class="fa fa-check"></i><b>0.6</b> R Studio Projects</a></li>
</ul></li>
<li class="chapter" data-level="1" data-path="intro-to-programming-in-r.html"><a href="intro-to-programming-in-r.html"><i class="fa fa-check"></i><b>1</b> Intro to Programming in R</a>
<ul>
<li class="chapter" data-level="1.1" data-path="intro-to-programming-in-r.html"><a href="intro-to-programming-in-r.html#creating-a-new-project-in-r-studio"><i class="fa fa-check"></i><b>1.1</b> Creating a New Project in R Studio</a></li>
<li class="chapter" data-level="1.2" data-path="intro-to-programming-in-r.html"><a href="intro-to-programming-in-r.html#loading-packages-and-data"><i class="fa fa-check"></i><b>1.2</b> Loading Packages and Data</a></li>
<li class="chapter" data-level="1.3" data-path="intro-to-programming-in-r.html"><a href="intro-to-programming-in-r.html#section"><i class="fa fa-check"></i><b>1.3</b> %&gt;%</a></li>
<li class="chapter" data-level="1.4" data-path="intro-to-programming-in-r.html"><a href="intro-to-programming-in-r.html#filtering-data"><i class="fa fa-check"></i><b>1.4</b> Filtering Data</a></li>
<li class="chapter" data-level="1.5" data-path="intro-to-programming-in-r.html"><a href="intro-to-programming-in-r.html#visualizing"><i class="fa fa-check"></i><b>1.5</b> Visualizing</a></li>
<li class="chapter" data-level="1.6" data-path="intro-to-programming-in-r.html"><a href="intro-to-programming-in-r.html#syntax"><i class="fa fa-check"></i><b>1.6</b> Syntax</a></li>
<li class="chapter" data-level="1.7" data-path="intro-to-programming-in-r.html"><a href="intro-to-programming-in-r.html#creating-variables"><i class="fa fa-check"></i><b>1.7</b> Creating Variables</a></li>
<li class="chapter" data-level="1.8" data-path="intro-to-programming-in-r.html"><a href="intro-to-programming-in-r.html#modifying-data"><i class="fa fa-check"></i><b>1.8</b> Modifying Data</a></li>
<li class="chapter" data-level="1.9" data-path="intro-to-programming-in-r.html"><a href="intro-to-programming-in-r.html#count"><i class="fa fa-check"></i><b>1.9</b> Count</a></li>
<li class="chapter" data-level="1.10" data-path="intro-to-programming-in-r.html"><a href="intro-to-programming-in-r.html#more-aesthetics"><i class="fa fa-check"></i><b>1.10</b> More Aesthetics</a></li>
<li class="chapter" data-level="1.11" data-path="intro-to-programming-in-r.html"><a href="intro-to-programming-in-r.html#review"><i class="fa fa-check"></i><b>1.11</b> Review</a></li>
</ul></li>
<li class="chapter" data-level="2" data-path="manipulating-data.html"><a href="manipulating-data.html"><i class="fa fa-check"></i><b>2</b> Manipulating Data</a>
<ul>
<li class="chapter" data-level="2.1" data-path="manipulating-data.html"><a href="manipulating-data.html#mutate"><i class="fa fa-check"></i><b>2.1</b> Mutate</a></li>
<li class="chapter" data-level="2.2" data-path="manipulating-data.html"><a href="manipulating-data.html#group_by-summarize"><i class="fa fa-check"></i><b>2.2</b> Group_by , Summarize()</a></li>
<li class="chapter" data-level="2.3" data-path="manipulating-data.html"><a href="manipulating-data.html#working-with-strings"><i class="fa fa-check"></i><b>2.3</b> Working with Strings</a>
<ul>
<li class="chapter" data-level="2.3.1" data-path="manipulating-data.html"><a href="manipulating-data.html#practical-applications-of-stringr"><i class="fa fa-check"></i><b>2.3.1</b> Practical Applications of Stringr</a></li>
</ul></li>
<li class="chapter" data-level="2.4" data-path="manipulating-data.html"><a href="manipulating-data.html#average-name-length-over-time"><i class="fa fa-check"></i><b>2.4</b> Average name length over time</a></li>
<li class="chapter" data-level="2.5" data-path="manipulating-data.html"><a href="manipulating-data.html#revisiting-summarize"><i class="fa fa-check"></i><b>2.5</b> Revisiting summarize()</a></li>
<li class="chapter" data-level="2.6" data-path="manipulating-data.html"><a href="manipulating-data.html#additional-functions"><i class="fa fa-check"></i><b>2.6</b> Additional Functions</a></li>
<li class="chapter" data-level="2.7" data-path="manipulating-data.html"><a href="manipulating-data.html#case-study-born-without-a-proper-name"><i class="fa fa-check"></i><b>2.7</b> Case Study: Born Without A (Proper) Name</a></li>
<li class="chapter" data-level="2.8" data-path="manipulating-data.html"><a href="manipulating-data.html#assignment"><i class="fa fa-check"></i><b>2.8</b> Assignment</a></li>
</ul></li>
<li class="chapter" data-level="3" data-path="statistical-analyses-of-a-single-variable.html"><a href="statistical-analyses-of-a-single-variable.html"><i class="fa fa-check"></i><b>3</b> Statistical Analyses of a Single Variable</a>
<ul>
<li class="chapter" data-level="3.1" data-path="statistical-analyses-of-a-single-variable.html"><a href="statistical-analyses-of-a-single-variable.html#variables-levels-of-measurement"><i class="fa fa-check"></i><b>3.1</b> Variables &amp; Levels of Measurement</a>
<ul>
<li class="chapter" data-level="3.1.1" data-path="statistical-analyses-of-a-single-variable.html"><a href="statistical-analyses-of-a-single-variable.html#nominal-data"><i class="fa fa-check"></i><b>3.1.1</b> Nominal Data</a></li>
<li class="chapter" data-level="3.1.2" data-path="statistical-analyses-of-a-single-variable.html"><a href="statistical-analyses-of-a-single-variable.html#ordinal-data"><i class="fa fa-check"></i><b>3.1.2</b> Ordinal Data</a></li>
<li class="chapter" data-level="3.1.3" data-path="statistical-analyses-of-a-single-variable.html"><a href="statistical-analyses-of-a-single-variable.html#interval-data"><i class="fa fa-check"></i><b>3.1.3</b> Interval Data</a></li>
<li class="chapter" data-level="3.1.4" data-path="statistical-analyses-of-a-single-variable.html"><a href="statistical-analyses-of-a-single-variable.html#ratio-data"><i class="fa fa-check"></i><b>3.1.4</b> Ratio Data</a></li>
</ul></li>
<li class="chapter" data-level="3.2" data-path="statistical-analyses-of-a-single-variable.html"><a href="statistical-analyses-of-a-single-variable.html#frequency-distribution"><i class="fa fa-check"></i><b>3.2</b> Frequency Distribution</a></li>
<li class="chapter" data-level="3.3" data-path="statistical-analyses-of-a-single-variable.html"><a href="statistical-analyses-of-a-single-variable.html#percentage-change"><i class="fa fa-check"></i><b>3.3</b> Percentage Change</a></li>
<li class="chapter" data-level="3.4" data-path="statistical-analyses-of-a-single-variable.html"><a href="statistical-analyses-of-a-single-variable.html#relative-frequency"><i class="fa fa-check"></i><b>3.4</b> Relative Frequency</a></li>
<li class="chapter" data-level="3.5" data-path="statistical-analyses-of-a-single-variable.html"><a href="statistical-analyses-of-a-single-variable.html#percentage-points"><i class="fa fa-check"></i><b>3.5</b> Percentage Points</a></li>
<li class="chapter" data-level="3.6" data-path="statistical-analyses-of-a-single-variable.html"><a href="statistical-analyses-of-a-single-variable.html#rate"><i class="fa fa-check"></i><b>3.6</b> Rate</a></li>
<li class="chapter" data-level="3.7" data-path="statistical-analyses-of-a-single-variable.html"><a href="statistical-analyses-of-a-single-variable.html#ratio"><i class="fa fa-check"></i><b>3.7</b> Ratio</a></li>
<li class="chapter" data-level="3.8" data-path="statistical-analyses-of-a-single-variable.html"><a href="statistical-analyses-of-a-single-variable.html#central-tendency"><i class="fa fa-check"></i><b>3.8</b> Central Tendency</a></li>
<li class="chapter" data-level="3.9" data-path="statistical-analyses-of-a-single-variable.html"><a href="statistical-analyses-of-a-single-variable.html#data-variation"><i class="fa fa-check"></i><b>3.9</b> Data Variation</a></li>
<li class="chapter" data-level="3.10" data-path="statistical-analyses-of-a-single-variable.html"><a href="statistical-analyses-of-a-single-variable.html#assignment-analyzing-a-single-variable"><i class="fa fa-check"></i><b>3.10</b> Assignment: Analyzing a Single Variable</a></li>
</ul></li>
<li class="chapter" data-level="4" data-path="statistical-analyses-of-two-variables.html"><a href="statistical-analyses-of-two-variables.html"><i class="fa fa-check"></i><b>4</b> Statistical Analyses of Two Variables</a>
<ul>
<li class="chapter" data-level="4.1" data-path="statistical-analyses-of-two-variables.html"><a href="statistical-analyses-of-two-variables.html#cross-tab"><i class="fa fa-check"></i><b>4.1</b> Cross-tab</a></li>
<li class="chapter" data-level="4.2" data-path="statistical-analyses-of-two-variables.html"><a href="statistical-analyses-of-two-variables.html#independent-variable-vs.-dependent-variable"><i class="fa fa-check"></i><b>4.2</b> Independent Variable VS. Dependent Variable</a></li>
<li class="chapter" data-level="4.3" data-path="statistical-analyses-of-two-variables.html"><a href="statistical-analyses-of-two-variables.html#independent-sample-t-test"><i class="fa fa-check"></i><b>4.3</b> Independent sample T-Test</a>
<ul>
<li class="chapter" data-level="4.3.1" data-path="statistical-analyses-of-two-variables.html"><a href="statistical-analyses-of-two-variables.html#anova"><i class="fa fa-check"></i><b>4.3.1</b> ANOVA</a></li>
</ul></li>
<li class="chapter" data-level="4.4" data-path="statistical-analyses-of-two-variables.html"><a href="statistical-analyses-of-two-variables.html#correlation"><i class="fa fa-check"></i><b>4.4</b> Correlation</a></li>
<li class="chapter" data-level="4.5" data-path="statistical-analyses-of-two-variables.html"><a href="statistical-analyses-of-two-variables.html#regression"><i class="fa fa-check"></i><b>4.5</b> Regression</a></li>
</ul></li>
<li class="chapter" data-level="5" data-path="statistical-analyses-of-three-or-more-variables-modelling.html"><a href="statistical-analyses-of-three-or-more-variables-modelling.html"><i class="fa fa-check"></i><b>5</b> Statistical Analyses of Three or More Variables &amp; Modelling</a>
<ul>
<li class="chapter" data-level="5.1" data-path="statistical-analyses-of-three-or-more-variables-modelling.html"><a href="statistical-analyses-of-three-or-more-variables-modelling.html#linear-regression"><i class="fa fa-check"></i><b>5.1</b> linear Regression</a></li>
<li class="chapter" data-level="5.2" data-path="statistical-analyses-of-three-or-more-variables-modelling.html"><a href="statistical-analyses-of-three-or-more-variables-modelling.html#interaction-effects"><i class="fa fa-check"></i><b>5.2</b> Interaction Effects</a></li>
<li class="chapter" data-level="5.3" data-path="statistical-analyses-of-three-or-more-variables-modelling.html"><a href="statistical-analyses-of-three-or-more-variables-modelling.html#assignment-1"><i class="fa fa-check"></i><b>5.3</b> Assignment</a>
<ul>
<li class="chapter" data-level="5.3.1" data-path="statistical-analyses-of-three-or-more-variables-modelling.html"><a href="statistical-analyses-of-three-or-more-variables-modelling.html#linear-regression-and-correlation"><i class="fa fa-check"></i><b>5.3.1</b> Linear Regression and Correlation</a></li>
<li class="chapter" data-level="5.3.2" data-path="statistical-analyses-of-three-or-more-variables-modelling.html"><a href="statistical-analyses-of-three-or-more-variables-modelling.html#multiple-regression-analysis"><i class="fa fa-check"></i><b>5.3.2</b> Multiple Regression Analysis</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="6" data-path="accessing-twitters-api-in-r.html"><a href="accessing-twitters-api-in-r.html"><i class="fa fa-check"></i><b>6</b> Accessing Twitter’s API in R</a>
<ul>
<li class="chapter" data-level="6.1" data-path="accessing-twitters-api-in-r.html"><a href="accessing-twitters-api-in-r.html#making-your-first-request-to-the-new-twitter-api-v2"><i class="fa fa-check"></i><b>6.1</b> Making Your First Request to the New Twitter API v2</a></li>
<li class="chapter" data-level="6.2" data-path="accessing-twitters-api-in-r.html"><a href="accessing-twitters-api-in-r.html#using-you-twitter-app-in-r"><i class="fa fa-check"></i><b>6.2</b> Using You Twitter App in R</a></li>
<li class="chapter" data-level="6.3" data-path="accessing-twitters-api-in-r.html"><a href="accessing-twitters-api-in-r.html#analyzing-twitter-data"><i class="fa fa-check"></i><b>6.3</b> Analyzing Twitter Data</a>
<ul>
<li class="chapter" data-level="6.3.1" data-path="accessing-twitters-api-in-r.html"><a href="accessing-twitters-api-in-r.html#lubridate-working-with-time"><i class="fa fa-check"></i><b>6.3.1</b> Lubridate &amp; Working with Time</a></li>
<li class="chapter" data-level="6.3.2" data-path="accessing-twitters-api-in-r.html"><a href="accessing-twitters-api-in-r.html#tweet-source"><i class="fa fa-check"></i><b>6.3.2</b> Tweet Source</a></li>
<li class="chapter" data-level="6.3.3" data-path="accessing-twitters-api-in-r.html"><a href="accessing-twitters-api-in-r.html#text-analysis-in-twitter"><i class="fa fa-check"></i><b>6.3.3</b> Text Analysis in Twitter</a></li>
</ul></li>
<li class="chapter" data-level="6.4" data-path="accessing-twitters-api-in-r.html"><a href="accessing-twitters-api-in-r.html#search-keywordssearch-users-by-keywordshashtags"><i class="fa fa-check"></i><b>6.4</b> Search Keywords/Search Users by Keywords/Hashtags</a></li>
<li class="chapter" data-level="6.5" data-path="accessing-twitters-api-in-r.html"><a href="accessing-twitters-api-in-r.html#assignment-2"><i class="fa fa-check"></i><b>6.5</b> Assignment</a>
<ul>
<li class="chapter" data-level="6.5.1" data-path="accessing-twitters-api-in-r.html"><a href="accessing-twitters-api-in-r.html#sample-code"><i class="fa fa-check"></i><b>6.5.1</b> Sample code</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="7" data-path="text-analysis.html"><a href="text-analysis.html"><i class="fa fa-check"></i><b>7</b> Text Analysis</a></li>
<li class="chapter" data-level="8" data-path="network-analysis.html"><a href="network-analysis.html"><i class="fa fa-check"></i><b>8</b> Network Analysis</a></li>
<li class="chapter" data-level="9" data-path="geo-spatial-analysis-and-visualizations.html"><a href="geo-spatial-analysis-and-visualizations.html"><i class="fa fa-check"></i><b>9</b> Geo-Spatial Analysis and Visualizations</a></li>
<li class="chapter" data-level="10" data-path="publishing.html"><a href="publishing.html"><i class="fa fa-check"></i><b>10</b> Publishing</a></li>
<li class="divider"></li>
<li><a href="https://github.com/rstudio/bookdown" target="blank">Published with bookdown</a></li>
</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Media Analytics With R</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="statistical-analyses-of-two-variables" class="section level1 hasAnchor" number="4">
<h1><span class="header-section-number">Chapter 4</span> Statistical Analyses of Two Variables<a href="statistical-analyses-of-two-variables.html#statistical-analyses-of-two-variables" class="anchor-section" aria-label="Anchor link to header"></a></h1>
<p>Analyzing a single variable can definitely help us understand the patterns of each variable in our data set; however, given its descriptive nature, it offers little insight for us to explore the relationships between different variables or to help us make informed decisions confidently. For instance, knowing the mean or median value of revenue does not allow us to understand the factors contributing to the high revenue.</p>
<p>Therefore, introducing a second variable or more allows us to explore the relationships between variables, based on which we can infer the results obtained from a sample to the general population and make confident decisions based on such analyses.</p>
<p>Now, I am going to introduce a new data set of authors of the Twitter discourses using the co-hashtags of #BlackLivesMatter and #StopAsianHate for the study of cross-racial solidarity on Twitter. It has six variables. Specifically, <strong>Gender</strong> refers to the gender of Twitter authors; <strong>Followers</strong> refers to the number of Twitter followers for each author. Using the variable of <strong>InfluencerType</strong>, authors have been categorized by follower size. <em>Mega influencers</em> are the highest-ranked category with more than a million followers. <em>Macro influencers</em> are in the tier with 100K to up to a million followers. <em>Micro influencers</em> are classified to have a follower base ranging from 10,000 to no more than 100K. Those who have less than 10,000 followers are classified as <em>Nano influencers</em>. <strong>Sentiment</strong> reflects if a tweet is positive, negative, or neutral. <strong>Post</strong> refers to the number of tweets created by an author using the co-hashtags of #BlackLivesMatter and #StopAsianHate. Finally, <strong>Impact</strong> shows you the potential impact of an author on the related Twitter discourses. It’s a normalized logarithmic scale between 0-100, with 100 indicating the greatest impact. The remaining parts of this chapter use this audience data set to demonstrate the statistical analysis of two or more variables.</p>
<div class="sourceCode" id="cb152"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb152-1"><a href="statistical-analyses-of-two-variables.html#cb152-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb152-2"><a href="statistical-analyses-of-two-variables.html#cb152-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb152-3"><a href="statistical-analyses-of-two-variables.html#cb152-3" aria-hidden="true" tabindex="-1"></a><span class="co">#You will need to read the social media data first</span></span>
<span id="cb152-4"><a href="statistical-analyses-of-two-variables.html#cb152-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb152-5"><a href="statistical-analyses-of-two-variables.html#cb152-5" aria-hidden="true" tabindex="-1"></a>data <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">&quot;social media data.csv&quot;</span>) <span class="co">#Create a dataset and name it as data</span></span></code></pre></div>
<div id="cross-tab" class="section level2 hasAnchor" number="4.1">
<h2><span class="header-section-number">4.1</span> Cross-tab<a href="statistical-analyses-of-two-variables.html#cross-tab" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Sometimes, the distribution of one variable is contingent upon a second variable, and we can conduct a cross-tab analysis to find out whether one variable has a relationship with another when both of the variables are categorical variables (nominal or ordinal level). For example, I have been wondering whether gender has any relationship with the Twitter users’ degree of influence. In other words, whether men and women have an equal chance of becoming influencers at different levels. A cross-tab analysis can help us answer this question. The key to exploring the relationship between these variables is to break these variables down into attributes and use a table to display the frequency distribution of these variables, which is called a contingency table.</p>
<div class="sourceCode" id="cb153"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb153-1"><a href="statistical-analyses-of-two-variables.html#cb153-1" aria-hidden="true" tabindex="-1"></a><span class="co">#The CrossTable() command from the gmodels package produces frequencies, and table, row, &amp; column proportions with a single command.</span></span>
<span id="cb153-2"><a href="statistical-analyses-of-two-variables.html#cb153-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb153-3"><a href="statistical-analyses-of-two-variables.html#cb153-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(gmodels)</span>
<span id="cb153-4"><a href="statistical-analyses-of-two-variables.html#cb153-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb153-5"><a href="statistical-analyses-of-two-variables.html#cb153-5" aria-hidden="true" tabindex="-1"></a><span class="co">#Run the CrossTable() command, with your two variables as inputs.</span></span>
<span id="cb153-6"><a href="statistical-analyses-of-two-variables.html#cb153-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb153-7"><a href="statistical-analyses-of-two-variables.html#cb153-7" aria-hidden="true" tabindex="-1"></a><span class="fu">CrossTable</span>(data<span class="sc">$</span>Gender, data<span class="sc">$</span>InfluencerType)</span></code></pre></div>
<pre><code>## 
##  
##    Cell Contents
## |-------------------------|
## |                       N |
## | Chi-square contribution |
## |           N / Row Total |
## |           N / Col Total |
## |         N / Table Total |
## |-------------------------|
## 
##  
## Total Observations in Table:  30519 
## 
##  
##              | data$InfluencerType 
##  data$Gender |     macro |      mega |     micro |      nano | Row Total | 
## -------------|-----------|-----------|-----------|-----------|-----------|
##       female |        24 |         2 |       502 |     13719 |     14247 | 
##              |     1.505 |     0.048 |     3.435 |     0.078 |           | 
##              |     0.002 |     0.000 |     0.035 |     0.963 |     0.467 | 
##              |     0.364 |     0.400 |     0.507 |     0.466 |           | 
##              |     0.001 |     0.000 |     0.016 |     0.450 |           | 
## -------------|-----------|-----------|-----------|-----------|-----------|
##         male |        42 |         3 |       488 |     15739 |     16272 | 
##              |     1.318 |     0.042 |     3.008 |     0.068 |           | 
##              |     0.003 |     0.000 |     0.030 |     0.967 |     0.533 | 
##              |     0.636 |     0.600 |     0.493 |     0.534 |           | 
##              |     0.001 |     0.000 |     0.016 |     0.516 |           | 
## -------------|-----------|-----------|-----------|-----------|-----------|
## Column Total |        66 |         5 |       990 |     29458 |     30519 | 
##              |     0.002 |     0.000 |     0.032 |     0.965 |           | 
## -------------|-----------|-----------|-----------|-----------|-----------|
## 
## </code></pre>
<div class="sourceCode" id="cb155"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb155-1"><a href="statistical-analyses-of-two-variables.html#cb155-1" aria-hidden="true" tabindex="-1"></a><span class="co"># change the order of the influencer type</span></span>
<span id="cb155-2"><a href="statistical-analyses-of-two-variables.html#cb155-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb155-3"><a href="statistical-analyses-of-two-variables.html#cb155-3" aria-hidden="true" tabindex="-1"></a>data<span class="sc">$</span>InfluencerType <span class="ot">&lt;-</span> <span class="fu">factor</span>(data<span class="sc">$</span>InfluencerType,</span>
<span id="cb155-4"><a href="statistical-analyses-of-two-variables.html#cb155-4" aria-hidden="true" tabindex="-1"></a>                              <span class="at">levels =</span> <span class="fu">c</span>(<span class="st">&quot;nano&quot;</span>, <span class="st">&quot;micro&quot;</span>, <span class="st">&quot;macro&quot;</span>, <span class="st">&quot;mega&quot;</span>))</span>
<span id="cb155-5"><a href="statistical-analyses-of-two-variables.html#cb155-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb155-6"><a href="statistical-analyses-of-two-variables.html#cb155-6" aria-hidden="true" tabindex="-1"></a><span class="co">#redo the crosstable</span></span>
<span id="cb155-7"><a href="statistical-analyses-of-two-variables.html#cb155-7" aria-hidden="true" tabindex="-1"></a><span class="fu">CrossTable</span>(data<span class="sc">$</span>Gender, data<span class="sc">$</span>InfluencerType)</span></code></pre></div>
<pre><code>## 
##  
##    Cell Contents
## |-------------------------|
## |                       N |
## | Chi-square contribution |
## |           N / Row Total |
## |           N / Col Total |
## |         N / Table Total |
## |-------------------------|
## 
##  
## Total Observations in Table:  30519 
## 
##  
##              | data$InfluencerType 
##  data$Gender |      nano |     micro |     macro |      mega | Row Total | 
## -------------|-----------|-----------|-----------|-----------|-----------|
##       female |     13719 |       502 |        24 |         2 |     14247 | 
##              |     0.078 |     3.435 |     1.505 |     0.048 |           | 
##              |     0.963 |     0.035 |     0.002 |     0.000 |     0.467 | 
##              |     0.466 |     0.507 |     0.364 |     0.400 |           | 
##              |     0.450 |     0.016 |     0.001 |     0.000 |           | 
## -------------|-----------|-----------|-----------|-----------|-----------|
##         male |     15739 |       488 |        42 |         3 |     16272 | 
##              |     0.068 |     3.008 |     1.318 |     0.042 |           | 
##              |     0.967 |     0.030 |     0.003 |     0.000 |     0.533 | 
##              |     0.534 |     0.493 |     0.636 |     0.600 |           | 
##              |     0.516 |     0.016 |     0.001 |     0.000 |           | 
## -------------|-----------|-----------|-----------|-----------|-----------|
## Column Total |     29458 |       990 |        66 |         5 |     30519 | 
##              |     0.965 |     0.032 |     0.002 |     0.000 |           | 
## -------------|-----------|-----------|-----------|-----------|-----------|
## 
## </code></pre>
<p>As you can see from the contingency table, female influencers account for nearly 47% of our sample, while male influencers account for 53%. If gender had nothing to do with the level of influence a user could reach, then we would end up finding around 47% females and 53% males among every single type of influencer. Now let’s see whether that is the case.</p>
<p>By looking into the <strong>Nano influencer</strong> column, we found 46.6% female and 53.4% male, which seems to be pretty close to the female and male percentages we had in our whole sample. Among the <strong>Micro influencers</strong>, almost 50% of them are female and 50% of them are male, which was a bit different from the percentages within the whole sample. However, when we move on to the next level, <strong>Macro influencer</strong>, we notice that females only account for 36% at this level while males account for 64% of all the macro influencers. Finally, for the most influential, the <strong>Mega influencer</strong> group, 40% of them are females, and the rest, 60%, are all males.</p>
<p>To summarize the patterns of this contingency table: at the <strong>Nano</strong> and <strong>Micro</strong> level, female and male influencers have a pretty balanced distribution; however, <strong>as the level of influencer goes up, female accounts for smaller percentages</strong>. So, it appears that gender does have a relationship with the type of influencer, with females more likely to be lower-level influencers and males more likely to be higher-level influencers.</p>
<p>The key statistic we derived from a cross-tab analysis is called <strong>Pearson’s chi-square</strong>, which indicates whether there is a significant difference between the expected frequency of each cell and the observed frequency in that contingency table. For example, we believe that if gender did not affect the influencer type, then the expected frequency of female influencers at the <strong>Macro level</strong> should have been around 31 (66*46.6%), while in fact, we only observed 24 female influencers at the Macro level. There is a substantial difference between 31, the expected frequency if gender and influencer type had no relationship, and 24, the observed frequency. In this case, the Pearson’s chi-square we got was 9.5, which was a “sum” of all the differences between the expected frequency and observed frequency of all the cells in this contingency table, and it was significant at the 0.02 level, indicating the probability of no differences among these groups in the population is only 2%. The R code for calculating Chi-sq is below:</p>
<div class="sourceCode" id="cb157"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb157-1"><a href="statistical-analyses-of-two-variables.html#cb157-1" aria-hidden="true" tabindex="-1"></a><span class="fu">chisq.test</span>(data<span class="sc">$</span>Gender, data<span class="sc">$</span>InfluencerType, <span class="at">correct =</span> <span class="cn">FALSE</span>)</span></code></pre></div>
<pre><code>## Warning in chisq.test(data$Gender, data$InfluencerType, correct
## = FALSE): Chi-squared approximation may be incorrect</code></pre>
<pre><code>## 
##  Pearson&#39;s Chi-squared test
## 
## data:  data$Gender and data$InfluencerType
## X-squared = 9.5, df = 3, p-value = 0.02</code></pre>
<p>Generally speaking, in social science, once we see a significance level lower than 0.05, we consider it to be significant evidence that we could reject the null hypothesis, which states that no relationship exists between the independent variable and the dependent variable, and at the same time, we accept the alternative hypothesis stating that there is a relationship between the independent variable and the dependent variable. The above Pearson’s chi-square value serves as a piece of evidence for us to conclude that for Twitter authors, there is a significant relationship between gender and influencer type.</p>
</div>
<div id="independent-variable-vs.-dependent-variable" class="section level2 hasAnchor" number="4.2">
<h2><span class="header-section-number">4.2</span> Independent Variable VS. Dependent Variable<a href="statistical-analyses-of-two-variables.html#independent-variable-vs.-dependent-variable" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>When we are exploring the relationship between two variables, we need to understand that <strong>some variables lay their influence on other variables (Independent variables or predictors)</strong>, and <strong>some variables are dependent on other variables (dependent variables or outcome variables)</strong>. For example, if you think that people’s political orientation influences whether or not, or how much, they watch FOX news, then in this relationship, political orientation serves as the independent variable, and FOX news consumption serves as the dependent variable. But you may be wondering, can this relationship be reversed? If you suspect that as people watch more FOX news, their political orientation might be shifted. Then in this new relationship, you are essentially proposing that FOX news consumption is your independent variable while political orientation is the dependent variable.</p>
</div>
<div id="independent-sample-t-test" class="section level2 hasAnchor" number="4.3">
<h2><span class="header-section-number">4.3</span> Independent sample T-Test<a href="statistical-analyses-of-two-variables.html#independent-sample-t-test" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>One of the most common analyses we do in communication research is <strong>comparing group means</strong>. Let’s start with comparing means between two groups. For example, do men earn higher salaries compared to women? Do Republicans have a higher vaccination rate than Democrats? In these two examples, we are examining a relationship between an independent variable and a dependent variable, with the former being a nominal variable with two values (e.g., gender: male vs. female) and the latter being a continuous variable measured at either ratio or interval level. The two groups we are comparing correspond to the two attributes of our independent variable (men vs. women; Democrats vs. Republicans), and the value we are comparing corresponds to the value of the dependent variable (salary; vaccine uptake rate).</p>
<p><strong>The analysis we use to compare two group means is called the independent sample t-test</strong>. Let’s say that we are interested in knowing whether males and females generate the same levels of impact. To answer this question, let’s compare the mean impact score of the two groups. For the case of the Twitter discourses using the co-hashtags of #BlackLivesMatter and #StopAsianHate, the average impact that females have reached was 4.87, and 4.34 for the males. We probably don’t even need any statistical tests to tell that there seems to be a difference between these two groups in terms of their impacts on the related Twitter discourses, with females generating higher impacts than the males. <strong>The key question here is, is this difference big enough for us to confidently claim that females and males have different impacts on the related Twitter discourses in the wider population?</strong> Remember, this is just one sample that we had, and our goal is to draw conclusions and make decisions within a population based on this one random sample. Therefore, we still need to look at inferential statistics to draw such conclusions.</p>
<p>Here is the related R code:</p>
<div class="sourceCode" id="cb160"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb160-1"><a href="statistical-analyses-of-two-variables.html#cb160-1" aria-hidden="true" tabindex="-1"></a><span class="fu">options</span>(<span class="at">scipen =</span> <span class="dv">999</span>) <span class="co"># turn off scientific notation for all variables</span></span>
<span id="cb160-2"><a href="statistical-analyses-of-two-variables.html#cb160-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb160-3"><a href="statistical-analyses-of-two-variables.html#cb160-3" aria-hidden="true" tabindex="-1"></a>mean_impact_gender <span class="ot">&lt;-</span> data <span class="sc">%&gt;%</span> <span class="co">#calculate the mean impact for males and females</span></span>
<span id="cb160-4"><a href="statistical-analyses-of-two-variables.html#cb160-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(Gender) <span class="sc">%&gt;%</span> </span>
<span id="cb160-5"><a href="statistical-analyses-of-two-variables.html#cb160-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">Impact =</span> <span class="fu">mean</span>(Impact)) </span>
<span id="cb160-6"><a href="statistical-analyses-of-two-variables.html#cb160-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb160-7"><a href="statistical-analyses-of-two-variables.html#cb160-7" aria-hidden="true" tabindex="-1"></a>mean_impact_gender <span class="sc">%&gt;%</span> </span>
<span id="cb160-8"><a href="statistical-analyses-of-two-variables.html#cb160-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(Gender, Impact)) <span class="sc">+</span></span>
<span id="cb160-9"><a href="statistical-analyses-of-two-variables.html#cb160-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_col</span>()</span></code></pre></div>
<p><img src="bookdownproj_files/figure-html/unnamed-chunk-62-1.png" width="672" /></p>
<div class="sourceCode" id="cb161"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb161-1"><a href="statistical-analyses-of-two-variables.html#cb161-1" aria-hidden="true" tabindex="-1"></a><span class="co">#mean plot</span></span>
<span id="cb161-2"><a href="statistical-analyses-of-two-variables.html#cb161-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(<span class="st">&quot;ggpubr&quot;</span>)</span>
<span id="cb161-3"><a href="statistical-analyses-of-two-variables.html#cb161-3" aria-hidden="true" tabindex="-1"></a><span class="fu">ggline</span>(data, <span class="at">x =</span> <span class="st">&quot;Gender&quot;</span>, <span class="at">y =</span> <span class="st">&quot;Impact&quot;</span>, </span>
<span id="cb161-4"><a href="statistical-analyses-of-two-variables.html#cb161-4" aria-hidden="true" tabindex="-1"></a>       <span class="at">add =</span> <span class="fu">c</span>(<span class="st">&quot;mean_se&quot;</span>), <span class="co"># Add error bars: mean_se</span></span>
<span id="cb161-5"><a href="statistical-analyses-of-two-variables.html#cb161-5" aria-hidden="true" tabindex="-1"></a>       <span class="at">order =</span> <span class="fu">c</span>(<span class="st">&quot;male&quot;</span>, <span class="st">&quot;female&quot;</span>),</span>
<span id="cb161-6"><a href="statistical-analyses-of-two-variables.html#cb161-6" aria-hidden="true" tabindex="-1"></a>       <span class="at">ylab =</span> <span class="st">&quot;Impact&quot;</span>, <span class="at">xlab =</span> <span class="st">&quot;Gender&quot;</span>)</span></code></pre></div>
<p><img src="bookdownproj_files/figure-html/unnamed-chunk-62-2.png" width="672" /></p>
<div class="sourceCode" id="cb162"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb162-1"><a href="statistical-analyses-of-two-variables.html#cb162-1" aria-hidden="true" tabindex="-1"></a><span class="co">#t-test</span></span>
<span id="cb162-2"><a href="statistical-analyses-of-two-variables.html#cb162-2" aria-hidden="true" tabindex="-1"></a><span class="fu">t.test</span>(Impact <span class="sc">~</span> Gender,</span>
<span id="cb162-3"><a href="statistical-analyses-of-two-variables.html#cb162-3" aria-hidden="true" tabindex="-1"></a>       <span class="at">data =</span> data)</span></code></pre></div>
<pre><code>## 
##  Welch Two Sample t-test
## 
## data:  Impact by Gender
## t = 4, df = 29805, p-value = 0.00005
## alternative hypothesis: true difference in means between group female and group male is not equal to 0
## 95 percent confidence interval:
##  0.2723 0.7841
## sample estimates:
## mean in group female   mean in group male 
##                4.873                4.345</code></pre>
<p>Again, the ultimate piece of evidence we are looking for is the significance level, and in this case, it’s .00005. What does it mean? It means the chances are about 0.05% that males and females really had the same level of impact, which is the null hypothesis. Well, the chances are pretty low, aren’t they? Our null hypothesis doesn’t really hold, and we are confident enough to claim that females generate bigger impacts than males on the Twitter discourses using the co-hashtags of #BlackLivesMatter and #StopAsianHate, not just within our sample, but in the whole population of Twitter users.</p>
<div id="anova" class="section level3 hasAnchor" number="4.3.1">
<h3><span class="header-section-number">4.3.1</span> ANOVA<a href="statistical-analyses-of-two-variables.html#anova" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Sometimes, we are interested in comparing multiple groups rather than just two groups. The idea is pretty similar. Let’s say you want to increase the impact of your tweets, and you are wondering whether tweets with different sentiments would have different levels of impact. Specifically, <strong>the sentiments of tweets can be categorized into negative, neutral, or positive.</strong> In this case, we are dealing with two variables: <strong>sentiment as the independent variable and impact as the dependent variable</strong>. And the question comes down to this: <strong>do tweets with different sentiments generate different levels of impact on the related Twitter discourses?</strong> We want to know whether the impact generated from tweets with different sentiments differs from one another. In other words, we are comparing the means of impacts among the three groups of tweets that have negative, neutral, and positive sentiments, respectively. If they do differ, then we can figure out the most effective way of tweeting and the not-so-effective tweet types in terms of generating impact for us, based on which we can publish more tweets that tend to have a higher impact in the future.</p>
<p><strong>Analysis of variance (ANOVA)</strong> is the best method to answer this question. In simple words, <strong>ANOVA tests whether two or more group means are equal</strong>. Let’s say, for example, impacts generated from tweets with different sentiments are quite different, with negative tweets leading to much lower mean impacts (M = 3.346) than the other two (Ms = 6.887 &amp; 6.94), which indicates a large variation of impacts between tweets with different sentiments. Indeed, as shown in the results of ANOVA analysis, this test yielded a significance level at .000, which indicates that it’s very unlikely to observe no differences in impacts from tweets with different sentiments in the population. Hence, this gives us strong evidence that we need to reject our null hypothesis and accept the alternative hypothesis, which is tweets with different sentiments had different impacts.</p>
<p>Here is the related R code:</p>
<div class="sourceCode" id="cb164"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb164-1"><a href="statistical-analyses-of-two-variables.html#cb164-1" aria-hidden="true" tabindex="-1"></a><span class="fu">options</span>(<span class="at">scipen =</span> <span class="dv">999</span>) <span class="co"># turn off scientific notation for all variables</span></span>
<span id="cb164-2"><a href="statistical-analyses-of-two-variables.html#cb164-2" aria-hidden="true" tabindex="-1"></a><span class="fu">options</span>(<span class="at">digits =</span> <span class="dv">4</span>) <span class="co"># define the digits </span></span>
<span id="cb164-3"><a href="statistical-analyses-of-two-variables.html#cb164-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb164-4"><a href="statistical-analyses-of-two-variables.html#cb164-4" aria-hidden="true" tabindex="-1"></a>mean_impact_sentiment <span class="ot">&lt;-</span> data <span class="sc">%&gt;%</span> <span class="co">#calculate the mean impact for different sentiment</span></span>
<span id="cb164-5"><a href="statistical-analyses-of-two-variables.html#cb164-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(Sentiment) <span class="sc">%&gt;%</span> </span>
<span id="cb164-6"><a href="statistical-analyses-of-two-variables.html#cb164-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">Impact =</span> <span class="fu">mean</span>(Impact)) </span>
<span id="cb164-7"><a href="statistical-analyses-of-two-variables.html#cb164-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb164-8"><a href="statistical-analyses-of-two-variables.html#cb164-8" aria-hidden="true" tabindex="-1"></a>mean_impact_sentiment <span class="sc">%&gt;%</span> </span>
<span id="cb164-9"><a href="statistical-analyses-of-two-variables.html#cb164-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(Sentiment, Impact, <span class="at">fill =</span> Sentiment)) <span class="sc">+</span></span>
<span id="cb164-10"><a href="statistical-analyses-of-two-variables.html#cb164-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_col</span>() <span class="sc">+</span></span>
<span id="cb164-11"><a href="statistical-analyses-of-two-variables.html#cb164-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_fill_manual</span>(<span class="at">values=</span><span class="fu">c</span>(<span class="st">&quot;red&quot;</span>, <span class="st">&quot;gray&quot;</span>, <span class="st">&quot;green&quot;</span>)) <span class="co"># manually set the column color</span></span></code></pre></div>
<p><img src="bookdownproj_files/figure-html/unnamed-chunk-63-1.png" width="672" /></p>
<div class="sourceCode" id="cb165"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb165-1"><a href="statistical-analyses-of-two-variables.html#cb165-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Other mean plots</span></span>
<span id="cb165-2"><a href="statistical-analyses-of-two-variables.html#cb165-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(<span class="st">&quot;ggpubr&quot;</span>)</span>
<span id="cb165-3"><a href="statistical-analyses-of-two-variables.html#cb165-3" aria-hidden="true" tabindex="-1"></a><span class="fu">ggline</span>(data, <span class="at">x =</span> <span class="st">&quot;Sentiment&quot;</span>, <span class="at">y =</span> <span class="st">&quot;Impact&quot;</span>, </span>
<span id="cb165-4"><a href="statistical-analyses-of-two-variables.html#cb165-4" aria-hidden="true" tabindex="-1"></a>       <span class="at">add =</span> <span class="fu">c</span>(<span class="st">&quot;mean_se&quot;</span>), <span class="co"># Add error bars: mean_se</span></span>
<span id="cb165-5"><a href="statistical-analyses-of-two-variables.html#cb165-5" aria-hidden="true" tabindex="-1"></a>       <span class="at">order =</span> <span class="fu">c</span>(<span class="st">&quot;negative&quot;</span>, <span class="st">&quot;neutral&quot;</span>, <span class="st">&quot;positive&quot;</span>),</span>
<span id="cb165-6"><a href="statistical-analyses-of-two-variables.html#cb165-6" aria-hidden="true" tabindex="-1"></a>       <span class="at">ylab =</span> <span class="st">&quot;Impact&quot;</span>, <span class="at">xlab =</span> <span class="st">&quot;Sentiment&quot;</span>)</span></code></pre></div>
<p><img src="bookdownproj_files/figure-html/unnamed-chunk-63-2.png" width="672" /></p>
<div class="sourceCode" id="cb166"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb166-1"><a href="statistical-analyses-of-two-variables.html#cb166-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Box plot</span></span>
<span id="cb166-2"><a href="statistical-analyses-of-two-variables.html#cb166-2" aria-hidden="true" tabindex="-1"></a><span class="fu">boxplot</span>(Impact <span class="sc">~</span> Sentiment, <span class="at">data =</span> data,</span>
<span id="cb166-3"><a href="statistical-analyses-of-two-variables.html#cb166-3" aria-hidden="true" tabindex="-1"></a>        <span class="at">xlab =</span> <span class="st">&quot;Sentiment&quot;</span>, <span class="at">ylab =</span> <span class="st">&quot;Impact&quot;</span>,</span>
<span id="cb166-4"><a href="statistical-analyses-of-two-variables.html#cb166-4" aria-hidden="true" tabindex="-1"></a>        <span class="at">frame =</span> <span class="cn">FALSE</span>, <span class="at">col =</span> <span class="fu">c</span>(<span class="st">&quot;red&quot;</span>, <span class="st">&quot;grey&quot;</span>, <span class="st">&quot;green&quot;</span>))</span></code></pre></div>
<p><img src="bookdownproj_files/figure-html/unnamed-chunk-63-3.png" width="672" />
##ANOVA</p>
<div class="sourceCode" id="cb167"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb167-1"><a href="statistical-analyses-of-two-variables.html#cb167-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Compute the analysis of variance</span></span>
<span id="cb167-2"><a href="statistical-analyses-of-two-variables.html#cb167-2" aria-hidden="true" tabindex="-1"></a>anova <span class="ot">&lt;-</span> <span class="fu">aov</span>(Impact <span class="sc">~</span> Sentiment, <span class="at">data =</span> data)</span>
<span id="cb167-3"><a href="statistical-analyses-of-two-variables.html#cb167-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Summary of the analysis</span></span>
<span id="cb167-4"><a href="statistical-analyses-of-two-variables.html#cb167-4" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(anova)</span></code></pre></div>
<pre><code>##                Df  Sum Sq Mean Sq F value              Pr(&gt;F)
## Sentiment       2   88248   44124     350 &lt;0.0000000000000002
## Residuals   30516 3852570     126                            
##                
## Sentiment   ***
## Residuals      
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
</div>
</div>
<div id="correlation" class="section level2 hasAnchor" number="4.4">
<h2><span class="header-section-number">4.4</span> Correlation<a href="statistical-analyses-of-two-variables.html#correlation" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Another type of analysis we do quite often is assessing the relationship between two continuous (interval or ratio level) variables. For example, what’s the relationship between people’s <strong>education level and their income level</strong>? In other words, do people with higher education levels have a higher income? Questions like this can be answered by assessing the Pearson’s correlation (r) between two variables. Using our data as an example again, let’s say we are interested in knowing <strong>the relationship between the number of tweets Twitter authors created containing the co-hashtags of #BlackLivesMatter and #StopAsianHate and the impact of these tweets on the related discourses on Twitter.</strong> In other words, if we created more tweets containing these two hashtags, does that translate to a higher level of impact on the related Twitter discourses? If we run the correlation between the number of posts containing these two hashtags and tweets’ impact, the key statistics we got is r = .05, p = .000.</p>
<p>Here is the R code for calculating correlation:</p>
<div class="sourceCode" id="cb169"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb169-1"><a href="statistical-analyses-of-two-variables.html#cb169-1" aria-hidden="true" tabindex="-1"></a><span class="co">#correlations</span></span>
<span id="cb169-2"><a href="statistical-analyses-of-two-variables.html#cb169-2" aria-hidden="true" tabindex="-1"></a><span class="co"># normalize each variable first</span></span>
<span id="cb169-3"><a href="statistical-analyses-of-two-variables.html#cb169-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb169-4"><a href="statistical-analyses-of-two-variables.html#cb169-4" aria-hidden="true" tabindex="-1"></a>Impact <span class="ot">&lt;-</span> (data<span class="sc">$</span>Impact <span class="sc">-</span> <span class="fu">mean</span>(data<span class="sc">$</span>Impact))<span class="sc">/</span><span class="fu">sd</span>(data<span class="sc">$</span>Impact) </span>
<span id="cb169-5"><a href="statistical-analyses-of-two-variables.html#cb169-5" aria-hidden="true" tabindex="-1"></a>Post <span class="ot">&lt;-</span> (data<span class="sc">$</span>Post <span class="sc">-</span> <span class="fu">mean</span>(data<span class="sc">$</span>Post))<span class="sc">/</span><span class="fu">sd</span>(data<span class="sc">$</span>Post)</span>
<span id="cb169-6"><a href="statistical-analyses-of-two-variables.html#cb169-6" aria-hidden="true" tabindex="-1"></a>Correlation <span class="ot">&lt;-</span> <span class="fu">cor.test</span>(data<span class="sc">$</span>Post, data<span class="sc">$</span>Impact, </span>
<span id="cb169-7"><a href="statistical-analyses-of-two-variables.html#cb169-7" aria-hidden="true" tabindex="-1"></a>                <span class="at">method =</span> <span class="st">&quot;pearson&quot;</span>)</span>
<span id="cb169-8"><a href="statistical-analyses-of-two-variables.html#cb169-8" aria-hidden="true" tabindex="-1"></a>Correlation</span></code></pre></div>
<pre><code>## 
##  Pearson&#39;s product-moment correlation
## 
## data:  data$Post and data$Impact
## t = 7.9, df = 30517, p-value = 0.000000000000002
## alternative hypothesis: true correlation is not equal to 0
## 95 percent confidence interval:
##  0.03417 0.05656
## sample estimates:
##     cor 
## 0.04537</code></pre>
<p>In theory, the r value here can range from -1 to 1, and it tells us two things: <strong>(1) the direction of the relationship; and (2) the strength of the relationship.</strong> A positive r value indicates a positive relationship, during which two variables’ values move in the same direction, while a negative value indicates a negative relationship, in which the values of two variables move in the opposite directions. If you suspect that when people have a higher degree, they have a higher income level as well, you are hypothesizing a positive relationship, with the values of the two variables increasing at the same time. However, if you suspect that the longer time we spend playing video games, the lower GPA we will have, that’s a negative relationship in which the two variables move in the opposite directions, with one variable’s value decreasing as the other increases.
Now that we know the direction, what about the strength? <strong>An r value closer to 1 or -1 indicates a stronger relationship; while an r value closer to 0 indicates a weaker relationship or no relationship at all, in which one variable’s value does not move in any clear pattern as the other variable’s value changes.</strong></p>
<p>In fact, in social science, it’s quite unlikely that we observe a perfect correlation between two different variables. Why? Because most of the concepts we study in social science are pretty complicated and they are related to and influenced by many factors. For example, study time will no doubt affect our GPA, but it is not the only factor that does. Our learning methods, intelligence, and class participation, among many other factors, jointly shape our GPA. Therefore, how our GPA changes will not solely be dependent upon our study time.</p>
<p>Let’s return to the case of analyzing the relationship between the number of posts that contain the two hashtags (#BlackLivesMatter and #StopAsianHate) and the impact of tweets. Do you think these two variables would be correlated? Probably. If you tweet more about popular social issues, it is likely that your tweets will generate a higher impact for those social issues. The Pearson’s r we got between these two variables is .05, which is a positive value and hence indicates a positive relationship: as the number of posts containing these two hashtags increases, so does the impact of tweets for the related Twitter conversations. Then what about the strength of the relationship?</p>
<p>In social science, a correlation coefficient of <strong>0.05 is considered a weak relationship between two variables</strong>, meaning that when one variable increases, the other variable also tends to increase, but in a rather unreliable manner. In other words, when Twitter authors post more tweets using the co-hashtags in their tweets, it is likely that their tweets will generate higher impacts on the related Twitter discourses, and it is also likely that the impact level stays the same or will even be lower. The probability value, or what we call the p value, is below 0.05, which indicates that we can be confident enough to infer this relationship to a larger population. In other words, going beyond this one sample that we have, we can be confident enough that in the whole population of tweets, there is a positive correlation between a Twitter user’s number of posts containing these two hashtags and the impact of their tweets on the related Twitter discourses.</p>
</div>
<div id="regression" class="section level2 hasAnchor" number="4.5">
<h2><span class="header-section-number">4.5</span> Regression<a href="statistical-analyses-of-two-variables.html#regression" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>One of the most important goals we want to achieve in doing research is to predict. <strong>Simple linear regression</strong> is a technique that helps us predict the value of our dependent variable given the value of our independent variable. When we use this technique, statistical software will test whether each predictor plays a significant role in helping us predict the dependent variable by conducting a t-test and also calculate a regression equation for us in the form of Y = a + b*X, which represents the linear relationship between our independent variable and dependent variable and also allows us to estimate the value of Y given any value of X.</p>
<p>Let’s still use the example of Twitter user’s number of posts containing the two hashtags and the impact of their tweets. If we want to use the number of posts to predict impact, we just need to run a simple linear regression that regresses impact on the number of posts.</p>
<div class="sourceCode" id="cb171"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb171-1"><a href="statistical-analyses-of-two-variables.html#cb171-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Impact = b0 + b1*Post</span></span>
<span id="cb171-2"><a href="statistical-analyses-of-two-variables.html#cb171-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb171-3"><a href="statistical-analyses-of-two-variables.html#cb171-3" aria-hidden="true" tabindex="-1"></a>model1 <span class="ot">&lt;-</span> <span class="fu">lm</span>(data<span class="sc">$</span>Impact <span class="sc">~</span> data<span class="sc">$</span>Post) <span class="co">#regress the predictor and the outcome variables</span></span>
<span id="cb171-4"><a href="statistical-analyses-of-two-variables.html#cb171-4" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model1) <span class="co"># look into coefficients of the regression analysis &amp; r square</span></span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = data$Impact ~ data$Post)
## 
## Residuals:
##    Min     1Q Median     3Q    Max 
## -49.37  -4.55  -4.55  -4.55  95.05 
## 
## Coefficients:
##             Estimate Std. Error t value             Pr(&gt;|t|)
## (Intercept)   4.4264     0.0682   64.88 &lt; 0.0000000000000002
## data$Post     0.1281     0.0161    7.93   0.0000000000000022
##                
## (Intercept) ***
## data$Post   ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 11.4 on 30517 degrees of freedom
## Multiple R-squared:  0.00206,    Adjusted R-squared:  0.00203 
## F-statistic:   63 on 1 and 30517 DF,  p-value: 0.00000000000000219</code></pre>
<div class="sourceCode" id="cb173"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb173-1"><a href="statistical-analyses-of-two-variables.html#cb173-1" aria-hidden="true" tabindex="-1"></a><span class="co"># visualization</span></span>
<span id="cb173-2"><a href="statistical-analyses-of-two-variables.html#cb173-2" aria-hidden="true" tabindex="-1"></a>Post <span class="ot">&lt;-</span> data<span class="sc">$</span>Post</span>
<span id="cb173-3"><a href="statistical-analyses-of-two-variables.html#cb173-3" aria-hidden="true" tabindex="-1"></a>Impact <span class="ot">&lt;-</span> data<span class="sc">$</span>Impact</span>
<span id="cb173-4"><a href="statistical-analyses-of-two-variables.html#cb173-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb173-5"><a href="statistical-analyses-of-two-variables.html#cb173-5" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(data, <span class="fu">aes</span>(<span class="at">x =</span> Post, <span class="at">y =</span> Impact)) <span class="sc">+</span> </span>
<span id="cb173-6"><a href="statistical-analyses-of-two-variables.html#cb173-6" aria-hidden="true" tabindex="-1"></a>  <span class="co">#create scatterplots</span></span>
<span id="cb173-7"><a href="statistical-analyses-of-two-variables.html#cb173-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span> </span>
<span id="cb173-8"><a href="statistical-analyses-of-two-variables.html#cb173-8" aria-hidden="true" tabindex="-1"></a>  <span class="co">#linear regression line</span></span>
<span id="cb173-9"><a href="statistical-analyses-of-two-variables.html#cb173-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">&#39;lm&#39;</span>, <span class="at">size =</span> <span class="dv">2</span>, <span class="at">alpha =</span> <span class="fl">0.75</span>) <span class="sc">+</span> </span>
<span id="cb173-10"><a href="statistical-analyses-of-two-variables.html#cb173-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">xlab</span>(<span class="st">&quot;Posts&quot;</span>) <span class="sc">+</span> </span>
<span id="cb173-11"><a href="statistical-analyses-of-two-variables.html#cb173-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ylab</span>(<span class="st">&quot;Impacts&quot;</span>)</span></code></pre></div>
<pre><code>## `geom_smooth()` using formula = &#39;y ~ x&#39;</code></pre>
<p><img src="bookdownproj_files/figure-html/unnamed-chunk-66-1.png" width="672" /></p>
<p>The t-test returned us a t value of 7.93, and the p value associated with it is less than .0001, which indicates that the number of posts is indeed a significant predictor of impact. The equation we got is Y = 4.59 + 0.52*X, with X representing our independent variable, number of posts, and Y representing our dependent variable, impact. Now all we need to do is plug in the value of X and then we will get an estimation of Y.</p>
<p>Let’s say I have ten posts that contain the two hashtags, then the estimated impact on the related Twitter discourse is: Impact = 4.59 + 0.52*10= 9.79.</p>
<p>If another user has 20 posts like this, then he or she would most likely create a bigger impact = 4.59 + 0.52*20= 14.99. In this way, once we’ve known a Twitter user’s number of posts containing these two hashtags, we could have a pretty good prediction of the impact his or her tweets might generate.</p>
<p>In a regression analysis, the independent variable can not only be a continuous variable, it can also be a nominal or ordinal level variable. For example, we are wondering to what extent the gender of the Twitter influencers affects their impacts, and we can regress impact on gender to find out. Gender is a nominal variable with two attributes: Twitter influencers are either male (coded as 0) or female (coded as 1). The regression equation we got was **Impact = 4.34 +0.52*Gender**.</p>
<div class="sourceCode" id="cb175"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb175-1"><a href="statistical-analyses-of-two-variables.html#cb175-1" aria-hidden="true" tabindex="-1"></a><span class="co">#create factors</span></span>
<span id="cb175-2"><a href="statistical-analyses-of-two-variables.html#cb175-2" aria-hidden="true" tabindex="-1"></a>gender <span class="ot">&lt;-</span> <span class="fu">factor</span>(data<span class="sc">$</span>Gender_D, <span class="fu">c</span>(<span class="dv">0</span>,<span class="dv">1</span>), <span class="at">labels=</span><span class="fu">c</span>(<span class="st">&#39;Male&#39;</span>, <span class="st">&#39;Female&#39;</span>))</span>
<span id="cb175-3"><a href="statistical-analyses-of-two-variables.html#cb175-3" aria-hidden="true" tabindex="-1"></a><span class="fu">contrasts</span>(gender)</span></code></pre></div>
<pre><code>##        Female
## Male        0
## Female      1</code></pre>
<div class="sourceCode" id="cb177"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb177-1"><a href="statistical-analyses-of-two-variables.html#cb177-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Impact = b0 + b1*gender</span></span>
<span id="cb177-2"><a href="statistical-analyses-of-two-variables.html#cb177-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb177-3"><a href="statistical-analyses-of-two-variables.html#cb177-3" aria-hidden="true" tabindex="-1"></a>model2 <span class="ot">&lt;-</span> <span class="fu">lm</span>(data<span class="sc">$</span>Impact <span class="sc">~</span>gender)</span>
<span id="cb177-4"><a href="statistical-analyses-of-two-variables.html#cb177-4" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model2)</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = data$Impact ~ gender)
## 
## Residuals:
##    Min     1Q Median     3Q    Max 
##  -4.87  -4.87  -4.34  -4.34  94.73 
## 
## Coefficients:
##              Estimate Std. Error t value             Pr(&gt;|t|)
## (Intercept)    4.3448     0.0891   48.78 &lt; 0.0000000000000002
## genderFemale   0.5282     0.1303    4.05             0.000051
##                 
## (Intercept)  ***
## genderFemale ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 11.4 on 30517 degrees of freedom
## Multiple R-squared:  0.000538,   Adjusted R-squared:  0.000505 
## F-statistic: 16.4 on 1 and 30517 DF,  p-value: 0.0000509</code></pre>
<p>To predict the impact of each gender, we can simply plug in thevalues of gender. When influencers are male, their corresponding impact scorewould be: <strong>4.34 + 0.52<em>0 = 4.34<strong>. Female influencers’ impact score is: </strong>4.34 + 0.52</em>1= 4.86</strong>. Based on the equation, we could estimate the Twitter users’ impact score by just knowing their gender. We also can learn from this linear regression model that females had more impact on the Twitter discourses using the co-hashtags of#BlackLivesMatter and #StopAsianHate.</p>
<p>Another important statistic to look at in a regression test is <strong>R square</strong>, which indicates the portion of variance in the dependent variable that has been explained by the predictor(s). In this model, the R square is .0005, meaning that 0.05% of variance in impact could be explained by gender. As mentioned earlier, in social science, usually our dependent variables are jointly influenced by multiple factors, some of which we can successfully identify and some not. When the regression test results indicate that 0.05% of the variance in impact has been explained by gender, we know that the rest of the 99.5% of variance in impact could be explained by many other factors jointly.</p>

</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="statistical-analyses-of-a-single-variable.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="statistical-analyses-of-three-or-more-variables-modelling.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"whatsapp": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": "https://github.com/jennyjiangke/book/edit/master/04-Statistical_Analyses_of_Two_Variables.Rmd",
"text": "Edit"
},
"history": {
"link": null,
"text": null
},
"view": {
"link": "https://github.com/jennyjiangke/book/blob/master/04-Statistical_Analyses_of_Two_Variables.Rmd",
"text": null
},
"download": null,
"search": {
"engine": "fuse",
"options": null
},
"toc": {
"collapse": "subsection"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
