<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Chapter 5 Statistical Analyses of Three or More Variables &amp; Modelling | Media Analytics With R</title>
  <meta name="description" content="Chapter 5 Statistical Analyses of Three or More Variables &amp; Modelling | Media Analytics With R" />
  <meta name="generator" content="bookdown 0.26 and GitBook 2.6.7" />

  <meta property="og:title" content="Chapter 5 Statistical Analyses of Three or More Variables &amp; Modelling | Media Analytics With R" />
  <meta property="og:type" content="book" />
  
  
  

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Chapter 5 Statistical Analyses of Three or More Variables &amp; Modelling | Media Analytics With R" />
  
  
  

<meta name="author" content="Jenny Jiang &amp; Brian Walsh" />


<meta name="date" content="2023-02-26" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="statistical-analyses-of-two-variables.html"/>
<link rel="next" href="text-analysis.html"/>
<script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fuse.js@6.4.6/dist/fuse.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />








<link href="libs/anchor-sections-1.1.0/anchor-sections.css" rel="stylesheet" />
<link href="libs/anchor-sections-1.1.0/anchor-sections-hash.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.1.0/anchor-sections.js"></script>
<script src="libs/kePrint-0.0.1/kePrint.js"></script>
<link href="libs/lightable-0.0.1/lightable.css" rel="stylesheet" />


<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>


<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">Media Analytics with R</a></li>

<li class="divider"></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>Preface</a>
<ul>
<li class="chapter" data-level="0.1" data-path="index.html"><a href="index.html#who-is-this-book-for"><i class="fa fa-check"></i><b>0.1</b> Who is this book for?</a></li>
<li class="chapter" data-level="0.2" data-path="index.html"><a href="index.html#why-r"><i class="fa fa-check"></i><b>0.2</b> Why R?</a></li>
<li class="chapter" data-level="0.3" data-path="index.html"><a href="index.html#what-will-we-learn-to-do-with-r-in-this-book"><i class="fa fa-check"></i><b>0.3</b> What will we learn to do with R in this book?</a></li>
<li class="chapter" data-level="0.4" data-path="index.html"><a href="index.html#installing-the-software"><i class="fa fa-check"></i><b>0.4</b> Installing the Software</a></li>
<li class="chapter" data-level="0.5" data-path="index.html"><a href="index.html#getting-started"><i class="fa fa-check"></i><b>0.5</b> Getting Started</a></li>
<li class="chapter" data-level="0.6" data-path="index.html"><a href="index.html#r-studio-projects"><i class="fa fa-check"></i><b>0.6</b> R Studio Projects</a></li>
</ul></li>
<li class="chapter" data-level="1" data-path="intro-to-programming-in-r.html"><a href="intro-to-programming-in-r.html"><i class="fa fa-check"></i><b>1</b> Intro to Programming in R</a>
<ul>
<li class="chapter" data-level="1.1" data-path="intro-to-programming-in-r.html"><a href="intro-to-programming-in-r.html#creating-a-new-project-in-r-studio"><i class="fa fa-check"></i><b>1.1</b> Creating a New Project in R Studio</a></li>
<li class="chapter" data-level="1.2" data-path="intro-to-programming-in-r.html"><a href="intro-to-programming-in-r.html#loading-packages-and-data"><i class="fa fa-check"></i><b>1.2</b> Loading Packages and Data</a></li>
<li class="chapter" data-level="1.3" data-path="intro-to-programming-in-r.html"><a href="intro-to-programming-in-r.html#section"><i class="fa fa-check"></i><b>1.3</b> %&gt;%</a></li>
<li class="chapter" data-level="1.4" data-path="intro-to-programming-in-r.html"><a href="intro-to-programming-in-r.html#filtering-data"><i class="fa fa-check"></i><b>1.4</b> Filtering Data</a></li>
<li class="chapter" data-level="1.5" data-path="intro-to-programming-in-r.html"><a href="intro-to-programming-in-r.html#visualizing"><i class="fa fa-check"></i><b>1.5</b> Visualizing</a></li>
<li class="chapter" data-level="1.6" data-path="intro-to-programming-in-r.html"><a href="intro-to-programming-in-r.html#syntax"><i class="fa fa-check"></i><b>1.6</b> Syntax</a></li>
<li class="chapter" data-level="1.7" data-path="intro-to-programming-in-r.html"><a href="intro-to-programming-in-r.html#creating-variables"><i class="fa fa-check"></i><b>1.7</b> Creating Variables</a></li>
<li class="chapter" data-level="1.8" data-path="intro-to-programming-in-r.html"><a href="intro-to-programming-in-r.html#modifying-data"><i class="fa fa-check"></i><b>1.8</b> Modifying Data</a></li>
<li class="chapter" data-level="1.9" data-path="intro-to-programming-in-r.html"><a href="intro-to-programming-in-r.html#count"><i class="fa fa-check"></i><b>1.9</b> Count</a></li>
<li class="chapter" data-level="1.10" data-path="intro-to-programming-in-r.html"><a href="intro-to-programming-in-r.html#more-aesthetics"><i class="fa fa-check"></i><b>1.10</b> More Aesthetics</a></li>
<li class="chapter" data-level="1.11" data-path="intro-to-programming-in-r.html"><a href="intro-to-programming-in-r.html#review"><i class="fa fa-check"></i><b>1.11</b> Review</a></li>
</ul></li>
<li class="chapter" data-level="2" data-path="manipulating-data.html"><a href="manipulating-data.html"><i class="fa fa-check"></i><b>2</b> Manipulating Data</a>
<ul>
<li class="chapter" data-level="2.1" data-path="manipulating-data.html"><a href="manipulating-data.html#mutate"><i class="fa fa-check"></i><b>2.1</b> Mutate</a></li>
<li class="chapter" data-level="2.2" data-path="manipulating-data.html"><a href="manipulating-data.html#group_by-summarize"><i class="fa fa-check"></i><b>2.2</b> Group_by , Summarize()</a></li>
<li class="chapter" data-level="2.3" data-path="manipulating-data.html"><a href="manipulating-data.html#working-with-strings"><i class="fa fa-check"></i><b>2.3</b> Working with Strings</a>
<ul>
<li class="chapter" data-level="2.3.1" data-path="manipulating-data.html"><a href="manipulating-data.html#practical-applications-of-stringr"><i class="fa fa-check"></i><b>2.3.1</b> Practical Applications of Stringr</a></li>
</ul></li>
<li class="chapter" data-level="2.4" data-path="manipulating-data.html"><a href="manipulating-data.html#average-name-length-over-time"><i class="fa fa-check"></i><b>2.4</b> Average name length over time</a></li>
<li class="chapter" data-level="2.5" data-path="manipulating-data.html"><a href="manipulating-data.html#revisiting-summarize"><i class="fa fa-check"></i><b>2.5</b> Revisiting summarize()</a></li>
<li class="chapter" data-level="2.6" data-path="manipulating-data.html"><a href="manipulating-data.html#additional-functions"><i class="fa fa-check"></i><b>2.6</b> Additional Functions</a></li>
<li class="chapter" data-level="2.7" data-path="manipulating-data.html"><a href="manipulating-data.html#case-study-born-without-a-proper-name"><i class="fa fa-check"></i><b>2.7</b> Case Study: Born Without A (Proper) Name</a></li>
<li class="chapter" data-level="2.8" data-path="manipulating-data.html"><a href="manipulating-data.html#assignment"><i class="fa fa-check"></i><b>2.8</b> Assignment</a></li>
</ul></li>
<li class="chapter" data-level="3" data-path="statistical-analyses-of-a-single-variable.html"><a href="statistical-analyses-of-a-single-variable.html"><i class="fa fa-check"></i><b>3</b> Statistical Analyses of a Single Variable</a>
<ul>
<li class="chapter" data-level="3.1" data-path="statistical-analyses-of-a-single-variable.html"><a href="statistical-analyses-of-a-single-variable.html#variables-levels-of-measurement"><i class="fa fa-check"></i><b>3.1</b> Variables &amp; Levels of Measurement</a>
<ul>
<li class="chapter" data-level="3.1.1" data-path="statistical-analyses-of-a-single-variable.html"><a href="statistical-analyses-of-a-single-variable.html#nominal-data"><i class="fa fa-check"></i><b>3.1.1</b> Nominal Data</a></li>
<li class="chapter" data-level="3.1.2" data-path="statistical-analyses-of-a-single-variable.html"><a href="statistical-analyses-of-a-single-variable.html#ordinal-data"><i class="fa fa-check"></i><b>3.1.2</b> Ordinal Data</a></li>
<li class="chapter" data-level="3.1.3" data-path="statistical-analyses-of-a-single-variable.html"><a href="statistical-analyses-of-a-single-variable.html#interval-data"><i class="fa fa-check"></i><b>3.1.3</b> Interval Data</a></li>
<li class="chapter" data-level="3.1.4" data-path="statistical-analyses-of-a-single-variable.html"><a href="statistical-analyses-of-a-single-variable.html#ratio-data"><i class="fa fa-check"></i><b>3.1.4</b> Ratio Data</a></li>
</ul></li>
<li class="chapter" data-level="3.2" data-path="statistical-analyses-of-a-single-variable.html"><a href="statistical-analyses-of-a-single-variable.html#frequency-distribution"><i class="fa fa-check"></i><b>3.2</b> Frequency Distribution</a></li>
<li class="chapter" data-level="3.3" data-path="statistical-analyses-of-a-single-variable.html"><a href="statistical-analyses-of-a-single-variable.html#percentage-change"><i class="fa fa-check"></i><b>3.3</b> Percentage Change</a></li>
<li class="chapter" data-level="3.4" data-path="statistical-analyses-of-a-single-variable.html"><a href="statistical-analyses-of-a-single-variable.html#relative-frequency"><i class="fa fa-check"></i><b>3.4</b> Relative Frequency</a></li>
<li class="chapter" data-level="3.5" data-path="statistical-analyses-of-a-single-variable.html"><a href="statistical-analyses-of-a-single-variable.html#percentage-points"><i class="fa fa-check"></i><b>3.5</b> Percentage Points</a></li>
<li class="chapter" data-level="3.6" data-path="statistical-analyses-of-a-single-variable.html"><a href="statistical-analyses-of-a-single-variable.html#rate"><i class="fa fa-check"></i><b>3.6</b> Rate</a></li>
<li class="chapter" data-level="3.7" data-path="statistical-analyses-of-a-single-variable.html"><a href="statistical-analyses-of-a-single-variable.html#ratio"><i class="fa fa-check"></i><b>3.7</b> Ratio</a></li>
<li class="chapter" data-level="3.8" data-path="statistical-analyses-of-a-single-variable.html"><a href="statistical-analyses-of-a-single-variable.html#central-tendency"><i class="fa fa-check"></i><b>3.8</b> Central Tendency</a></li>
<li class="chapter" data-level="3.9" data-path="statistical-analyses-of-a-single-variable.html"><a href="statistical-analyses-of-a-single-variable.html#data-variation"><i class="fa fa-check"></i><b>3.9</b> Data Variation</a></li>
<li class="chapter" data-level="3.10" data-path="statistical-analyses-of-a-single-variable.html"><a href="statistical-analyses-of-a-single-variable.html#assignment-analyzing-a-single-variable"><i class="fa fa-check"></i><b>3.10</b> Assignment: Analyzing a Single Variable</a></li>
</ul></li>
<li class="chapter" data-level="4" data-path="statistical-analyses-of-two-variables.html"><a href="statistical-analyses-of-two-variables.html"><i class="fa fa-check"></i><b>4</b> Statistical Analyses of Two Variables</a>
<ul>
<li class="chapter" data-level="4.1" data-path="statistical-analyses-of-two-variables.html"><a href="statistical-analyses-of-two-variables.html#cross-tab"><i class="fa fa-check"></i><b>4.1</b> Cross-tab</a></li>
<li class="chapter" data-level="4.2" data-path="statistical-analyses-of-two-variables.html"><a href="statistical-analyses-of-two-variables.html#independent-variable-vs.-dependent-variable"><i class="fa fa-check"></i><b>4.2</b> Independent Variable VS. Dependent Variable</a></li>
<li class="chapter" data-level="4.3" data-path="statistical-analyses-of-two-variables.html"><a href="statistical-analyses-of-two-variables.html#independent-sample-t-test"><i class="fa fa-check"></i><b>4.3</b> Independent sample T-Test</a>
<ul>
<li class="chapter" data-level="4.3.1" data-path="statistical-analyses-of-two-variables.html"><a href="statistical-analyses-of-two-variables.html#anova"><i class="fa fa-check"></i><b>4.3.1</b> ANOVA</a></li>
</ul></li>
<li class="chapter" data-level="4.4" data-path="statistical-analyses-of-two-variables.html"><a href="statistical-analyses-of-two-variables.html#correlation"><i class="fa fa-check"></i><b>4.4</b> Correlation</a></li>
<li class="chapter" data-level="4.5" data-path="statistical-analyses-of-two-variables.html"><a href="statistical-analyses-of-two-variables.html#regression"><i class="fa fa-check"></i><b>4.5</b> Regression</a></li>
</ul></li>
<li class="chapter" data-level="5" data-path="statistical-analyses-of-three-or-more-variables-modelling.html"><a href="statistical-analyses-of-three-or-more-variables-modelling.html"><i class="fa fa-check"></i><b>5</b> Statistical Analyses of Three or More Variables &amp; Modelling</a>
<ul>
<li class="chapter" data-level="5.1" data-path="statistical-analyses-of-three-or-more-variables-modelling.html"><a href="statistical-analyses-of-three-or-more-variables-modelling.html#linear-regression"><i class="fa fa-check"></i><b>5.1</b> linear Regression</a></li>
<li class="chapter" data-level="5.2" data-path="statistical-analyses-of-three-or-more-variables-modelling.html"><a href="statistical-analyses-of-three-or-more-variables-modelling.html#interaction-effects"><i class="fa fa-check"></i><b>5.2</b> Interaction Effects</a></li>
<li class="chapter" data-level="5.3" data-path="statistical-analyses-of-three-or-more-variables-modelling.html"><a href="statistical-analyses-of-three-or-more-variables-modelling.html#assignment-1"><i class="fa fa-check"></i><b>5.3</b> Assignment</a>
<ul>
<li class="chapter" data-level="5.3.1" data-path="statistical-analyses-of-three-or-more-variables-modelling.html"><a href="statistical-analyses-of-three-or-more-variables-modelling.html#linear-regression-and-correlation"><i class="fa fa-check"></i><b>5.3.1</b> Linear Regression and Correlation</a></li>
<li class="chapter" data-level="5.3.2" data-path="statistical-analyses-of-three-or-more-variables-modelling.html"><a href="statistical-analyses-of-three-or-more-variables-modelling.html#multiple-regression-analysis"><i class="fa fa-check"></i><b>5.3.2</b> Multiple Regression Analysis</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="6" data-path="text-analysis.html"><a href="text-analysis.html"><i class="fa fa-check"></i><b>6</b> Text Analysis</a>
<ul>
<li class="chapter" data-level="6.1" data-path="text-analysis.html"><a href="text-analysis.html#an-introduction-to-stringr"><i class="fa fa-check"></i><b>6.1</b> An Introduction to Stringr</a>
<ul>
<li class="chapter" data-level="6.1.1" data-path="text-analysis.html"><a href="text-analysis.html#practical-applications-of-stringr-1"><i class="fa fa-check"></i><b>6.1.1</b> Practical Applications of Stringr</a></li>
<li class="chapter" data-level="6.1.2" data-path="text-analysis.html"><a href="text-analysis.html#average-name-length-over-time-1"><i class="fa fa-check"></i><b>6.1.2</b> Average name length over time</a></li>
<li class="chapter" data-level="6.1.3" data-path="text-analysis.html"><a href="text-analysis.html#common-issue-example-most-common-3-letter-names"><i class="fa fa-check"></i><b>6.1.3</b> Common issue: (example: most common 3-letter names)</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="7" data-path="network-analysis.html"><a href="network-analysis.html"><i class="fa fa-check"></i><b>7</b> Network Analysis</a></li>
<li class="chapter" data-level="8" data-path="geo-spatial-analysis-and-visualizations.html"><a href="geo-spatial-analysis-and-visualizations.html"><i class="fa fa-check"></i><b>8</b> Geo-Spatial Analysis and Visualizations</a></li>
<li class="chapter" data-level="9" data-path="publishing.html"><a href="publishing.html"><i class="fa fa-check"></i><b>9</b> Publishing</a></li>
<li class="divider"></li>
<li><a href="https://github.com/rstudio/bookdown" target="blank">Published with bookdown</a></li>
</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Media Analytics With R</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="statistical-analyses-of-three-or-more-variables-modelling" class="section level1 hasAnchor" number="5">
<h1><span class="header-section-number">Chapter 5</span> Statistical Analyses of Three or More Variables &amp; Modelling<a href="statistical-analyses-of-three-or-more-variables-modelling.html#statistical-analyses-of-three-or-more-variables-modelling" class="anchor-section" aria-label="Anchor link to header"></a></h1>
<div id="linear-regression" class="section level2 hasAnchor" number="5.1">
<h2><span class="header-section-number">5.1</span> linear Regression<a href="statistical-analyses-of-three-or-more-variables-modelling.html#linear-regression" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Because many concepts in social science are complicated and jointly influenced by multiple factors, can we consider their influences simultaneously? The answer is yes. We can use multiple factors to predict our dependent variable. If we want to predict impact more accurately, we can consider including more than one independent variable in our model.</p>
<p>Knowing the gender of the influencer would certainly help, but remember, that only explains 0.05% of the variance in impact. Could the influencer type make a difference, too? To find that out, we can include both the gender and influencer type as predictors in our regression model. We will still need to use the regression equation to predict the value of impact given the values of the predictors.</p>
<div class="sourceCode" id="cb181"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb181-1"><a href="statistical-analyses-of-three-or-more-variables-modelling.html#cb181-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Impact = b0 + b1*influencerType + b2*gender</span></span>
<span id="cb181-2"><a href="statistical-analyses-of-three-or-more-variables-modelling.html#cb181-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb181-3"><a href="statistical-analyses-of-three-or-more-variables-modelling.html#cb181-3" aria-hidden="true" tabindex="-1"></a><span class="co">#create factors</span></span>
<span id="cb181-4"><a href="statistical-analyses-of-three-or-more-variables-modelling.html#cb181-4" aria-hidden="true" tabindex="-1"></a>gender <span class="ot">&lt;-</span> <span class="fu">factor</span>(data<span class="sc">$</span>Gender_D, <span class="fu">c</span>(<span class="dv">0</span>,<span class="dv">1</span>), <span class="at">labels=</span><span class="fu">c</span>(<span class="st">&#39;Male&#39;</span>, <span class="st">&#39;Female&#39;</span>))</span>
<span id="cb181-5"><a href="statistical-analyses-of-three-or-more-variables-modelling.html#cb181-5" aria-hidden="true" tabindex="-1"></a><span class="fu">contrasts</span>(gender)</span></code></pre></div>
<pre><code>##        Female
## Male        0
## Female      1</code></pre>
<div class="sourceCode" id="cb183"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb183-1"><a href="statistical-analyses-of-three-or-more-variables-modelling.html#cb183-1" aria-hidden="true" tabindex="-1"></a>influencer<span class="ot">&lt;-</span><span class="fu">factor</span>(data<span class="sc">$</span>InfluencerType_N, <span class="fu">c</span>(<span class="dv">1</span>,<span class="dv">2</span>,<span class="dv">3</span>,<span class="dv">4</span>), <span class="at">labels=</span><span class="fu">c</span>(<span class="st">&#39;nano&#39;</span>, <span class="st">&#39;micro&#39;</span>,<span class="st">&#39;macro&#39;</span>,<span class="st">&#39;mega&#39;</span>))</span>
<span id="cb183-2"><a href="statistical-analyses-of-three-or-more-variables-modelling.html#cb183-2" aria-hidden="true" tabindex="-1"></a><span class="fu">contrasts</span>(influencer)</span></code></pre></div>
<pre><code>##       micro macro mega
## nano      0     0    0
## micro     1     0    0
## macro     0     1    0
## mega      0     0    1</code></pre>
<div class="sourceCode" id="cb185"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb185-1"><a href="statistical-analyses-of-three-or-more-variables-modelling.html#cb185-1" aria-hidden="true" tabindex="-1"></a>model3 <span class="ot">&lt;-</span> <span class="fu">lm</span>(data<span class="sc">$</span>Impact <span class="sc">~</span> gender <span class="sc">+</span> influencer)</span>
<span id="cb185-2"><a href="statistical-analyses-of-three-or-more-variables-modelling.html#cb185-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model3)</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = data$Impact ~ gender + influencer)
## 
## Residuals:
##    Min     1Q Median     3Q    Max 
## -10.05  -3.45  -3.06  -3.06  74.44 
## 
## Coefficients:
##                 Estimate Std. Error t value             Pr(&gt;|t|)
## (Intercept)       3.0578     0.0694   44.03 &lt; 0.0000000000000002
## genderFemale      0.3879     0.1008    3.85              0.00012
## influencermicro  37.4046     0.2839  131.77 &lt; 0.0000000000000002
## influencermacro  58.6027     1.0825   54.14 &lt; 0.0000000000000002
## influencermega   75.5270     3.9286   19.22 &lt; 0.0000000000000002
##                    
## (Intercept)     ***
## genderFemale    ***
## influencermicro ***
## influencermacro ***
## influencermega  ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 8.78 on 30514 degrees of freedom
## Multiple R-squared:  0.403,  Adjusted R-squared:  0.402 
## F-statistic: 5.14e+03 on 4 and 30514 DF,  p-value: &lt;0.0000000000000002</code></pre>
<p>Because we have two independent variables now, the equation is <strong>Impact = 3.06 + 0.39 * Gender + 37.40 * InfluencerMicro + 58.56 * InfluencerMacro +75.50 * InfluencerMega</strong>. Note here that the variable of influencer type has been coded into three dummy variables with two values: 0 and 1. For example,Influencer Micro can take the value of either 0 or 1. When it takes the value of 1, it represents influencers at the micro level; when it takes the value of 0, it indicates that this influencer is not at the micro level. In other words, this influencer could be at nano, macro, or mega level.</p>
<p>To estimate the impact score, we just need to plug in the values of both predictors. If we have a male influencer at the micro level, the impact score would be 3.06 + 0.39 * 0 + 37.40 * 1 + 58.56 * 0 + 75.50 * 0 = 40.46. If it’s a female influencer at the mega level, her impact score would be 3.06 + 0.39 * 1 + 37.40 * 0 + 58.56 * 0 + 75.50 * 1 = 78.95, which is much higher compared to the male influencer at the micro level. You can see that the R-square of this model increased to 0.4 indicating 40% of variance in impact could be explained by gender and influencer type.</p>
</div>
<div id="interaction-effects" class="section level2 hasAnchor" number="5.2">
<h2><span class="header-section-number">5.2</span> Interaction Effects<a href="statistical-analyses-of-three-or-more-variables-modelling.html#interaction-effects" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Furthermore, could the relationship between the influencer type and impact depend on the gender of Twitter authors? If we suspect that gender might further influence the direction and/or the strength of the relationship between the influencer type and impact score, we can add in an interaction term of gender and influencer type by multiplying these two terms.</p>
<div class="sourceCode" id="cb187"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb187-1"><a href="statistical-analyses-of-three-or-more-variables-modelling.html#cb187-1" aria-hidden="true" tabindex="-1"></a><span class="co">#interaction effects</span></span>
<span id="cb187-2"><a href="statistical-analyses-of-three-or-more-variables-modelling.html#cb187-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb187-3"><a href="statistical-analyses-of-three-or-more-variables-modelling.html#cb187-3" aria-hidden="true" tabindex="-1"></a>model4 <span class="ot">&lt;-</span> <span class="fu">lm</span>(data<span class="sc">$</span>Impact <span class="sc">~</span> gender<span class="sc">*</span>influencer)</span>
<span id="cb187-4"><a href="statistical-analyses-of-three-or-more-variables-modelling.html#cb187-4" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model4)</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = data$Impact ~ gender * influencer)
## 
## Residuals:
##    Min     1Q Median     3Q    Max 
## -13.90  -3.47  -3.04  -3.04  74.46 
## 
## Coefficients:
##                              Estimate Std. Error t value
## (Intercept)                     3.037      0.070   43.38
## genderFemale                    0.433      0.103    4.22
## influencermicro                38.172      0.404   94.56
## influencermacro                58.170      1.357   42.87
## influencermega                 71.063      5.071   14.01
## genderFemale:influencermicro   -1.518      0.568   -2.67
## genderFemale:influencermacro    1.201      2.250    0.53
## genderFemale:influencermega    11.167      8.018    1.39
##                                          Pr(&gt;|t|)    
## (Intercept)                  &lt; 0.0000000000000002 ***
## genderFemale                             0.000024 ***
## influencermicro              &lt; 0.0000000000000002 ***
## influencermacro              &lt; 0.0000000000000002 ***
## influencermega               &lt; 0.0000000000000002 ***
## genderFemale:influencermicro               0.0075 ** 
## genderFemale:influencermacro               0.5933    
## genderFemale:influencermega                0.1637    
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 8.78 on 30511 degrees of freedom
## Multiple R-squared:  0.403,  Adjusted R-squared:  0.403 
## F-statistic: 2.94e+03 on 7 and 30511 DF,  p-value: &lt;0.0000000000000002</code></pre>
<div class="sourceCode" id="cb189"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb189-1"><a href="statistical-analyses-of-three-or-more-variables-modelling.html#cb189-1" aria-hidden="true" tabindex="-1"></a><span class="co">#visualization</span></span>
<span id="cb189-2"><a href="statistical-analyses-of-three-or-more-variables-modelling.html#cb189-2" aria-hidden="true" tabindex="-1"></a>data_2 <span class="ot">&lt;-</span> data <span class="sc">%&gt;%</span> </span>
<span id="cb189-3"><a href="statistical-analyses-of-three-or-more-variables-modelling.html#cb189-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(Gender, InfluencerType) <span class="sc">%&gt;%</span> </span>
<span id="cb189-4"><a href="statistical-analyses-of-three-or-more-variables-modelling.html#cb189-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">Impact =</span> <span class="fu">mean</span>(Impact)) <span class="sc">%&gt;%</span></span>
<span id="cb189-5"><a href="statistical-analyses-of-three-or-more-variables-modelling.html#cb189-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">arrange</span>(<span class="fu">desc</span>(Impact))</span></code></pre></div>
<pre><code>## `summarise()` has grouped output by &#39;Gender&#39;. You can override
## using the `.groups` argument.</code></pre>
<div class="sourceCode" id="cb191"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb191-1"><a href="statistical-analyses-of-three-or-more-variables-modelling.html#cb191-1" aria-hidden="true" tabindex="-1"></a>data_2<span class="sc">$</span>InfluencerType <span class="ot">&lt;-</span> <span class="fu">factor</span>(data_2<span class="sc">$</span>InfluencerType,<span class="at">levels =</span> <span class="fu">c</span>(<span class="st">&quot;nano&quot;</span>, <span class="st">&quot;micro&quot;</span>, <span class="st">&quot;macro&quot;</span>, <span class="st">&quot;mega&quot;</span>)) <span class="co">#Re-order the sequence of influencer type</span></span>
<span id="cb191-2"><a href="statistical-analyses-of-three-or-more-variables-modelling.html#cb191-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb191-3"><a href="statistical-analyses-of-three-or-more-variables-modelling.html#cb191-3" aria-hidden="true" tabindex="-1"></a>data_2 <span class="sc">%&gt;%</span> </span>
<span id="cb191-4"><a href="statistical-analyses-of-three-or-more-variables-modelling.html#cb191-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>() <span class="sc">+</span></span>
<span id="cb191-5"><a href="statistical-analyses-of-three-or-more-variables-modelling.html#cb191-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">aes</span>(<span class="at">x =</span> InfluencerType, </span>
<span id="cb191-6"><a href="statistical-analyses-of-three-or-more-variables-modelling.html#cb191-6" aria-hidden="true" tabindex="-1"></a>      <span class="at">y =</span> Impact, </span>
<span id="cb191-7"><a href="statistical-analyses-of-three-or-more-variables-modelling.html#cb191-7" aria-hidden="true" tabindex="-1"></a>      <span class="at">color =</span> Gender) <span class="sc">+</span></span>
<span id="cb191-8"><a href="statistical-analyses-of-three-or-more-variables-modelling.html#cb191-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="fu">aes</span>(<span class="at">group =</span> Gender)) <span class="sc">+</span></span>
<span id="cb191-9"><a href="statistical-analyses-of-three-or-more-variables-modelling.html#cb191-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>()<span class="sc">+</span> </span>
<span id="cb191-10"><a href="statistical-analyses-of-three-or-more-variables-modelling.html#cb191-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ylab</span>(<span class="st">&quot;Impacts&quot;</span>)</span></code></pre></div>
<p><img src="bookdownproj_files/figure-html/unnamed-chunk-69-1.png" width="672" /></p>
<p>From the above statistics and graph, you can see the significant interaction effect between gender and influencer type for predicting impacts. Male micro influencers had a little bit higher impacts than female micro influeners. But for other types of influencers, such as megas, males had lower impacts than females.</p>
<p>Could the relationship between the numbers of post and impact also depend on the gender of Twitter authors? Let’s add in an interaction term of gender and the number of post by multiplying these two terms.</p>
<div class="sourceCode" id="cb192"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb192-1"><a href="statistical-analyses-of-three-or-more-variables-modelling.html#cb192-1" aria-hidden="true" tabindex="-1"></a><span class="co">#interaction effects of post and gender</span></span>
<span id="cb192-2"><a href="statistical-analyses-of-three-or-more-variables-modelling.html#cb192-2" aria-hidden="true" tabindex="-1"></a>post <span class="ot">&lt;-</span> data<span class="sc">$</span>Post</span>
<span id="cb192-3"><a href="statistical-analyses-of-three-or-more-variables-modelling.html#cb192-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb192-4"><a href="statistical-analyses-of-three-or-more-variables-modelling.html#cb192-4" aria-hidden="true" tabindex="-1"></a>model5 <span class="ot">&lt;-</span> <span class="fu">lm</span>(data<span class="sc">$</span>Impact <span class="sc">~</span> post<span class="sc">*</span>gender)</span>
<span id="cb192-5"><a href="statistical-analyses-of-three-or-more-variables-modelling.html#cb192-5" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model5)</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = data$Impact ~ post * gender)
## 
## Residuals:
##    Min     1Q Median     3Q    Max 
## -44.94  -4.85  -4.29  -4.29  94.75 
## 
## Coefficients:
##                   Estimate Std. Error t value
## (Intercept)         4.1396     0.0927   44.64
## post                0.1548     0.0197    7.84
## genderFemale        0.6382     0.1373    4.65
## post:genderFemale  -0.0784     0.0343   -2.29
##                               Pr(&gt;|t|)    
## (Intercept)       &lt; 0.0000000000000002 ***
## post                0.0000000000000047 ***
## genderFemale        0.0000033613215465 ***
## post:genderFemale                0.022 *  
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 11.3 on 30515 degrees of freedom
## Multiple R-squared:  0.00279,    Adjusted R-squared:  0.00269 
## F-statistic: 28.4 on 3 and 30515 DF,  p-value: &lt;0.0000000000000002</code></pre>
<div class="sourceCode" id="cb194"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb194-1"><a href="statistical-analyses-of-three-or-more-variables-modelling.html#cb194-1" aria-hidden="true" tabindex="-1"></a><span class="co">#model 5 visualization</span></span>
<span id="cb194-2"><a href="statistical-analyses-of-three-or-more-variables-modelling.html#cb194-2" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(data) <span class="sc">+</span></span>
<span id="cb194-3"><a href="statistical-analyses-of-three-or-more-variables-modelling.html#cb194-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">aes</span>(<span class="at">x =</span> Post, <span class="at">y =</span> Impact, <span class="at">color =</span> Gender) <span class="sc">+</span></span>
<span id="cb194-4"><a href="statistical-analyses-of-three-or-more-variables-modelling.html#cb194-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">color =</span> <span class="st">&quot;grey&quot;</span>) <span class="sc">+</span></span>
<span id="cb194-5"><a href="statistical-analyses-of-three-or-more-variables-modelling.html#cb194-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">&quot;lm&quot;</span>)<span class="sc">+</span> </span>
<span id="cb194-6"><a href="statistical-analyses-of-three-or-more-variables-modelling.html#cb194-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ylab</span>(<span class="st">&quot;Impacts&quot;</span>)</span></code></pre></div>
<pre><code>## `geom_smooth()` using formula = &#39;y ~ x&#39;</code></pre>
<p><img src="bookdownproj_files/figure-html/unnamed-chunk-70-1.png" width="672" /></p>
<p>The above visualization and statistics shows significant interaction effects (p = 0.022) between gender and the numbers of post when predicting impact. But the R square is only 0.0027 indicating less than 0.3% of the variance in impact can be explained by this model.The R square of previous model of interaction between gender and the number of posts is 0.403, indicating more than 40% of the variance in impact can be explained by this regression model, and thus representing a better model for predicting impacts.</p>
</div>
<div id="assignment-1" class="section level2 hasAnchor" number="5.3">
<h2><span class="header-section-number">5.3</span> Assignment<a href="statistical-analyses-of-three-or-more-variables-modelling.html#assignment-1" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<div id="linear-regression-and-correlation" class="section level3 hasAnchor" number="5.3.1">
<h3><span class="header-section-number">5.3.1</span> Linear Regression and Correlation<a href="statistical-analyses-of-three-or-more-variables-modelling.html#linear-regression-and-correlation" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p><strong>Learning Objective</strong>: Apply Linear Regression and Correlation analysis onto media analytics</p>
<p><strong>Step 1</strong>. Download your google analytic data. (GA-regression&amp;correlation.xlsx)</p>
<p><strong>Step 2</strong>. Download the case study R code ( Casestudy-GA.R) to import and clean your data.</p>
<p><strong>Step 3</strong>. Develop R code to run the regression analysis of:</p>
<ol style="list-style-type: lower-alpha">
<li><p>Users ~ Costs (Predicting Users using Costs)</p></li>
<li><p>Revenue ~ Costs (Predicting Revenue using Costs)</p></li>
</ol>
<p><strong>Step 4</strong>. Develop R code to plot the two regressions with trendlines.</p>
<p><strong>Step 5</strong>. Develop R code to run the correlation analysis between</p>
<ol style="list-style-type: lower-alpha">
<li><p>Users &amp; Costs</p></li>
<li><p>Revenue &amp; Costs</p></li>
</ol>
<p><strong>Step 6</strong>. Write a report briefly summarizing the results of regression and correlation analysis.</p>
<p><strong>Sample Report</strong></p>
<p>The results of correlation analysis indicated that there are strong negative correlations (r = -0.838) between Bounce Rate and Average Session Duration. The longer the Average Session Duration, the smaller the Bounce Rate.</p>
<p>The result of regression analysis is illustrated in the figure below. Specifically, the Bounce Rate could be predicted by the Average Session Duration. The linear regression equation is: Y = – 0.00149X + 0.724. The R^2 of the linear regression is 0.6961, indicating nearly 70% of the variance in Bounce Rate can be explained or predicted by the Average Session Duration.</p>
<div class="figure">
<img src="images/6.png" alt="" />
<p class="caption">R Studio’s first loading screen</p>
</div>
</div>
<div id="multiple-regression-analysis" class="section level3 hasAnchor" number="5.3.2">
<h3><span class="header-section-number">5.3.2</span> Multiple Regression Analysis<a href="statistical-analyses-of-three-or-more-variables-modelling.html#multiple-regression-analysis" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p><strong>Learning Objective</strong>: Apply Multiple Regression analysis onto media analytics.</p>
<p><strong>Step 1</strong>. Download the data of tweets containing the co-hashtags of #BlackLivesMatter and #StopAsianHate from BrandWatch (Tools – Downloads – New - Select Query: BLS &amp; SAH - Select a month data of your choice - Request Download). Download the data as an Excel file.</p>
<p><strong>Step 2</strong>. Download the case study R code (Casestudy_ml.R) to import and clean your data.</p>
<p><strong>Step 3</strong>. Develop your own code to run the multiple regression analysis of:</p>
<ol style="list-style-type: lower-alpha">
<li><p>Impacts ~ Gender + Influencer Type (Predicting Impacts using Gender and Influencer Type)</p></li>
<li><p>Impacts ~ Gender * Influencer Type (Predicting Impacts using Gender * Influencer Type)</p></li>
</ol>
<p><strong>Step 4</strong>. Develop your own code to plot the interaction effects.</p>
<p><strong>Step 5</strong>. Write a report briefly summarizing the results of the multiple regression analysis. (Sample report attached)</p>
<p><strong>Sample Report</strong></p>
<p>The result of the multiple linear regression analysis indicates that both gender and influencer type are significant predictors of impacts on the social media conversations of co-hashtags of #BlackLivesMatter and #StopAsianHate. The multiple linear regression equation is: Impact = 3.06 + 0.39 * GenderFemale + 37.40 * InfluencerMicro + 58.56 * InfluencerMacro + 75.50 * InfluencerMega. The R Square of the linear multiple regression is 0.4025, indicating 40% of the variance in Impact can be explained or predicted by gender and influencer type.</p>
<p>We also found a significant interaction effect between gender and influencer type (F = 3.14, p = 0.02426). The related regression equation is: Impact = 3.06 + 0.43 * GenderFemale + 38.17 * InfluencerMicro + 58.17 * InfluencerMacro + 71.06 * InfluencerMega - 1.52 * GenderFemale * InfluencerMicro + 1.20 * GenderFemale * InfluencerMacro + 11.17 * GenderFemale * InfluencerMega. The R Square of the interaction model is 0.4026, slightly better than the model containing only main effects.</p>
<p><img src="images/7.png" alt="R Studio’s first loading screen" />
The figure demonstrated the interaction effects: While females generally have more impacts on the social media conversations of co-hashtags of #BlackLivesMatter and #StopAsianHate, the female micro influencers’ impacts are slightly lower than male influencers.</p>

</div>
</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="statistical-analyses-of-two-variables.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="text-analysis.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"whatsapp": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": "https://github.com/jennyjiangke/book/edit/master/05-Statistical_Analyses_of_Three_or_More_Variables_Modelling.Rmd",
"text": "Edit"
},
"history": {
"link": null,
"text": null
},
"view": {
"link": "https://github.com/jennyjiangke/book/blob/master/05-Statistical_Analyses_of_Three_or_More_Variables_Modelling.Rmd",
"text": null
},
"download": null,
"search": {
"engine": "fuse",
"options": null
},
"toc": {
"collapse": "subsection"
}
});
});
</script>

</body>

</html>
