<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Chapter 3 Statistical Analyses of a Single Variable | Media Analytics With R</title>
  <meta name="description" content="Chapter 3 Statistical Analyses of a Single Variable | Media Analytics With R" />
  <meta name="generator" content="bookdown 0.26 and GitBook 2.6.7" />

  <meta property="og:title" content="Chapter 3 Statistical Analyses of a Single Variable | Media Analytics With R" />
  <meta property="og:type" content="book" />
  
  
  

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Chapter 3 Statistical Analyses of a Single Variable | Media Analytics With R" />
  
  
  

<meta name="author" content="Jenny Jiang &amp; Brian Walsh" />


<meta name="date" content="2023-02-17" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="manipulating-data.html"/>
<link rel="next" href="statistical-analyses-of-two-variables.html"/>
<script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fuse.js@6.4.6/dist/fuse.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />








<link href="libs/anchor-sections-1.1.0/anchor-sections.css" rel="stylesheet" />
<link href="libs/anchor-sections-1.1.0/anchor-sections-hash.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.1.0/anchor-sections.js"></script>
<script src="libs/kePrint-0.0.1/kePrint.js"></script>
<link href="libs/lightable-0.0.1/lightable.css" rel="stylesheet" />


<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>


<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">Media Analytics with R</a></li>

<li class="divider"></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>Preface</a>
<ul>
<li class="chapter" data-level="0.1" data-path="index.html"><a href="index.html#who-is-this-book-for"><i class="fa fa-check"></i><b>0.1</b> Who is this book for?</a></li>
<li class="chapter" data-level="0.2" data-path="index.html"><a href="index.html#why-r"><i class="fa fa-check"></i><b>0.2</b> Why R?</a></li>
<li class="chapter" data-level="0.3" data-path="index.html"><a href="index.html#what-will-we-learn-to-do-with-r-in-this-book"><i class="fa fa-check"></i><b>0.3</b> What will we learn to do with R in this book?</a></li>
<li class="chapter" data-level="0.4" data-path="index.html"><a href="index.html#installing-the-software"><i class="fa fa-check"></i><b>0.4</b> Installing the Software</a></li>
<li class="chapter" data-level="0.5" data-path="index.html"><a href="index.html#getting-started"><i class="fa fa-check"></i><b>0.5</b> Getting Started</a></li>
<li class="chapter" data-level="0.6" data-path="index.html"><a href="index.html#r-studio-projects"><i class="fa fa-check"></i><b>0.6</b> R Studio Projects</a></li>
</ul></li>
<li class="chapter" data-level="1" data-path="intro-to-programming-in-r.html"><a href="intro-to-programming-in-r.html"><i class="fa fa-check"></i><b>1</b> Intro to Programming in R</a>
<ul>
<li class="chapter" data-level="1.1" data-path="intro-to-programming-in-r.html"><a href="intro-to-programming-in-r.html#creating-a-new-project-in-r-studio"><i class="fa fa-check"></i><b>1.1</b> Creating a New Project in R Studio</a></li>
<li class="chapter" data-level="1.2" data-path="intro-to-programming-in-r.html"><a href="intro-to-programming-in-r.html#loading-packages-and-data"><i class="fa fa-check"></i><b>1.2</b> Loading Packages and Data</a></li>
<li class="chapter" data-level="1.3" data-path="intro-to-programming-in-r.html"><a href="intro-to-programming-in-r.html#section"><i class="fa fa-check"></i><b>1.3</b> %&gt;%</a></li>
<li class="chapter" data-level="1.4" data-path="intro-to-programming-in-r.html"><a href="intro-to-programming-in-r.html#filtering-data"><i class="fa fa-check"></i><b>1.4</b> Filtering Data</a></li>
<li class="chapter" data-level="1.5" data-path="intro-to-programming-in-r.html"><a href="intro-to-programming-in-r.html#visualizing"><i class="fa fa-check"></i><b>1.5</b> Visualizing</a></li>
<li class="chapter" data-level="1.6" data-path="intro-to-programming-in-r.html"><a href="intro-to-programming-in-r.html#syntax"><i class="fa fa-check"></i><b>1.6</b> Syntax</a></li>
<li class="chapter" data-level="1.7" data-path="intro-to-programming-in-r.html"><a href="intro-to-programming-in-r.html#creating-variables"><i class="fa fa-check"></i><b>1.7</b> Creating Variables</a></li>
<li class="chapter" data-level="1.8" data-path="intro-to-programming-in-r.html"><a href="intro-to-programming-in-r.html#modifying-data"><i class="fa fa-check"></i><b>1.8</b> Modifying Data</a></li>
<li class="chapter" data-level="1.9" data-path="intro-to-programming-in-r.html"><a href="intro-to-programming-in-r.html#count"><i class="fa fa-check"></i><b>1.9</b> Count</a></li>
<li class="chapter" data-level="1.10" data-path="intro-to-programming-in-r.html"><a href="intro-to-programming-in-r.html#more-aesthetics"><i class="fa fa-check"></i><b>1.10</b> More Aesthetics</a></li>
<li class="chapter" data-level="1.11" data-path="intro-to-programming-in-r.html"><a href="intro-to-programming-in-r.html#review"><i class="fa fa-check"></i><b>1.11</b> Review</a></li>
</ul></li>
<li class="chapter" data-level="2" data-path="manipulating-data.html"><a href="manipulating-data.html"><i class="fa fa-check"></i><b>2</b> Manipulating Data</a>
<ul>
<li class="chapter" data-level="2.1" data-path="manipulating-data.html"><a href="manipulating-data.html#mutate"><i class="fa fa-check"></i><b>2.1</b> Mutate</a></li>
<li class="chapter" data-level="2.2" data-path="manipulating-data.html"><a href="manipulating-data.html#group_by-summarize"><i class="fa fa-check"></i><b>2.2</b> Group_by , Summarize()</a></li>
<li class="chapter" data-level="2.3" data-path="manipulating-data.html"><a href="manipulating-data.html#working-with-strings"><i class="fa fa-check"></i><b>2.3</b> Working with Strings</a>
<ul>
<li class="chapter" data-level="2.3.1" data-path="manipulating-data.html"><a href="manipulating-data.html#practical-applications-of-stringr"><i class="fa fa-check"></i><b>2.3.1</b> Practical Applications of Stringr</a></li>
</ul></li>
<li class="chapter" data-level="2.4" data-path="manipulating-data.html"><a href="manipulating-data.html#average-name-length-over-time"><i class="fa fa-check"></i><b>2.4</b> Average name length over time</a></li>
<li class="chapter" data-level="2.5" data-path="manipulating-data.html"><a href="manipulating-data.html#revisiting-summarize"><i class="fa fa-check"></i><b>2.5</b> Revisiting summarize()</a></li>
<li class="chapter" data-level="2.6" data-path="manipulating-data.html"><a href="manipulating-data.html#additional-functions"><i class="fa fa-check"></i><b>2.6</b> Additional Functions</a></li>
<li class="chapter" data-level="2.7" data-path="manipulating-data.html"><a href="manipulating-data.html#case-study-born-without-a-proper-name"><i class="fa fa-check"></i><b>2.7</b> Case Study: Born Without A (Proper) Name</a></li>
<li class="chapter" data-level="2.8" data-path="manipulating-data.html"><a href="manipulating-data.html#assignment"><i class="fa fa-check"></i><b>2.8</b> Assignment</a></li>
</ul></li>
<li class="chapter" data-level="3" data-path="statistical-analyses-of-a-single-variable.html"><a href="statistical-analyses-of-a-single-variable.html"><i class="fa fa-check"></i><b>3</b> Statistical Analyses of a Single Variable</a>
<ul>
<li class="chapter" data-level="3.1" data-path="statistical-analyses-of-a-single-variable.html"><a href="statistical-analyses-of-a-single-variable.html#variables-levels-of-measurement"><i class="fa fa-check"></i><b>3.1</b> Variables &amp; Levels of Measurement</a>
<ul>
<li class="chapter" data-level="3.1.1" data-path="statistical-analyses-of-a-single-variable.html"><a href="statistical-analyses-of-a-single-variable.html#nominal-data"><i class="fa fa-check"></i><b>3.1.1</b> Nominal Data</a></li>
<li class="chapter" data-level="3.1.2" data-path="statistical-analyses-of-a-single-variable.html"><a href="statistical-analyses-of-a-single-variable.html#ordinal-data"><i class="fa fa-check"></i><b>3.1.2</b> Ordinal Data</a></li>
<li class="chapter" data-level="3.1.3" data-path="statistical-analyses-of-a-single-variable.html"><a href="statistical-analyses-of-a-single-variable.html#interval-data"><i class="fa fa-check"></i><b>3.1.3</b> Interval Data</a></li>
<li class="chapter" data-level="3.1.4" data-path="statistical-analyses-of-a-single-variable.html"><a href="statistical-analyses-of-a-single-variable.html#ratio-data"><i class="fa fa-check"></i><b>3.1.4</b> Ratio Data</a></li>
</ul></li>
<li class="chapter" data-level="3.2" data-path="statistical-analyses-of-a-single-variable.html"><a href="statistical-analyses-of-a-single-variable.html#frequency-distribution"><i class="fa fa-check"></i><b>3.2</b> Frequency Distribution</a></li>
<li class="chapter" data-level="3.3" data-path="statistical-analyses-of-a-single-variable.html"><a href="statistical-analyses-of-a-single-variable.html#percentage-change"><i class="fa fa-check"></i><b>3.3</b> Percentage Change</a></li>
<li class="chapter" data-level="3.4" data-path="statistical-analyses-of-a-single-variable.html"><a href="statistical-analyses-of-a-single-variable.html#relative-frequency"><i class="fa fa-check"></i><b>3.4</b> Relative Frequency</a></li>
<li class="chapter" data-level="3.5" data-path="statistical-analyses-of-a-single-variable.html"><a href="statistical-analyses-of-a-single-variable.html#percentage-points"><i class="fa fa-check"></i><b>3.5</b> Percentage Points</a></li>
<li class="chapter" data-level="3.6" data-path="statistical-analyses-of-a-single-variable.html"><a href="statistical-analyses-of-a-single-variable.html#rate"><i class="fa fa-check"></i><b>3.6</b> Rate</a></li>
<li class="chapter" data-level="3.7" data-path="statistical-analyses-of-a-single-variable.html"><a href="statistical-analyses-of-a-single-variable.html#ratio"><i class="fa fa-check"></i><b>3.7</b> Ratio</a></li>
<li class="chapter" data-level="3.8" data-path="statistical-analyses-of-a-single-variable.html"><a href="statistical-analyses-of-a-single-variable.html#central-tendency"><i class="fa fa-check"></i><b>3.8</b> Central Tendency</a></li>
<li class="chapter" data-level="3.9" data-path="statistical-analyses-of-a-single-variable.html"><a href="statistical-analyses-of-a-single-variable.html#data-variation"><i class="fa fa-check"></i><b>3.9</b> Data Variation</a></li>
<li class="chapter" data-level="3.10" data-path="statistical-analyses-of-a-single-variable.html"><a href="statistical-analyses-of-a-single-variable.html#assignment-analyzing-a-single-variable"><i class="fa fa-check"></i><b>3.10</b> Assignment: Analyzing a Single Variable</a></li>
</ul></li>
<li class="chapter" data-level="4" data-path="statistical-analyses-of-two-variables.html"><a href="statistical-analyses-of-two-variables.html"><i class="fa fa-check"></i><b>4</b> Statistical Analyses of Two Variables</a>
<ul>
<li class="chapter" data-level="4.1" data-path="statistical-analyses-of-two-variables.html"><a href="statistical-analyses-of-two-variables.html#cross-tab"><i class="fa fa-check"></i><b>4.1</b> Cross-tab</a></li>
<li class="chapter" data-level="4.2" data-path="statistical-analyses-of-two-variables.html"><a href="statistical-analyses-of-two-variables.html#independent-variable-vs.-dependent-variable"><i class="fa fa-check"></i><b>4.2</b> Independent Variable VS. Dependent Variable</a></li>
<li class="chapter" data-level="4.3" data-path="statistical-analyses-of-two-variables.html"><a href="statistical-analyses-of-two-variables.html#t-test"><i class="fa fa-check"></i><b>4.3</b> T-Test</a></li>
<li class="chapter" data-level="4.4" data-path="statistical-analyses-of-two-variables.html"><a href="statistical-analyses-of-two-variables.html#correlation"><i class="fa fa-check"></i><b>4.4</b> Correlation</a></li>
<li class="chapter" data-level="4.5" data-path="statistical-analyses-of-two-variables.html"><a href="statistical-analyses-of-two-variables.html#regression"><i class="fa fa-check"></i><b>4.5</b> Regression</a></li>
</ul></li>
<li class="chapter" data-level="5" data-path="statistical-analyses-of-three-or-more-variables-modelling.html"><a href="statistical-analyses-of-three-or-more-variables-modelling.html"><i class="fa fa-check"></i><b>5</b> Statistical Analyses of Three or More Variables &amp; Modelling</a></li>
<li class="chapter" data-level="6" data-path="text-analysis.html"><a href="text-analysis.html"><i class="fa fa-check"></i><b>6</b> Text Analysis</a>
<ul>
<li class="chapter" data-level="6.1" data-path="text-analysis.html"><a href="text-analysis.html#an-introduction-to-stringr"><i class="fa fa-check"></i><b>6.1</b> An Introduction to Stringr</a>
<ul>
<li class="chapter" data-level="6.1.1" data-path="text-analysis.html"><a href="text-analysis.html#practical-applications-of-stringr-1"><i class="fa fa-check"></i><b>6.1.1</b> Practical Applications of Stringr</a></li>
<li class="chapter" data-level="6.1.2" data-path="text-analysis.html"><a href="text-analysis.html#average-name-length-over-time-1"><i class="fa fa-check"></i><b>6.1.2</b> Average name length over time</a></li>
<li class="chapter" data-level="6.1.3" data-path="text-analysis.html"><a href="text-analysis.html#common-issue-example-most-common-3-letter-names"><i class="fa fa-check"></i><b>6.1.3</b> Common issue: (example: most common 3-letter names)</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="7" data-path="network-analysis.html"><a href="network-analysis.html"><i class="fa fa-check"></i><b>7</b> Network Analysis</a></li>
<li class="chapter" data-level="8" data-path="geo-spatial-analysis-and-visualizations.html"><a href="geo-spatial-analysis-and-visualizations.html"><i class="fa fa-check"></i><b>8</b> Geo-Spatial Analysis and Visualizations</a></li>
<li class="chapter" data-level="9" data-path="publishing.html"><a href="publishing.html"><i class="fa fa-check"></i><b>9</b> Publishing</a></li>
<li class="divider"></li>
<li><a href="https://github.com/rstudio/bookdown" target="blank">Published with bookdown</a></li>
</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Media Analytics With R</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="statistical-analyses-of-a-single-variable" class="section level1 hasAnchor" number="3">
<h1><span class="header-section-number">Chapter 3</span> Statistical Analyses of a Single Variable<a href="statistical-analyses-of-a-single-variable.html#statistical-analyses-of-a-single-variable" class="anchor-section" aria-label="Anchor link to header"></a></h1>
<p>This chapter uses data from Google Analytics’ channels report, which demonstrates how much of traffic is coming from specific paid versus unpaid channels to illustrate how to analyze a single variable.</p>
<p>Let’s import the Google Analytics’ channels report into RStudio.</p>
<div class="sourceCode" id="cb121"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb121-1"><a href="statistical-analyses-of-a-single-variable.html#cb121-1" aria-hidden="true" tabindex="-1"></a><span class="co">#You will need to install readxl package</span></span>
<span id="cb121-2"><a href="statistical-analyses-of-a-single-variable.html#cb121-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb121-3"><a href="statistical-analyses-of-a-single-variable.html#cb121-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(readxl) </span>
<span id="cb121-4"><a href="statistical-analyses-of-a-single-variable.html#cb121-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb121-5"><a href="statistical-analyses-of-a-single-variable.html#cb121-5" aria-hidden="true" tabindex="-1"></a>my_data <span class="ot">&lt;-</span> <span class="fu">read_excel</span>(<span class="st">&quot;google analytics sample data.xlsx&quot;</span>) <span class="co">#Create a dataset and name it as my_data</span></span></code></pre></div>
<p>Table 3.1 presents parts of a public demo data set of channels report from Google Analytics of Google Merchandise Store, which is an affiliate of the holding company, Google, and an e-commerce business site that deals with marketing and selling of Google, YouTube, and Android branded merchandise such as stationaries, bags among other products.</p>
<div class="sourceCode" id="cb122"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb122-1"><a href="statistical-analyses-of-a-single-variable.html#cb122-1" aria-hidden="true" tabindex="-1"></a><span class="co">#You will need to install kableExtra package</span></span>
<span id="cb122-2"><a href="statistical-analyses-of-a-single-variable.html#cb122-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(kableExtra)</span>
<span id="cb122-3"><a href="statistical-analyses-of-a-single-variable.html#cb122-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb122-4"><a href="statistical-analyses-of-a-single-variable.html#cb122-4" aria-hidden="true" tabindex="-1"></a>knitr<span class="sc">::</span><span class="fu">kable</span>(<span class="fu">head</span>(my_data[,<span class="dv">1</span><span class="sc">:</span><span class="dv">12</span>], <span class="dv">20</span>), <span class="at">digits =</span> <span class="dv">5</span>, <span class="at">booktabs =</span> <span class="cn">TRUE</span>,</span>
<span id="cb122-5"><a href="statistical-analyses-of-a-single-variable.html#cb122-5" aria-hidden="true" tabindex="-1"></a>  <span class="at">caption =</span> <span class="st">&#39;The First 20 Rows of the Google Analytics Sample Data&#39;</span></span>
<span id="cb122-6"><a href="statistical-analyses-of-a-single-variable.html#cb122-6" aria-hidden="true" tabindex="-1"></a>) <span class="sc">%&gt;%</span></span>
<span id="cb122-7"><a href="statistical-analyses-of-a-single-variable.html#cb122-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">kable_styling</span>(<span class="at">font_size =</span> <span class="fl">6.5</span>)</span></code></pre></div>
<table class="table" style="font-size: 6.5px; margin-left: auto; margin-right: auto;">
<caption style="font-size: initial !important;">
<span id="tab:unnamed-chunk-30">Table 3.1: </span>The First 20 Rows of the Google Analytics Sample Data
</caption>
<thead>
<tr>
<th style="text-align:left;">
Channel
</th>
<th style="text-align:left;">
Age
</th>
<th style="text-align:right;">
Users
</th>
<th style="text-align:right;">
New Users
</th>
<th style="text-align:right;">
Sessions
</th>
<th style="text-align:right;">
Bounce Rate
</th>
<th style="text-align:right;">
Pages / Session
</th>
<th style="text-align:right;">
Avg. Session Duration
</th>
<th style="text-align:right;">
Ecommerce Conversion Rate
</th>
<th style="text-align:right;">
Transactions
</th>
<th style="text-align:right;">
Revenue
</th>
<th style="text-align:right;">
Year
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
Direct
</td>
<td style="text-align:left;">
25-34
</td>
<td style="text-align:right;">
81822
</td>
<td style="text-align:right;">
76251
</td>
<td style="text-align:right;">
118241
</td>
<td style="text-align:right;">
0.42193
</td>
<td style="text-align:right;">
5.82467
</td>
<td style="text-align:right;">
227.6724
</td>
<td style="text-align:right;">
0.03649
</td>
<td style="text-align:right;">
4315
</td>
<td style="text-align:right;">
332771.829
</td>
<td style="text-align:right;">
2021
</td>
</tr>
<tr>
<td style="text-align:left;">
Direct
</td>
<td style="text-align:left;">
18-24
</td>
<td style="text-align:right;">
65506
</td>
<td style="text-align:right;">
61565
</td>
<td style="text-align:right;">
88898
</td>
<td style="text-align:right;">
0.47178
</td>
<td style="text-align:right;">
4.98222
</td>
<td style="text-align:right;">
199.7854
</td>
<td style="text-align:right;">
0.02642
</td>
<td style="text-align:right;">
2349
</td>
<td style="text-align:right;">
198848.060
</td>
<td style="text-align:right;">
2021
</td>
</tr>
<tr>
<td style="text-align:left;">
Direct
</td>
<td style="text-align:left;">
35-44
</td>
<td style="text-align:right;">
41947
</td>
<td style="text-align:right;">
38535
</td>
<td style="text-align:right;">
59313
</td>
<td style="text-align:right;">
0.42185
</td>
<td style="text-align:right;">
5.91531
</td>
<td style="text-align:right;">
229.8105
</td>
<td style="text-align:right;">
0.03842
</td>
<td style="text-align:right;">
2279
</td>
<td style="text-align:right;">
189792.736
</td>
<td style="text-align:right;">
2021
</td>
</tr>
<tr>
<td style="text-align:left;">
Direct
</td>
<td style="text-align:left;">
45-54
</td>
<td style="text-align:right;">
26800
</td>
<td style="text-align:right;">
24967
</td>
<td style="text-align:right;">
37477
</td>
<td style="text-align:right;">
0.44659
</td>
<td style="text-align:right;">
5.47669
</td>
<td style="text-align:right;">
226.9229
</td>
<td style="text-align:right;">
0.03421
</td>
<td style="text-align:right;">
1282
</td>
<td style="text-align:right;">
109531.822
</td>
<td style="text-align:right;">
2021
</td>
</tr>
<tr>
<td style="text-align:left;">
Direct
</td>
<td style="text-align:left;">
55-64
</td>
<td style="text-align:right;">
12981
</td>
<td style="text-align:right;">
12217
</td>
<td style="text-align:right;">
17703
</td>
<td style="text-align:right;">
0.46444
</td>
<td style="text-align:right;">
5.26922
</td>
<td style="text-align:right;">
213.1094
</td>
<td style="text-align:right;">
0.03474
</td>
<td style="text-align:right;">
615
</td>
<td style="text-align:right;">
54808.702
</td>
<td style="text-align:right;">
2021
</td>
</tr>
<tr>
<td style="text-align:left;">
Direct
</td>
<td style="text-align:left;">
65+
</td>
<td style="text-align:right;">
9432
</td>
<td style="text-align:right;">
8849
</td>
<td style="text-align:right;">
12548
</td>
<td style="text-align:right;">
0.46788
</td>
<td style="text-align:right;">
5.23932
</td>
<td style="text-align:right;">
210.5902
</td>
<td style="text-align:right;">
0.02981
</td>
<td style="text-align:right;">
374
</td>
<td style="text-align:right;">
35609.855
</td>
<td style="text-align:right;">
2021
</td>
</tr>
<tr>
<td style="text-align:left;">
Paid Search
</td>
<td style="text-align:left;">
18-24
</td>
<td style="text-align:right;">
2015
</td>
<td style="text-align:right;">
1766
</td>
<td style="text-align:right;">
2797
</td>
<td style="text-align:right;">
0.55703
</td>
<td style="text-align:right;">
4.71505
</td>
<td style="text-align:right;">
175.1087
</td>
<td style="text-align:right;">
0.02252
</td>
<td style="text-align:right;">
63
</td>
<td style="text-align:right;">
8423.719
</td>
<td style="text-align:right;">
2021
</td>
</tr>
<tr>
<td style="text-align:left;">
Paid Search
</td>
<td style="text-align:left;">
35-44
</td>
<td style="text-align:right;">
1394
</td>
<td style="text-align:right;">
1216
</td>
<td style="text-align:right;">
1980
</td>
<td style="text-align:right;">
0.47525
</td>
<td style="text-align:right;">
5.20909
</td>
<td style="text-align:right;">
157.2596
</td>
<td style="text-align:right;">
0.03535
</td>
<td style="text-align:right;">
70
</td>
<td style="text-align:right;">
8175.394
</td>
<td style="text-align:right;">
2021
</td>
</tr>
<tr>
<td style="text-align:left;">
Paid Search
</td>
<td style="text-align:left;">
25-34
</td>
<td style="text-align:right;">
2175
</td>
<td style="text-align:right;">
1829
</td>
<td style="text-align:right;">
3198
</td>
<td style="text-align:right;">
0.43809
</td>
<td style="text-align:right;">
5.88149
</td>
<td style="text-align:right;">
195.8474
</td>
<td style="text-align:right;">
0.03502
</td>
<td style="text-align:right;">
112
</td>
<td style="text-align:right;">
7576.795
</td>
<td style="text-align:right;">
2021
</td>
</tr>
<tr>
<td style="text-align:left;">
Direct
</td>
<td style="text-align:left;">
25-34
</td>
<td style="text-align:right;">
30772
</td>
<td style="text-align:right;">
29628
</td>
<td style="text-align:right;">
40539
</td>
<td style="text-align:right;">
0.37803
</td>
<td style="text-align:right;">
5.78436
</td>
<td style="text-align:right;">
233.6450
</td>
<td style="text-align:right;">
0.00306
</td>
<td style="text-align:right;">
124
</td>
<td style="text-align:right;">
7240.313
</td>
<td style="text-align:right;">
2020
</td>
</tr>
<tr>
<td style="text-align:left;">
Direct
</td>
<td style="text-align:left;">
18-24
</td>
<td style="text-align:right;">
17545
</td>
<td style="text-align:right;">
17024
</td>
<td style="text-align:right;">
21888
</td>
<td style="text-align:right;">
0.42708
</td>
<td style="text-align:right;">
5.07753
</td>
<td style="text-align:right;">
210.2462
</td>
<td style="text-align:right;">
0.00315
</td>
<td style="text-align:right;">
69
</td>
<td style="text-align:right;">
5325.412
</td>
<td style="text-align:right;">
2020
</td>
</tr>
<tr>
<td style="text-align:left;">
Direct
</td>
<td style="text-align:left;">
45-54
</td>
<td style="text-align:right;">
8491
</td>
<td style="text-align:right;">
8126
</td>
<td style="text-align:right;">
11115
</td>
<td style="text-align:right;">
0.38570
</td>
<td style="text-align:right;">
5.73117
</td>
<td style="text-align:right;">
230.9463
</td>
<td style="text-align:right;">
0.00495
</td>
<td style="text-align:right;">
55
</td>
<td style="text-align:right;">
4173.602
</td>
<td style="text-align:right;">
2020
</td>
</tr>
<tr>
<td style="text-align:left;">
Paid Search
</td>
<td style="text-align:left;">
45-54
</td>
<td style="text-align:right;">
1083
</td>
<td style="text-align:right;">
960
</td>
<td style="text-align:right;">
1387
</td>
<td style="text-align:right;">
0.56669
</td>
<td style="text-align:right;">
4.39726
</td>
<td style="text-align:right;">
138.6871
</td>
<td style="text-align:right;">
0.02307
</td>
<td style="text-align:right;">
32
</td>
<td style="text-align:right;">
4086.483
</td>
<td style="text-align:right;">
2021
</td>
</tr>
<tr>
<td style="text-align:left;">
Direct
</td>
<td style="text-align:left;">
35-44
</td>
<td style="text-align:right;">
14088
</td>
<td style="text-align:right;">
13560
</td>
<td style="text-align:right;">
18461
</td>
<td style="text-align:right;">
0.38248
</td>
<td style="text-align:right;">
5.53648
</td>
<td style="text-align:right;">
226.3607
</td>
<td style="text-align:right;">
0.00444
</td>
<td style="text-align:right;">
82
</td>
<td style="text-align:right;">
3993.809
</td>
<td style="text-align:right;">
2020
</td>
</tr>
<tr>
<td style="text-align:left;">
Organic Search
</td>
<td style="text-align:left;">
25-34
</td>
<td style="text-align:right;">
35978
</td>
<td style="text-align:right;">
32853
</td>
<td style="text-align:right;">
47132
</td>
<td style="text-align:right;">
0.51390
</td>
<td style="text-align:right;">
3.97070
</td>
<td style="text-align:right;">
164.3456
</td>
<td style="text-align:right;">
0.00068
</td>
<td style="text-align:right;">
32
</td>
<td style="text-align:right;">
1738.469
</td>
<td style="text-align:right;">
2020
</td>
</tr>
<tr>
<td style="text-align:left;">
(Other)
</td>
<td style="text-align:left;">
35-44
</td>
<td style="text-align:right;">
284
</td>
<td style="text-align:right;">
174
</td>
<td style="text-align:right;">
523
</td>
<td style="text-align:right;">
0.24474
</td>
<td style="text-align:right;">
7.62524
</td>
<td style="text-align:right;">
278.2505
</td>
<td style="text-align:right;">
0.03824
</td>
<td style="text-align:right;">
20
</td>
<td style="text-align:right;">
1657.444
</td>
<td style="text-align:right;">
2021
</td>
</tr>
<tr>
<td style="text-align:left;">
Direct
</td>
<td style="text-align:left;">
55-64
</td>
<td style="text-align:right;">
4466
</td>
<td style="text-align:right;">
4287
</td>
<td style="text-align:right;">
5862
</td>
<td style="text-align:right;">
0.40242
</td>
<td style="text-align:right;">
5.46571
</td>
<td style="text-align:right;">
232.1102
</td>
<td style="text-align:right;">
0.00409
</td>
<td style="text-align:right;">
24
</td>
<td style="text-align:right;">
1530.108
</td>
<td style="text-align:right;">
2020
</td>
</tr>
<tr>
<td style="text-align:left;">
(Other)
</td>
<td style="text-align:left;">
25-34
</td>
<td style="text-align:right;">
3440
</td>
<td style="text-align:right;">
2370
</td>
<td style="text-align:right;">
4741
</td>
<td style="text-align:right;">
0.31533
</td>
<td style="text-align:right;">
5.90719
</td>
<td style="text-align:right;">
232.4685
</td>
<td style="text-align:right;">
0.00337
</td>
<td style="text-align:right;">
16
</td>
<td style="text-align:right;">
1472.471
</td>
<td style="text-align:right;">
2020
</td>
</tr>
<tr>
<td style="text-align:left;">
(Other)
</td>
<td style="text-align:left;">
18-24
</td>
<td style="text-align:right;">
500
</td>
<td style="text-align:right;">
302
</td>
<td style="text-align:right;">
849
</td>
<td style="text-align:right;">
0.34982
</td>
<td style="text-align:right;">
5.61602
</td>
<td style="text-align:right;">
244.2697
</td>
<td style="text-align:right;">
0.03651
</td>
<td style="text-align:right;">
31
</td>
<td style="text-align:right;">
1395.053
</td>
<td style="text-align:right;">
2021
</td>
</tr>
<tr>
<td style="text-align:left;">
Paid Search
</td>
<td style="text-align:left;">
55-64
</td>
<td style="text-align:right;">
804
</td>
<td style="text-align:right;">
748
</td>
<td style="text-align:right;">
1009
</td>
<td style="text-align:right;">
0.62537
</td>
<td style="text-align:right;">
3.59068
</td>
<td style="text-align:right;">
111.0684
</td>
<td style="text-align:right;">
0.01388
</td>
<td style="text-align:right;">
14
</td>
<td style="text-align:right;">
1315.551
</td>
<td style="text-align:right;">
2021
</td>
</tr>
</tbody>
</table>
<p>See the bibliography at the end of the chapter for referral to the complete dataset that you can access and work with.</p>
<div id="variables-levels-of-measurement" class="section level2 hasAnchor" number="3.1">
<h2><span class="header-section-number">3.1</span> Variables &amp; Levels of Measurement<a href="statistical-analyses-of-a-single-variable.html#variables-levels-of-measurement" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>In a dataset, the columns identify the variables that represent certain qualities of individuals. Any quality that can vary can be considered a variable. Variables can take on different values or attributes. An attribute is a specific value on a variable. For example, gender might be a variable that we are interested in, and the attributes of gender could be male, female, transgender, and non-binary.</p>
<p>We use levels of measurement to describe how precisely variables are recorded. There are four levels of measurement: nominal, ordinal, interval, and ratio representing the transition from analyzing qualitative to quantitative data.</p>
<div id="nominal-data" class="section level3 hasAnchor" number="3.1.1">
<h3><span class="header-section-number">3.1.1</span> Nominal Data<a href="statistical-analyses-of-a-single-variable.html#nominal-data" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Nominal data is used to label variables. Gender, nationality, race, and ethnicity are a few of the most common examples of nominal data. It can only be categorized based on qualitative differences and there are no orderings or directions among different categories. We only know that males and females have qualitative differences in terms of gender, but we cannot tell how much they differ, nor could we sort individuals based on their gender. We can still assign numbers to different attributes of nominal variables (e.g., we can assign 1 to females and 2 to males, or vice versa), but the numbers only serve as labels that lack numerical values.</p>
<p>For the dataset of Google Analytics from Google Merchandise Store (Table 1), the variable <strong>Channel</strong> is measured at the nominal level, and it indicates the channel through which traffic got to Google Merchandise Store. <em>Organic Search</em> indicates visits from unpaid search results. <em>Direct</em> indicates visits where users navigated directly to the URL, or the source of the visit is unknown. <em>Referral</em> indicates traffic where users clicked a link from another site, excluding major search engines. <em>Display</em> indicates traffic from display advertising, such as Google AdWords remarketing campaigns. <em>Social</em> indicates visits from social networks (Facebook, Twitter, etc.). <em>Paid Search</em> indicates traffic from the PPC (Pay Per Click) campaigns run in search results.</p>
<p>Since each variable should be exhaustive to include all the possibilities, for the variable of Channel, the attribute “<em>Other</em>” is assigned referring to traffic from an un-identified channel. All these different channels through which a user reaches our website are different attributes our channel variable can have.</p>
</div>
<div id="ordinal-data" class="section level3 hasAnchor" number="3.1.2">
<h3><span class="header-section-number">3.1.2</span> Ordinal Data<a href="statistical-analyses-of-a-single-variable.html#ordinal-data" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Ordinal data also can be categorized, but there are rankings or orderings or scaling between categories. The ordinal measurement has been widely used to analyze variables such as education level (e.g., “high school,” “BS,” “MS,” “Ph.D.”), income level (e.g., “less than 50K,” “50-100K,” “over 100K”), and socioeconomic status (e.g., “lower class,” “middle class,” and “upper class”).</p>
<p>For the dataset of Google Analytics from Google Merchandise Store (Table 2.1), the variable <strong>Age</strong> is also ordinal, and it refers to the age group of the users. For such ordinal variable, we can turn it into quantitative by assigning numerical values to different categories.</p>
<p>For example, Age can be defined as having six attributes:1 = 18-24; 2 = 25-34; 3 = 35-44; 4 = 45-54; 5 = 55-64; 6 = 65+. There is a logical ordering among the different age groups, in a way that whoever answers “6” is older than individuals who answer “5” to this question. However, we cannot precisely tell the differences between the two groups because each attribute covers a wide range, and the ranges of different attributes are of different sizes.</p>
</div>
<div id="interval-data" class="section level3 hasAnchor" number="3.1.3">
<h3><span class="header-section-number">3.1.3</span> Interval Data<a href="statistical-analyses-of-a-single-variable.html#interval-data" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Interval data refers not only to the classification and ordering of data but also specifies that the distances between every two adjacent attributes on a scale are equal. For interval data, the difference between two values is meaningful, but there is no true zero point or fixed beginning, which refers to a scale where 0 indicates the absence of something.</p>
<p>The most popular example is the temperature in degrees Fahrenheit or Celsius. The difference between 90 degrees F and 80 degrees F is the same difference between 70 degrees F and 60 degrees F; however, when it comes to 0 degrees F, we cannot say that temperature no longer exists. For interval measures, the value 0 does not mean the absence of this variable; rather, it is just an arbitrary setting that we have agreed upon.</p>
<p>Another example of interval data is year. For year, 0 does not represent the missing value but indicates the year when Christ was born, and the time before 0 is given the prefix BC. If you were born in the year of 2005 and I was born in the year of 2000, we know that I will be five years older than you.</p>
<p>For the dataset of Google Analytics from Google Merchandise Store (Table 2.1), the only interval variable is <strong>Year</strong>, indicating the year of each observation.</p>
</div>
<div id="ratio-data" class="section level3 hasAnchor" number="3.1.4">
<h3><span class="header-section-number">3.1.4</span> Ratio Data<a href="statistical-analyses-of-a-single-variable.html#ratio-data" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>For ratio data, the difference between two values is also meaningful, and it has a true zero, indicating the absence of such variable. Media consumption is a great example of ratio data. Media consumption can be measured in days, hours, or minutes a person exposes him/herself to media content. If a person has zero media consumption, that means this person does not consume media at all; in other words, to this person, media consumption is absent.</p>
<p>For ratio data, zero is the starting point, and the distance between two adjacent values is the same. In addition, it makes sense to calculate the ratio of different values: If you have six hours of media consumption and I only have three hours, then we can say that you consume twice as much media as I do.</p>
<p>Table 2.1 has six ratio variables. <strong>Sessions</strong> are the total number of sessions within the date range. A session is the period time a user is actively engaged with the website of Google Merchandise Store. <strong>Users</strong> are the number of users who have initiated at least one session during the date range, with the value of zero representing no such user exists. <strong>New Users</strong> are the number of first-time users during the selected date range. <strong>Transactions</strong> are the number of completed purchases on Google Merchandise Store. <strong>Ecommerce Conversion Rate</strong> refers to the E-commerce conversion rate that is the percentage of sessions that resulted in an e-commerce transaction. <strong>Revenue</strong> refers to the revenue of the completed purchases. If the revenue from the display channel is 0, that just means there is no income produced by the display Ads.</p>
<p>What you can do to analyze your data may be limited due to the level of measurement of the variable. The complexity and precision of the level of measurement increase from nominal to ratio. For the ratio level of measurement, we can not only add numbers or subtract numbers but calculate the ratio of two numbers. For example, if the revenue from the organic search channel is 8k and from the paid search is 4k, then the revenue generated from organic search is twice as much as the revenue from paid search.</p>
<p>The rows in a spreadsheet are closely associated with the unit of analysis, which is one of the most important ideas in a research project and the major entity that you are analyzing in your study. You will need to determine the unit of analysis since it determines the analysis you do for your research.</p>
<p>For instance, if you are comparing the e-commerce performances (e.g., User, Sessions, Transactions, Revenues, ECR) of different channels, the unit of analysis is each individual channel. If you are comparing the e-commerce performance of different age groups, the unit of analysis is each age group. If you are comparing the e-commerce performance of different channels and age groups, the unit of analysis is each individual channel at each age group.</p>
<p>After defining your research questions and the related unit(s) of analysis, and levels of measurement, we may start the data analysis journey by conducting a statistical analysis of a single variable.</p>
</div>
</div>
<div id="frequency-distribution" class="section level2 hasAnchor" number="3.2">
<h2><span class="header-section-number">3.2</span> Frequency Distribution<a href="statistical-analyses-of-a-single-variable.html#frequency-distribution" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>The easiest thing we can do is to count the number of times an event or a value occurs for the variable(s) of our choice, and this is called Frequency analysis. We can aggregate individual observations of a variable into groups so that a frequency distribution of these groups can serve as a convenient means of summarizing or describing our data.</p>
<p>We are going to use the <strong>tidyverse</strong> package to count the aggregated transactions by channel and age groups.</p>
<div class="sourceCode" id="cb123"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb123-1"><a href="statistical-analyses-of-a-single-variable.html#cb123-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Frequency and grouped frequency analysis</span></span>
<span id="cb123-2"><a href="statistical-analyses-of-a-single-variable.html#cb123-2" aria-hidden="true" tabindex="-1"></a><span class="co">#You will need to install dplyr package</span></span>
<span id="cb123-3"><a href="statistical-analyses-of-a-single-variable.html#cb123-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb123-4"><a href="statistical-analyses-of-a-single-variable.html#cb123-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb123-5"><a href="statistical-analyses-of-a-single-variable.html#cb123-5" aria-hidden="true" tabindex="-1"></a>Transaction_Frequency_Channel <span class="ot">&lt;-</span> my_data <span class="sc">%&gt;%</span> </span>
<span id="cb123-6"><a href="statistical-analyses-of-a-single-variable.html#cb123-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(Channel) <span class="sc">%&gt;%</span> </span>
<span id="cb123-7"><a href="statistical-analyses-of-a-single-variable.html#cb123-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">Frequency =</span> <span class="fu">sum</span>(Transactions))</span>
<span id="cb123-8"><a href="statistical-analyses-of-a-single-variable.html#cb123-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb123-9"><a href="statistical-analyses-of-a-single-variable.html#cb123-9" aria-hidden="true" tabindex="-1"></a>Transaction_Frequency_Age <span class="ot">&lt;-</span> my_data <span class="sc">%&gt;%</span> </span>
<span id="cb123-10"><a href="statistical-analyses-of-a-single-variable.html#cb123-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(Age) <span class="sc">%&gt;%</span> </span>
<span id="cb123-11"><a href="statistical-analyses-of-a-single-variable.html#cb123-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">Frequency =</span> <span class="fu">sum</span>(Transactions))</span></code></pre></div>
<p>Table 3.2 demonstrated the grouped frequency of transactions for each channel and age group. From the frequency analysis, we can tell that the direct channel (n = 11581) and the age group of 25 to 34 (n = 4654) had the greatest number of transactions in Google Merchandise Store.</p>
<div class="sourceCode" id="cb124"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb124-1"><a href="statistical-analyses-of-a-single-variable.html#cb124-1" aria-hidden="true" tabindex="-1"></a>knitr<span class="sc">::</span><span class="fu">kable</span>(</span>
<span id="cb124-2"><a href="statistical-analyses-of-a-single-variable.html#cb124-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">list</span>(</span>
<span id="cb124-3"><a href="statistical-analyses-of-a-single-variable.html#cb124-3" aria-hidden="true" tabindex="-1"></a>    <span class="fu">head</span>(<span class="fu">arrange</span>(Transaction_Frequency_Channel, <span class="fu">desc</span>(Frequency))), </span>
<span id="cb124-4"><a href="statistical-analyses-of-a-single-variable.html#cb124-4" aria-hidden="true" tabindex="-1"></a>    <span class="fu">head</span>(<span class="fu">arrange</span>(Transaction_Frequency_Age, <span class="fu">desc</span>(Frequency)))), </span>
<span id="cb124-5"><a href="statistical-analyses-of-a-single-variable.html#cb124-5" aria-hidden="true" tabindex="-1"></a>  <span class="at">booktabs =</span> <span class="cn">TRUE</span>,</span>
<span id="cb124-6"><a href="statistical-analyses-of-a-single-variable.html#cb124-6" aria-hidden="true" tabindex="-1"></a>  <span class="at">caption =</span> <span class="st">&#39;Grouped Transaction Frequency for Channel and Age&#39;</span></span>
<span id="cb124-7"><a href="statistical-analyses-of-a-single-variable.html#cb124-7" aria-hidden="true" tabindex="-1"></a>) <span class="sc">%&gt;%</span></span>
<span id="cb124-8"><a href="statistical-analyses-of-a-single-variable.html#cb124-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">kable_styling</span>(<span class="at">font_size =</span> <span class="dv">14</span>)</span></code></pre></div>
<table class="kable_wrapper table" style="font-size: 14px; margin-left: auto; margin-right: auto;">
<caption style="font-size: initial !important;">
<span id="tab:unnamed-chunk-32">Table 3.2: </span>Grouped Transaction Frequency for Channel and Age
</caption>
<tbody>
<tr>
<td>
<table>
<thead>
<tr>
<th style="text-align:left;">
Channel
</th>
<th style="text-align:right;">
Frequency
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
Direct
</td>
<td style="text-align:right;">
11581
</td>
</tr>
<tr>
<td style="text-align:left;">
Paid Search
</td>
<td style="text-align:right;">
330
</td>
</tr>
<tr>
<td style="text-align:left;">
(Other)
</td>
<td style="text-align:right;">
138
</td>
</tr>
<tr>
<td style="text-align:left;">
Organic Search
</td>
<td style="text-align:right;">
98
</td>
</tr>
<tr>
<td style="text-align:left;">
Referral
</td>
<td style="text-align:right;">
32
</td>
</tr>
<tr>
<td style="text-align:left;">
Display
</td>
<td style="text-align:right;">
6
</td>
</tr>
</tbody>
</table>
</td>
<td>
<table>
<thead>
<tr>
<th style="text-align:left;">
Age
</th>
<th style="text-align:right;">
Frequency
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
25-34
</td>
<td style="text-align:right;">
4654
</td>
</tr>
<tr>
<td style="text-align:left;">
18-24
</td>
<td style="text-align:right;">
2558
</td>
</tr>
<tr>
<td style="text-align:left;">
35-44
</td>
<td style="text-align:right;">
2496
</td>
</tr>
<tr>
<td style="text-align:left;">
45-54
</td>
<td style="text-align:right;">
1394
</td>
</tr>
<tr>
<td style="text-align:left;">
55-64
</td>
<td style="text-align:right;">
673
</td>
</tr>
<tr>
<td style="text-align:left;">
65+
</td>
<td style="text-align:right;">
414
</td>
</tr>
</tbody>
</table>
</td>
</tr>
</tbody>
</table>
</div>
<div id="percentage-change" class="section level2 hasAnchor" number="3.3">
<h2><span class="header-section-number">3.3</span> Percentage Change<a href="statistical-analyses-of-a-single-variable.html#percentage-change" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Here, we can also use the grouped frequency analysis to compare the revenue from each channel between 2020 and 2021 to assess the dynamic changes of each channel.</p>
<div class="sourceCode" id="cb125"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb125-1"><a href="statistical-analyses-of-a-single-variable.html#cb125-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Creat a subset for year 2020 and year 2021</span></span>
<span id="cb125-2"><a href="statistical-analyses-of-a-single-variable.html#cb125-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb125-3"><a href="statistical-analyses-of-a-single-variable.html#cb125-3" aria-hidden="true" tabindex="-1"></a>my_data_2020 <span class="ot">&lt;-</span> my_data <span class="sc">%&gt;%</span> <span class="fu">filter</span>(Year <span class="sc">==</span> <span class="dv">2020</span>)</span>
<span id="cb125-4"><a href="statistical-analyses-of-a-single-variable.html#cb125-4" aria-hidden="true" tabindex="-1"></a>my_data_2021 <span class="ot">&lt;-</span> my_data <span class="sc">%&gt;%</span> <span class="fu">filter</span>(Year <span class="sc">==</span> <span class="dv">2021</span>)</span>
<span id="cb125-5"><a href="statistical-analyses-of-a-single-variable.html#cb125-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb125-6"><a href="statistical-analyses-of-a-single-variable.html#cb125-6" aria-hidden="true" tabindex="-1"></a>Revenue_Frequency_2020 <span class="ot">&lt;-</span> my_data_2020 <span class="sc">%&gt;%</span> </span>
<span id="cb125-7"><a href="statistical-analyses-of-a-single-variable.html#cb125-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(Channel) <span class="sc">%&gt;%</span> </span>
<span id="cb125-8"><a href="statistical-analyses-of-a-single-variable.html#cb125-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">Revenue =</span> <span class="fu">sum</span>(Revenue))</span>
<span id="cb125-9"><a href="statistical-analyses-of-a-single-variable.html#cb125-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb125-10"><a href="statistical-analyses-of-a-single-variable.html#cb125-10" aria-hidden="true" tabindex="-1"></a>Revenue_Frequency_2021 <span class="ot">&lt;-</span> my_data_2021 <span class="sc">%&gt;%</span> </span>
<span id="cb125-11"><a href="statistical-analyses-of-a-single-variable.html#cb125-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(Channel) <span class="sc">%&gt;%</span> </span>
<span id="cb125-12"><a href="statistical-analyses-of-a-single-variable.html#cb125-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">Revenue =</span> <span class="fu">sum</span>(Revenue))</span></code></pre></div>
<p>As illustrated in Table 3.3, the direct channel created the most revenues in both 2020 and 2021. When you have such data for two points in time, you can calculate how much change there has been over this period. The result is expressed as a percentage in absolute numbers and is called the percentage change or the rate of change. Here is the formula: <strong>Percentage Change = [(Number at later time / Number at earlier time) - 1] × 100%</strong>.</p>
<div class="sourceCode" id="cb126"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb126-1"><a href="statistical-analyses-of-a-single-variable.html#cb126-1" aria-hidden="true" tabindex="-1"></a>knitr<span class="sc">::</span><span class="fu">kable</span>(</span>
<span id="cb126-2"><a href="statistical-analyses-of-a-single-variable.html#cb126-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">list</span>(</span>
<span id="cb126-3"><a href="statistical-analyses-of-a-single-variable.html#cb126-3" aria-hidden="true" tabindex="-1"></a>    <span class="fu">head</span>(<span class="fu">arrange</span>(Revenue_Frequency_2020, <span class="fu">desc</span>(Revenue))), </span>
<span id="cb126-4"><a href="statistical-analyses-of-a-single-variable.html#cb126-4" aria-hidden="true" tabindex="-1"></a>    <span class="fu">head</span>(<span class="fu">arrange</span>(Revenue_Frequency_2021, <span class="fu">desc</span>(Revenue)))), </span>
<span id="cb126-5"><a href="statistical-analyses-of-a-single-variable.html#cb126-5" aria-hidden="true" tabindex="-1"></a>  <span class="at">booktabs =</span> <span class="cn">TRUE</span>,</span>
<span id="cb126-6"><a href="statistical-analyses-of-a-single-variable.html#cb126-6" aria-hidden="true" tabindex="-1"></a>  <span class="at">caption =</span> <span class="st">&#39;Grouped Revenue in 2020 and 2021&#39;</span></span>
<span id="cb126-7"><a href="statistical-analyses-of-a-single-variable.html#cb126-7" aria-hidden="true" tabindex="-1"></a>) <span class="sc">%&gt;%</span></span>
<span id="cb126-8"><a href="statistical-analyses-of-a-single-variable.html#cb126-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">kable_styling</span>(<span class="at">font_size =</span> <span class="dv">14</span>)</span></code></pre></div>
<table class="kable_wrapper table" style="font-size: 14px; margin-left: auto; margin-right: auto;">
<caption style="font-size: initial !important;">
<span id="tab:unnamed-chunk-34">Table 3.3: </span>Grouped Revenue in 2020 and 2021
</caption>
<tbody>
<tr>
<td>
<table>
<thead>
<tr>
<th style="text-align:left;">
Channel
</th>
<th style="text-align:right;">
Revenue
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
Direct
</td>
<td style="text-align:right;">
23565.6812
</td>
</tr>
<tr>
<td style="text-align:left;">
Organic Search
</td>
<td style="text-align:right;">
4628.4410
</td>
</tr>
<tr>
<td style="text-align:left;">
(Other)
</td>
<td style="text-align:right;">
3154.8063
</td>
</tr>
<tr>
<td style="text-align:left;">
Paid Search
</td>
<td style="text-align:right;">
1975.9309
</td>
</tr>
<tr>
<td style="text-align:left;">
Referral
</td>
<td style="text-align:right;">
864.7263
</td>
</tr>
<tr>
<td style="text-align:left;">
Social
</td>
<td style="text-align:right;">
164.8144
</td>
</tr>
</tbody>
</table>
</td>
<td>
<table>
<thead>
<tr>
<th style="text-align:left;">
Channel
</th>
<th style="text-align:right;">
Revenue
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
Direct
</td>
<td style="text-align:right;">
921363.0041
</td>
</tr>
<tr>
<td style="text-align:left;">
Paid Search
</td>
<td style="text-align:right;">
29908.1791
</td>
</tr>
<tr>
<td style="text-align:left;">
(Other)
</td>
<td style="text-align:right;">
5193.1180
</td>
</tr>
<tr>
<td style="text-align:left;">
Referral
</td>
<td style="text-align:right;">
852.0686
</td>
</tr>
<tr>
<td style="text-align:left;">
Display
</td>
<td style="text-align:right;">
354.3391
</td>
</tr>
<tr>
<td style="text-align:left;">
Organic Search
</td>
<td style="text-align:right;">
188.6451
</td>
</tr>
</tbody>
</table>
</td>
</tr>
</tbody>
</table>
<p>For example, from Table 3.3, in 2020, the revenue generated from the paid search channel was $1975.93. And in 2020, the revenue generated from the paid search channel was 29908.18. The percentage change of revenue from the paid search channel from 2020 to 2021 is then calculated as follows: <strong>[(29908.18/ 1975.93)-1] x 100%= 1413.62%</strong>, meaning that from the year of 2020 to the year of 2021, the revenue generated from the paid search channel increased by 1413.62%.</p>
</div>
<div id="relative-frequency" class="section level2 hasAnchor" number="3.4">
<h2><span class="header-section-number">3.4</span> Relative Frequency<a href="statistical-analyses-of-a-single-variable.html#relative-frequency" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>For the frequency analysis, we also can count how often something happens divided by all outcomes, which is called the relative frequency analysis. For example, from Table 3.3, the revenue from the organic search channel in 2020 is $4,628.44, and the total revenue in 2020 is the sum of revenue from all channels, which is $34422.26.The relative revenue from the organic search channel is 4,628.44/34422.26 = 13.44%, indicating 13.44% of the revenue in 2020 was from the organic search channel. We can use the codes below to get the relative revenue for each channel in 2020 and 2021 (Table 3.4).</p>
<div class="sourceCode" id="cb127"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb127-1"><a href="statistical-analyses-of-a-single-variable.html#cb127-1" aria-hidden="true" tabindex="-1"></a>Revenue_Relative_Frequency_2020 <span class="ot">&lt;-</span> my_data_2020 <span class="sc">%&gt;%</span> </span>
<span id="cb127-2"><a href="statistical-analyses-of-a-single-variable.html#cb127-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(Channel) <span class="sc">%&gt;%</span> </span>
<span id="cb127-3"><a href="statistical-analyses-of-a-single-variable.html#cb127-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="st">&#39;Revenue_Percentage&#39;</span> <span class="ot">=</span> <span class="fu">sum</span>(Revenue)<span class="sc">/</span><span class="fu">sum</span>(my_data_2020<span class="sc">$</span>Revenue))</span>
<span id="cb127-4"><a href="statistical-analyses-of-a-single-variable.html#cb127-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb127-5"><a href="statistical-analyses-of-a-single-variable.html#cb127-5" aria-hidden="true" tabindex="-1"></a>Revenue_Relative_Frequency_2021 <span class="ot">&lt;-</span> my_data_2021 <span class="sc">%&gt;%</span> </span>
<span id="cb127-6"><a href="statistical-analyses-of-a-single-variable.html#cb127-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(Channel) <span class="sc">%&gt;%</span> </span>
<span id="cb127-7"><a href="statistical-analyses-of-a-single-variable.html#cb127-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="st">&#39;Revenue_Percentage&#39;</span> <span class="ot">=</span> <span class="fu">sum</span>(Revenue)<span class="sc">/</span><span class="fu">sum</span>(my_data_2021<span class="sc">$</span>Revenue))</span></code></pre></div>
<div class="sourceCode" id="cb128"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb128-1"><a href="statistical-analyses-of-a-single-variable.html#cb128-1" aria-hidden="true" tabindex="-1"></a>knitr<span class="sc">::</span><span class="fu">kable</span>(</span>
<span id="cb128-2"><a href="statistical-analyses-of-a-single-variable.html#cb128-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">list</span>(</span>
<span id="cb128-3"><a href="statistical-analyses-of-a-single-variable.html#cb128-3" aria-hidden="true" tabindex="-1"></a>    <span class="fu">head</span>(<span class="fu">arrange</span>(Revenue_Relative_Frequency_2020, <span class="fu">desc</span>(Revenue_Percentage))), </span>
<span id="cb128-4"><a href="statistical-analyses-of-a-single-variable.html#cb128-4" aria-hidden="true" tabindex="-1"></a>    <span class="fu">head</span>(<span class="fu">arrange</span>(Revenue_Relative_Frequency_2021, <span class="fu">desc</span>(Revenue_Percentage)))), </span>
<span id="cb128-5"><a href="statistical-analyses-of-a-single-variable.html#cb128-5" aria-hidden="true" tabindex="-1"></a>  <span class="at">booktabs =</span> <span class="cn">TRUE</span>,</span>
<span id="cb128-6"><a href="statistical-analyses-of-a-single-variable.html#cb128-6" aria-hidden="true" tabindex="-1"></a>  <span class="at">caption =</span> <span class="st">&#39;Grouped Revenue in 2020 and 2021&#39;</span></span>
<span id="cb128-7"><a href="statistical-analyses-of-a-single-variable.html#cb128-7" aria-hidden="true" tabindex="-1"></a>) <span class="sc">%&gt;%</span></span>
<span id="cb128-8"><a href="statistical-analyses-of-a-single-variable.html#cb128-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">kable_styling</span>(<span class="at">font_size =</span> <span class="dv">14</span>)</span></code></pre></div>
<table class="kable_wrapper table" style="font-size: 14px; margin-left: auto; margin-right: auto;">
<caption style="font-size: initial !important;">
<span id="tab:unnamed-chunk-36">Table 3.4: </span>Grouped Revenue in 2020 and 2021
</caption>
<tbody>
<tr>
<td>
<table>
<thead>
<tr>
<th style="text-align:left;">
Channel
</th>
<th style="text-align:right;">
Revenue_Percentage
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
Direct
</td>
<td style="text-align:right;">
0.6846058
</td>
</tr>
<tr>
<td style="text-align:left;">
Organic Search
</td>
<td style="text-align:right;">
0.1344607
</td>
</tr>
<tr>
<td style="text-align:left;">
(Other)
</td>
<td style="text-align:right;">
0.0916502
</td>
</tr>
<tr>
<td style="text-align:left;">
Paid Search
</td>
<td style="text-align:right;">
0.0574027
</td>
</tr>
<tr>
<td style="text-align:left;">
Referral
</td>
<td style="text-align:right;">
0.0251211
</td>
</tr>
<tr>
<td style="text-align:left;">
Social
</td>
<td style="text-align:right;">
0.0047880
</td>
</tr>
</tbody>
</table>
</td>
<td>
<table>
<thead>
<tr>
<th style="text-align:left;">
Channel
</th>
<th style="text-align:right;">
Revenue_Percentage
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
Direct
</td>
<td style="text-align:right;">
0.9618529
</td>
</tr>
<tr>
<td style="text-align:left;">
Paid Search
</td>
<td style="text-align:right;">
0.0312225
</td>
</tr>
<tr>
<td style="text-align:left;">
(Other)
</td>
<td style="text-align:right;">
0.0054213
</td>
</tr>
<tr>
<td style="text-align:left;">
Referral
</td>
<td style="text-align:right;">
0.0008895
</td>
</tr>
<tr>
<td style="text-align:left;">
Display
</td>
<td style="text-align:right;">
0.0003699
</td>
</tr>
<tr>
<td style="text-align:left;">
Organic Search
</td>
<td style="text-align:right;">
0.0001969
</td>
</tr>
</tbody>
</table>
</td>
</tr>
</tbody>
</table>
</div>
<div id="percentage-points" class="section level2 hasAnchor" number="3.5">
<h2><span class="header-section-number">3.5</span> Percentage Points<a href="statistical-analyses-of-a-single-variable.html#percentage-points" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>We can use the term “percentage points” to compare two different percentages at two points in time. The best way to explain this is through an example: from Table 3.4, in 2020, the share of revenue from the Paid Search channel was 5.74%. In 2021, the share of revenue from the Paid Search channel was 3.12%. The difference of these two percentages is calculated in percentage points: 3.12 % - 5.74 % = -2.62%. This means that the share of revenue from Paid Search channel in 2021 was almost three percentage points lower than the share of revenue from the Paid Search channel in 2020.</p>
</div>
<div id="rate" class="section level2 hasAnchor" number="3.6">
<h2><span class="header-section-number">3.6</span> Rate<a href="statistical-analyses-of-a-single-variable.html#rate" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>In data analysis, some variables, such as the ECR (e-commerce conversion rate from Table 2.1), are too small to visualize. Under such circumstances, we can represent the percentage as rate by converting the small proportions to a whole number with one, two, or three digits on a base of some multiple of 1,000, 10,000, 100,000, or 1 million.</p>
<p>For example, from Table 3.1, in 2020, the Ecommerce Conversion Rate of the organic search channel for users of 25 to 34 is 0.00068 or 0.068%. Instead of reporting the percentage, we can move the decimal place farther to the right, sufficient to make a number greater than 1, which allows us to better visualize the data. In the case of Ecommerce Conversion Rate, moving the decimal point four places to the right is the same as multiplying the value by 10,000. Consequently, the Ecommerce Conversion Rate of the organic search channel was 6.8 per 10,000 sessions.</p>
<p>We can use the r code below to add a column representing the Ecommerce Conversion Rate per 10,000 sessions for my_data.</p>
<div class="sourceCode" id="cb129"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb129-1"><a href="statistical-analyses-of-a-single-variable.html#cb129-1" aria-hidden="true" tabindex="-1"></a>my_data<span class="sc">$</span>ECR <span class="ot">&lt;-</span> my_data<span class="sc">$</span><span class="st">`</span><span class="at">Ecommerce Conversion Rate</span><span class="st">`</span><span class="sc">*</span><span class="dv">10000</span></span></code></pre></div>
<p>Now, the new column has been added to my_data as illustrated in Table 3.5.</p>
<div class="sourceCode" id="cb130"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb130-1"><a href="statistical-analyses-of-a-single-variable.html#cb130-1" aria-hidden="true" tabindex="-1"></a>knitr<span class="sc">::</span><span class="fu">kable</span>(<span class="fu">head</span>(my_data[,<span class="dv">1</span><span class="sc">:</span><span class="dv">13</span>], <span class="dv">20</span>), <span class="at">digits =</span> <span class="dv">5</span>, <span class="at">booktabs =</span> <span class="cn">TRUE</span>,</span>
<span id="cb130-2"><a href="statistical-analyses-of-a-single-variable.html#cb130-2" aria-hidden="true" tabindex="-1"></a>  <span class="at">caption =</span> <span class="st">&#39;The First 20 Rows of the Google Analytics Sample Data&#39;</span></span>
<span id="cb130-3"><a href="statistical-analyses-of-a-single-variable.html#cb130-3" aria-hidden="true" tabindex="-1"></a>) <span class="sc">%&gt;%</span></span>
<span id="cb130-4"><a href="statistical-analyses-of-a-single-variable.html#cb130-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">kable_styling</span>(<span class="at">font_size =</span> <span class="fl">6.5</span>)</span></code></pre></div>
<table class="table" style="font-size: 6.5px; margin-left: auto; margin-right: auto;">
<caption style="font-size: initial !important;">
<span id="tab:unnamed-chunk-38">Table 3.5: </span>The First 20 Rows of the Google Analytics Sample Data
</caption>
<thead>
<tr>
<th style="text-align:left;">
Channel
</th>
<th style="text-align:left;">
Age
</th>
<th style="text-align:right;">
Users
</th>
<th style="text-align:right;">
New Users
</th>
<th style="text-align:right;">
Sessions
</th>
<th style="text-align:right;">
Bounce Rate
</th>
<th style="text-align:right;">
Pages / Session
</th>
<th style="text-align:right;">
Avg. Session Duration
</th>
<th style="text-align:right;">
Ecommerce Conversion Rate
</th>
<th style="text-align:right;">
Transactions
</th>
<th style="text-align:right;">
Revenue
</th>
<th style="text-align:right;">
Year
</th>
<th style="text-align:right;">
ECR
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
Direct
</td>
<td style="text-align:left;">
25-34
</td>
<td style="text-align:right;">
81822
</td>
<td style="text-align:right;">
76251
</td>
<td style="text-align:right;">
118241
</td>
<td style="text-align:right;">
0.42193
</td>
<td style="text-align:right;">
5.82467
</td>
<td style="text-align:right;">
227.6724
</td>
<td style="text-align:right;">
0.03649
</td>
<td style="text-align:right;">
4315
</td>
<td style="text-align:right;">
332771.829
</td>
<td style="text-align:right;">
2021
</td>
<td style="text-align:right;">
364.93264
</td>
</tr>
<tr>
<td style="text-align:left;">
Direct
</td>
<td style="text-align:left;">
18-24
</td>
<td style="text-align:right;">
65506
</td>
<td style="text-align:right;">
61565
</td>
<td style="text-align:right;">
88898
</td>
<td style="text-align:right;">
0.47178
</td>
<td style="text-align:right;">
4.98222
</td>
<td style="text-align:right;">
199.7854
</td>
<td style="text-align:right;">
0.02642
</td>
<td style="text-align:right;">
2349
</td>
<td style="text-align:right;">
198848.060
</td>
<td style="text-align:right;">
2021
</td>
<td style="text-align:right;">
264.23542
</td>
</tr>
<tr>
<td style="text-align:left;">
Direct
</td>
<td style="text-align:left;">
35-44
</td>
<td style="text-align:right;">
41947
</td>
<td style="text-align:right;">
38535
</td>
<td style="text-align:right;">
59313
</td>
<td style="text-align:right;">
0.42185
</td>
<td style="text-align:right;">
5.91531
</td>
<td style="text-align:right;">
229.8105
</td>
<td style="text-align:right;">
0.03842
</td>
<td style="text-align:right;">
2279
</td>
<td style="text-align:right;">
189792.736
</td>
<td style="text-align:right;">
2021
</td>
<td style="text-align:right;">
384.23280
</td>
</tr>
<tr>
<td style="text-align:left;">
Direct
</td>
<td style="text-align:left;">
45-54
</td>
<td style="text-align:right;">
26800
</td>
<td style="text-align:right;">
24967
</td>
<td style="text-align:right;">
37477
</td>
<td style="text-align:right;">
0.44659
</td>
<td style="text-align:right;">
5.47669
</td>
<td style="text-align:right;">
226.9229
</td>
<td style="text-align:right;">
0.03421
</td>
<td style="text-align:right;">
1282
</td>
<td style="text-align:right;">
109531.822
</td>
<td style="text-align:right;">
2021
</td>
<td style="text-align:right;">
342.07647
</td>
</tr>
<tr>
<td style="text-align:left;">
Direct
</td>
<td style="text-align:left;">
55-64
</td>
<td style="text-align:right;">
12981
</td>
<td style="text-align:right;">
12217
</td>
<td style="text-align:right;">
17703
</td>
<td style="text-align:right;">
0.46444
</td>
<td style="text-align:right;">
5.26922
</td>
<td style="text-align:right;">
213.1094
</td>
<td style="text-align:right;">
0.03474
</td>
<td style="text-align:right;">
615
</td>
<td style="text-align:right;">
54808.702
</td>
<td style="text-align:right;">
2021
</td>
<td style="text-align:right;">
347.39875
</td>
</tr>
<tr>
<td style="text-align:left;">
Direct
</td>
<td style="text-align:left;">
65+
</td>
<td style="text-align:right;">
9432
</td>
<td style="text-align:right;">
8849
</td>
<td style="text-align:right;">
12548
</td>
<td style="text-align:right;">
0.46788
</td>
<td style="text-align:right;">
5.23932
</td>
<td style="text-align:right;">
210.5902
</td>
<td style="text-align:right;">
0.02981
</td>
<td style="text-align:right;">
374
</td>
<td style="text-align:right;">
35609.855
</td>
<td style="text-align:right;">
2021
</td>
<td style="text-align:right;">
298.05547
</td>
</tr>
<tr>
<td style="text-align:left;">
Paid Search
</td>
<td style="text-align:left;">
18-24
</td>
<td style="text-align:right;">
2015
</td>
<td style="text-align:right;">
1766
</td>
<td style="text-align:right;">
2797
</td>
<td style="text-align:right;">
0.55703
</td>
<td style="text-align:right;">
4.71505
</td>
<td style="text-align:right;">
175.1087
</td>
<td style="text-align:right;">
0.02252
</td>
<td style="text-align:right;">
63
</td>
<td style="text-align:right;">
8423.719
</td>
<td style="text-align:right;">
2021
</td>
<td style="text-align:right;">
225.24133
</td>
</tr>
<tr>
<td style="text-align:left;">
Paid Search
</td>
<td style="text-align:left;">
35-44
</td>
<td style="text-align:right;">
1394
</td>
<td style="text-align:right;">
1216
</td>
<td style="text-align:right;">
1980
</td>
<td style="text-align:right;">
0.47525
</td>
<td style="text-align:right;">
5.20909
</td>
<td style="text-align:right;">
157.2596
</td>
<td style="text-align:right;">
0.03535
</td>
<td style="text-align:right;">
70
</td>
<td style="text-align:right;">
8175.394
</td>
<td style="text-align:right;">
2021
</td>
<td style="text-align:right;">
353.53535
</td>
</tr>
<tr>
<td style="text-align:left;">
Paid Search
</td>
<td style="text-align:left;">
25-34
</td>
<td style="text-align:right;">
2175
</td>
<td style="text-align:right;">
1829
</td>
<td style="text-align:right;">
3198
</td>
<td style="text-align:right;">
0.43809
</td>
<td style="text-align:right;">
5.88149
</td>
<td style="text-align:right;">
195.8474
</td>
<td style="text-align:right;">
0.03502
</td>
<td style="text-align:right;">
112
</td>
<td style="text-align:right;">
7576.795
</td>
<td style="text-align:right;">
2021
</td>
<td style="text-align:right;">
350.21889
</td>
</tr>
<tr>
<td style="text-align:left;">
Direct
</td>
<td style="text-align:left;">
25-34
</td>
<td style="text-align:right;">
30772
</td>
<td style="text-align:right;">
29628
</td>
<td style="text-align:right;">
40539
</td>
<td style="text-align:right;">
0.37803
</td>
<td style="text-align:right;">
5.78436
</td>
<td style="text-align:right;">
233.6450
</td>
<td style="text-align:right;">
0.00306
</td>
<td style="text-align:right;">
124
</td>
<td style="text-align:right;">
7240.313
</td>
<td style="text-align:right;">
2020
</td>
<td style="text-align:right;">
30.58783
</td>
</tr>
<tr>
<td style="text-align:left;">
Direct
</td>
<td style="text-align:left;">
18-24
</td>
<td style="text-align:right;">
17545
</td>
<td style="text-align:right;">
17024
</td>
<td style="text-align:right;">
21888
</td>
<td style="text-align:right;">
0.42708
</td>
<td style="text-align:right;">
5.07753
</td>
<td style="text-align:right;">
210.2462
</td>
<td style="text-align:right;">
0.00315
</td>
<td style="text-align:right;">
69
</td>
<td style="text-align:right;">
5325.412
</td>
<td style="text-align:right;">
2020
</td>
<td style="text-align:right;">
31.52412
</td>
</tr>
<tr>
<td style="text-align:left;">
Direct
</td>
<td style="text-align:left;">
45-54
</td>
<td style="text-align:right;">
8491
</td>
<td style="text-align:right;">
8126
</td>
<td style="text-align:right;">
11115
</td>
<td style="text-align:right;">
0.38570
</td>
<td style="text-align:right;">
5.73117
</td>
<td style="text-align:right;">
230.9463
</td>
<td style="text-align:right;">
0.00495
</td>
<td style="text-align:right;">
55
</td>
<td style="text-align:right;">
4173.602
</td>
<td style="text-align:right;">
2020
</td>
<td style="text-align:right;">
49.48268
</td>
</tr>
<tr>
<td style="text-align:left;">
Paid Search
</td>
<td style="text-align:left;">
45-54
</td>
<td style="text-align:right;">
1083
</td>
<td style="text-align:right;">
960
</td>
<td style="text-align:right;">
1387
</td>
<td style="text-align:right;">
0.56669
</td>
<td style="text-align:right;">
4.39726
</td>
<td style="text-align:right;">
138.6871
</td>
<td style="text-align:right;">
0.02307
</td>
<td style="text-align:right;">
32
</td>
<td style="text-align:right;">
4086.483
</td>
<td style="text-align:right;">
2021
</td>
<td style="text-align:right;">
230.71377
</td>
</tr>
<tr>
<td style="text-align:left;">
Direct
</td>
<td style="text-align:left;">
35-44
</td>
<td style="text-align:right;">
14088
</td>
<td style="text-align:right;">
13560
</td>
<td style="text-align:right;">
18461
</td>
<td style="text-align:right;">
0.38248
</td>
<td style="text-align:right;">
5.53648
</td>
<td style="text-align:right;">
226.3607
</td>
<td style="text-align:right;">
0.00444
</td>
<td style="text-align:right;">
82
</td>
<td style="text-align:right;">
3993.809
</td>
<td style="text-align:right;">
2020
</td>
<td style="text-align:right;">
44.41796
</td>
</tr>
<tr>
<td style="text-align:left;">
Organic Search
</td>
<td style="text-align:left;">
25-34
</td>
<td style="text-align:right;">
35978
</td>
<td style="text-align:right;">
32853
</td>
<td style="text-align:right;">
47132
</td>
<td style="text-align:right;">
0.51390
</td>
<td style="text-align:right;">
3.97070
</td>
<td style="text-align:right;">
164.3456
</td>
<td style="text-align:right;">
0.00068
</td>
<td style="text-align:right;">
32
</td>
<td style="text-align:right;">
1738.469
</td>
<td style="text-align:right;">
2020
</td>
<td style="text-align:right;">
6.78944
</td>
</tr>
<tr>
<td style="text-align:left;">
(Other)
</td>
<td style="text-align:left;">
35-44
</td>
<td style="text-align:right;">
284
</td>
<td style="text-align:right;">
174
</td>
<td style="text-align:right;">
523
</td>
<td style="text-align:right;">
0.24474
</td>
<td style="text-align:right;">
7.62524
</td>
<td style="text-align:right;">
278.2505
</td>
<td style="text-align:right;">
0.03824
</td>
<td style="text-align:right;">
20
</td>
<td style="text-align:right;">
1657.444
</td>
<td style="text-align:right;">
2021
</td>
<td style="text-align:right;">
382.40918
</td>
</tr>
<tr>
<td style="text-align:left;">
Direct
</td>
<td style="text-align:left;">
55-64
</td>
<td style="text-align:right;">
4466
</td>
<td style="text-align:right;">
4287
</td>
<td style="text-align:right;">
5862
</td>
<td style="text-align:right;">
0.40242
</td>
<td style="text-align:right;">
5.46571
</td>
<td style="text-align:right;">
232.1102
</td>
<td style="text-align:right;">
0.00409
</td>
<td style="text-align:right;">
24
</td>
<td style="text-align:right;">
1530.108
</td>
<td style="text-align:right;">
2020
</td>
<td style="text-align:right;">
40.94166
</td>
</tr>
<tr>
<td style="text-align:left;">
(Other)
</td>
<td style="text-align:left;">
25-34
</td>
<td style="text-align:right;">
3440
</td>
<td style="text-align:right;">
2370
</td>
<td style="text-align:right;">
4741
</td>
<td style="text-align:right;">
0.31533
</td>
<td style="text-align:right;">
5.90719
</td>
<td style="text-align:right;">
232.4685
</td>
<td style="text-align:right;">
0.00337
</td>
<td style="text-align:right;">
16
</td>
<td style="text-align:right;">
1472.471
</td>
<td style="text-align:right;">
2020
</td>
<td style="text-align:right;">
33.74815
</td>
</tr>
<tr>
<td style="text-align:left;">
(Other)
</td>
<td style="text-align:left;">
18-24
</td>
<td style="text-align:right;">
500
</td>
<td style="text-align:right;">
302
</td>
<td style="text-align:right;">
849
</td>
<td style="text-align:right;">
0.34982
</td>
<td style="text-align:right;">
5.61602
</td>
<td style="text-align:right;">
244.2697
</td>
<td style="text-align:right;">
0.03651
</td>
<td style="text-align:right;">
31
</td>
<td style="text-align:right;">
1395.053
</td>
<td style="text-align:right;">
2021
</td>
<td style="text-align:right;">
365.13545
</td>
</tr>
<tr>
<td style="text-align:left;">
Paid Search
</td>
<td style="text-align:left;">
55-64
</td>
<td style="text-align:right;">
804
</td>
<td style="text-align:right;">
748
</td>
<td style="text-align:right;">
1009
</td>
<td style="text-align:right;">
0.62537
</td>
<td style="text-align:right;">
3.59068
</td>
<td style="text-align:right;">
111.0684
</td>
<td style="text-align:right;">
0.01388
</td>
<td style="text-align:right;">
14
</td>
<td style="text-align:right;">
1315.551
</td>
<td style="text-align:right;">
2021
</td>
<td style="text-align:right;">
138.75124
</td>
</tr>
</tbody>
</table>
</div>
<div id="ratio" class="section level2 hasAnchor" number="3.7">
<h2><span class="header-section-number">3.7</span> Ratio<a href="statistical-analyses-of-a-single-variable.html#ratio" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Ratio compares the size of two numbers indicating how many times one number contains another. For example, let’s calculate the ratio of returning users and new users using the formula: <strong>Number of Old Users / Number of New Users</strong>. We first use the r code below to create a new column <strong>old user (users - new users)</strong>, then we use the <strong>group_by</strong> function to calculate the ratio fo returning users and new users for each channel.</p>
<div class="sourceCode" id="cb131"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb131-1"><a href="statistical-analyses-of-a-single-variable.html#cb131-1" aria-hidden="true" tabindex="-1"></a><span class="co">#creating a new colunme of old users</span></span>
<span id="cb131-2"><a href="statistical-analyses-of-a-single-variable.html#cb131-2" aria-hidden="true" tabindex="-1"></a>my_data<span class="sc">$</span>OldUsers <span class="ot">&lt;-</span> my_data<span class="sc">$</span>Users<span class="sc">-</span>my_data<span class="sc">$</span><span class="st">&#39;New Users&#39;</span></span>
<span id="cb131-3"><a href="statistical-analyses-of-a-single-variable.html#cb131-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb131-4"><a href="statistical-analyses-of-a-single-variable.html#cb131-4" aria-hidden="true" tabindex="-1"></a>userratio <span class="ot">&lt;-</span> my_data <span class="sc">%&gt;%</span> </span>
<span id="cb131-5"><a href="statistical-analyses-of-a-single-variable.html#cb131-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(Channel) <span class="sc">%&gt;%</span> </span>
<span id="cb131-6"><a href="statistical-analyses-of-a-single-variable.html#cb131-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">OldUsers =</span> <span class="fu">sum</span>(OldUsers), <span class="at">NewUsers =</span> <span class="fu">sum</span>(<span class="st">`</span><span class="at">New Users</span><span class="st">`</span>),<span class="at">Ratio =</span> <span class="fu">sum</span>(OldUsers)<span class="sc">/</span><span class="fu">sum</span>(<span class="st">`</span><span class="at">New Users</span><span class="st">`</span>))</span></code></pre></div>
<p>From Table 3.6, we can find that besides the un-defined channel, the referral channel has a relatively higher ratio of returning (old) users to new users, indicating a better retention rate.</p>
<div class="sourceCode" id="cb132"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb132-1"><a href="statistical-analyses-of-a-single-variable.html#cb132-1" aria-hidden="true" tabindex="-1"></a>knitr<span class="sc">::</span><span class="fu">kable</span>(</span>
<span id="cb132-2"><a href="statistical-analyses-of-a-single-variable.html#cb132-2" aria-hidden="true" tabindex="-1"></a>    <span class="fu">head</span>(<span class="fu">arrange</span>(userratio, <span class="fu">desc</span>(Ratio))), </span>
<span id="cb132-3"><a href="statistical-analyses-of-a-single-variable.html#cb132-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">booktabs =</span> <span class="cn">TRUE</span>,</span>
<span id="cb132-4"><a href="statistical-analyses-of-a-single-variable.html#cb132-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">caption =</span> <span class="st">&#39;The Ratio of Old Users and New Users for Each Channel&#39;</span></span>
<span id="cb132-5"><a href="statistical-analyses-of-a-single-variable.html#cb132-5" aria-hidden="true" tabindex="-1"></a>) <span class="sc">%&gt;%</span></span>
<span id="cb132-6"><a href="statistical-analyses-of-a-single-variable.html#cb132-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">kable_styling</span>(<span class="at">font_size =</span> <span class="dv">14</span>)</span></code></pre></div>
<table class="table" style="font-size: 14px; margin-left: auto; margin-right: auto;">
<caption style="font-size: initial !important;">
<span id="tab:unnamed-chunk-40">Table 3.6: </span>The Ratio of Old Users and New Users for Each Channel
</caption>
<thead>
<tr>
<th style="text-align:left;">
Channel
</th>
<th style="text-align:right;">
OldUsers
</th>
<th style="text-align:right;">
NewUsers
</th>
<th style="text-align:right;">
Ratio
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
(Other)
</td>
<td style="text-align:right;">
3383
</td>
<td style="text-align:right;">
7268
</td>
<td style="text-align:right;">
0.4654651
</td>
</tr>
<tr>
<td style="text-align:left;">
Referral
</td>
<td style="text-align:right;">
8101
</td>
<td style="text-align:right;">
23027
</td>
<td style="text-align:right;">
0.3518044
</td>
</tr>
<tr>
<td style="text-align:left;">
Paid Search
</td>
<td style="text-align:right;">
2116
</td>
<td style="text-align:right;">
11593
</td>
<td style="text-align:right;">
0.1825239
</td>
</tr>
<tr>
<td style="text-align:left;">
Affiliates
</td>
<td style="text-align:right;">
1002
</td>
<td style="text-align:right;">
8071
</td>
<td style="text-align:right;">
0.1241482
</td>
</tr>
<tr>
<td style="text-align:left;">
Organic Search
</td>
<td style="text-align:right;">
8428
</td>
<td style="text-align:right;">
81809
</td>
<td style="text-align:right;">
0.1030205
</td>
</tr>
<tr>
<td style="text-align:left;">
Display
</td>
<td style="text-align:right;">
524
</td>
<td style="text-align:right;">
7624
</td>
<td style="text-align:right;">
0.0687303
</td>
</tr>
</tbody>
</table>
</div>
<div id="central-tendency" class="section level2 hasAnchor" number="3.8">
<h2><span class="header-section-number">3.8</span> Central Tendency<a href="statistical-analyses-of-a-single-variable.html#central-tendency" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Besides using frequency analysis to summarize the distribution of a variable, we also can use the central tendency analysis to understand which attribute of a variable is most typical or representative of the variable distribution. Specifically, the central tendency analysis describes what the center of the data for a variable is. What do we mean by the center of the data? For many, the mean, median, and mode. Mean is the sum of all data points divided by the total number of observations. Median is the midpoint in data with an equal number of data points above and below. If the number of data points is even, then Median is the mean of the two midpoints. Mode is the data point that is most prevalent in the data set. It represents the most likely outcome in a data set.</p>
<p>Let’s first create a small dataset of test scores from 20 students.</p>
<div class="sourceCode" id="cb133"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb133-1"><a href="statistical-analyses-of-a-single-variable.html#cb133-1" aria-hidden="true" tabindex="-1"></a>StudentID <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">1</span><span class="sc">:</span><span class="dv">20</span>)</span>
<span id="cb133-2"><a href="statistical-analyses-of-a-single-variable.html#cb133-2" aria-hidden="true" tabindex="-1"></a>Score <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">40</span>,<span class="dv">50</span>,<span class="dv">50</span>,<span class="dv">60</span>,<span class="dv">60</span>,<span class="dv">60</span>,<span class="dv">60</span>,<span class="dv">60</span>,<span class="dv">70</span>,<span class="dv">70</span>,<span class="dv">70</span>,<span class="dv">80</span>,<span class="dv">80</span>,<span class="dv">80</span>,<span class="dv">80</span>,<span class="dv">90</span>,<span class="dv">90</span>,<span class="dv">90</span>,<span class="dv">90</span>,<span class="dv">100</span>)</span>
<span id="cb133-3"><a href="statistical-analyses-of-a-single-variable.html#cb133-3" aria-hidden="true" tabindex="-1"></a>TestData <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(StudentID, Score)</span>
<span id="cb133-4"><a href="statistical-analyses-of-a-single-variable.html#cb133-4" aria-hidden="true" tabindex="-1"></a>ScoreFrequency <span class="ot">&lt;-</span> <span class="fu">as.data.frame</span>(<span class="fu">table</span>(TestData<span class="sc">$</span>Score)) <span class="co"># Calculate the frequency of each score</span></span>
<span id="cb133-5"><a href="statistical-analyses-of-a-single-variable.html#cb133-5" aria-hidden="true" tabindex="-1"></a><span class="fu">colnames</span>(ScoreFrequency) <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">&quot;Score&quot;</span>,<span class="st">&quot;Frequency&quot;</span>)</span></code></pre></div>
<p>Table 3.7 demonstrates the frequency of each score.</p>
<div class="sourceCode" id="cb134"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb134-1"><a href="statistical-analyses-of-a-single-variable.html#cb134-1" aria-hidden="true" tabindex="-1"></a>knitr<span class="sc">::</span><span class="fu">kable</span>(</span>
<span id="cb134-2"><a href="statistical-analyses-of-a-single-variable.html#cb134-2" aria-hidden="true" tabindex="-1"></a>    <span class="fu">head</span>(<span class="fu">arrange</span>(ScoreFrequency)), </span>
<span id="cb134-3"><a href="statistical-analyses-of-a-single-variable.html#cb134-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">booktabs =</span> <span class="cn">TRUE</span>,</span>
<span id="cb134-4"><a href="statistical-analyses-of-a-single-variable.html#cb134-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">caption =</span> <span class="st">&#39;Frequency of Test Scores from 20 Students&#39;</span>, <span class="at">align =</span> <span class="st">&quot;l&quot;</span></span>
<span id="cb134-5"><a href="statistical-analyses-of-a-single-variable.html#cb134-5" aria-hidden="true" tabindex="-1"></a>) <span class="sc">%&gt;%</span></span>
<span id="cb134-6"><a href="statistical-analyses-of-a-single-variable.html#cb134-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">kable_styling</span>(<span class="at">font_size =</span> <span class="dv">16</span>)</span></code></pre></div>
<table class="table" style="font-size: 16px; margin-left: auto; margin-right: auto;">
<caption style="font-size: initial !important;">
<span id="tab:unnamed-chunk-42">Table 3.7: </span>Frequency of Test Scores from 20 Students
</caption>
<thead>
<tr>
<th style="text-align:left;">
Score
</th>
<th style="text-align:left;">
Frequency
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
40
</td>
<td style="text-align:left;">
1
</td>
</tr>
<tr>
<td style="text-align:left;">
50
</td>
<td style="text-align:left;">
2
</td>
</tr>
<tr>
<td style="text-align:left;">
60
</td>
<td style="text-align:left;">
5
</td>
</tr>
<tr>
<td style="text-align:left;">
70
</td>
<td style="text-align:left;">
3
</td>
</tr>
<tr>
<td style="text-align:left;">
80
</td>
<td style="text-align:left;">
4
</td>
</tr>
<tr>
<td style="text-align:left;">
90
</td>
<td style="text-align:left;">
4
</td>
</tr>
</tbody>
</table>
<p>The mean score is the sum of all scores divided by 20. The related formula is: <strong>(40x1 + 50x2 + 60x5 + 70x3 + 80x4 +90x4 + 100x1)/20 = 71.5</strong>, meaning that the average score among these 20 students is 71.5.</p>
<p>When it comes to identifying the median value, we want to sort all individuals from the lowest value to the highest value, and whoever in the middle gives us the median value. But the problem is, we have 20 students in this sample, which is an even number, meaning that there will be two individuals in the middle (Table 3.8: student number 10 and number 11). For situations like this, we take the mean of these two individuals’ values to compute the <strong>median: (70+70)/2 = 70</strong> (Table 2.8).</p>
<div class="sourceCode" id="cb135"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb135-1"><a href="statistical-analyses-of-a-single-variable.html#cb135-1" aria-hidden="true" tabindex="-1"></a>knitr<span class="sc">::</span><span class="fu">kable</span>(<span class="fu">head</span>(TestData, <span class="dv">20</span>), <span class="at">booktabs =</span> <span class="cn">TRUE</span>,</span>
<span id="cb135-2"><a href="statistical-analyses-of-a-single-variable.html#cb135-2" aria-hidden="true" tabindex="-1"></a>  <span class="at">caption =</span> <span class="st">&#39;A Small Dataset of Test Scores from 20 Students&#39;</span>, <span class="at">align =</span> <span class="st">&quot;l&quot;</span></span>
<span id="cb135-3"><a href="statistical-analyses-of-a-single-variable.html#cb135-3" aria-hidden="true" tabindex="-1"></a>) <span class="sc">%&gt;%</span></span>
<span id="cb135-4"><a href="statistical-analyses-of-a-single-variable.html#cb135-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">kable_styling</span>(<span class="at">font_size =</span> <span class="dv">16</span>)</span></code></pre></div>
<table class="table" style="font-size: 16px; margin-left: auto; margin-right: auto;">
<caption style="font-size: initial !important;">
<span id="tab:unnamed-chunk-43">Table 3.8: </span>A Small Dataset of Test Scores from 20 Students
</caption>
<thead>
<tr>
<th style="text-align:left;">
StudentID
</th>
<th style="text-align:left;">
Score
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
1
</td>
<td style="text-align:left;">
40
</td>
</tr>
<tr>
<td style="text-align:left;">
2
</td>
<td style="text-align:left;">
50
</td>
</tr>
<tr>
<td style="text-align:left;">
3
</td>
<td style="text-align:left;">
50
</td>
</tr>
<tr>
<td style="text-align:left;">
4
</td>
<td style="text-align:left;">
60
</td>
</tr>
<tr>
<td style="text-align:left;">
5
</td>
<td style="text-align:left;">
60
</td>
</tr>
<tr>
<td style="text-align:left;">
6
</td>
<td style="text-align:left;">
60
</td>
</tr>
<tr>
<td style="text-align:left;">
7
</td>
<td style="text-align:left;">
60
</td>
</tr>
<tr>
<td style="text-align:left;">
8
</td>
<td style="text-align:left;">
60
</td>
</tr>
<tr>
<td style="text-align:left;">
9
</td>
<td style="text-align:left;">
70
</td>
</tr>
<tr>
<td style="text-align:left;">
10
</td>
<td style="text-align:left;">
70
</td>
</tr>
<tr>
<td style="text-align:left;">
11
</td>
<td style="text-align:left;">
70
</td>
</tr>
<tr>
<td style="text-align:left;">
12
</td>
<td style="text-align:left;">
80
</td>
</tr>
<tr>
<td style="text-align:left;">
13
</td>
<td style="text-align:left;">
80
</td>
</tr>
<tr>
<td style="text-align:left;">
14
</td>
<td style="text-align:left;">
80
</td>
</tr>
<tr>
<td style="text-align:left;">
15
</td>
<td style="text-align:left;">
80
</td>
</tr>
<tr>
<td style="text-align:left;">
16
</td>
<td style="text-align:left;">
90
</td>
</tr>
<tr>
<td style="text-align:left;">
17
</td>
<td style="text-align:left;">
90
</td>
</tr>
<tr>
<td style="text-align:left;">
18
</td>
<td style="text-align:left;">
90
</td>
</tr>
<tr>
<td style="text-align:left;">
19
</td>
<td style="text-align:left;">
90
</td>
</tr>
<tr>
<td style="text-align:left;">
20
</td>
<td style="text-align:left;">
100
</td>
</tr>
</tbody>
</table>
<p>We can easily identify the most frequent test score by looking into the score distribution visualization.</p>
<div class="sourceCode" id="cb136"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb136-1"><a href="statistical-analyses-of-a-single-variable.html#cb136-1" aria-hidden="true" tabindex="-1"></a><span class="co"># You will need install ggplot2 package</span></span>
<span id="cb136-2"><a href="statistical-analyses-of-a-single-variable.html#cb136-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb136-3"><a href="statistical-analyses-of-a-single-variable.html#cb136-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb136-4"><a href="statistical-analyses-of-a-single-variable.html#cb136-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Barplot</span></span>
<span id="cb136-5"><a href="statistical-analyses-of-a-single-variable.html#cb136-5" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(ScoreFrequency, <span class="fu">aes</span>(<span class="at">x=</span>Score, <span class="at">y=</span>Frequency)) <span class="sc">+</span> </span>
<span id="cb136-6"><a href="statistical-analyses-of-a-single-variable.html#cb136-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_bar</span>(<span class="at">stat =</span> <span class="st">&quot;identity&quot;</span>)</span></code></pre></div>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:unnamed-chunk-44"></span>
<img src="bookdownproj_files/figure-html/unnamed-chunk-44-1.png" alt="Distribution of Test Scores from 20 Students" width="672" />
<p class="caption">
Figure 3.1: Distribution of Test Scores from 20 Students
</p>
</div>
<p>Since 60 is the most frequent data point, it is the mode of the dataset. When we do the central tendency analysis, we also need to consider the data types. While interval and ratio data have a median, mode, and mean, the nominal data has only a mode. Furthermore, when the data distribution is symmetrical, such as your data is normally distributed, the mean is the best measure of central tendency. But, when the dataset has a strongly skewed distribution, the best indicator of central tendency is the median or mode, with the median usually preferred.</p>
<p>Now we can use the code below to get the mean, median, and mode for the number of Users and New Users, number of Sessions, E-commerce Conversion Rates, Transactions, and Revenues for the Google analytics data of the Google Merchandise Store.</p>
<div class="sourceCode" id="cb137"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb137-1"><a href="statistical-analyses-of-a-single-variable.html#cb137-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Calculate mean for each col</span></span>
<span id="cb137-2"><a href="statistical-analyses-of-a-single-variable.html#cb137-2" aria-hidden="true" tabindex="-1"></a>mean_report <span class="ot">&lt;-</span> my_data <span class="sc">%&gt;%</span> </span>
<span id="cb137-3"><a href="statistical-analyses-of-a-single-variable.html#cb137-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise_if</span>(is.numeric, mean)</span>
<span id="cb137-4"><a href="statistical-analyses-of-a-single-variable.html#cb137-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb137-5"><a href="statistical-analyses-of-a-single-variable.html#cb137-5" aria-hidden="true" tabindex="-1"></a><span class="co">#Calculate median for each col</span></span>
<span id="cb137-6"><a href="statistical-analyses-of-a-single-variable.html#cb137-6" aria-hidden="true" tabindex="-1"></a>median_report <span class="ot">&lt;-</span> my_data <span class="sc">%&gt;%</span> </span>
<span id="cb137-7"><a href="statistical-analyses-of-a-single-variable.html#cb137-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise_if</span>(is.numeric, median)</span>
<span id="cb137-8"><a href="statistical-analyses-of-a-single-variable.html#cb137-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb137-9"><a href="statistical-analyses-of-a-single-variable.html#cb137-9" aria-hidden="true" tabindex="-1"></a><span class="co">#Create the mode function</span></span>
<span id="cb137-10"><a href="statistical-analyses-of-a-single-variable.html#cb137-10" aria-hidden="true" tabindex="-1"></a>getmode <span class="ot">&lt;-</span> <span class="cf">function</span>(v) {</span>
<span id="cb137-11"><a href="statistical-analyses-of-a-single-variable.html#cb137-11" aria-hidden="true" tabindex="-1"></a>  uniqv <span class="ot">&lt;-</span> <span class="fu">unique</span>(v)</span>
<span id="cb137-12"><a href="statistical-analyses-of-a-single-variable.html#cb137-12" aria-hidden="true" tabindex="-1"></a>  uniqv[<span class="fu">which.max</span>(<span class="fu">tabulate</span>(<span class="fu">match</span>(v, uniqv)))]</span>
<span id="cb137-13"><a href="statistical-analyses-of-a-single-variable.html#cb137-13" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb137-14"><a href="statistical-analyses-of-a-single-variable.html#cb137-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb137-15"><a href="statistical-analyses-of-a-single-variable.html#cb137-15" aria-hidden="true" tabindex="-1"></a><span class="co">#Calculate mode for each col</span></span>
<span id="cb137-16"><a href="statistical-analyses-of-a-single-variable.html#cb137-16" aria-hidden="true" tabindex="-1"></a>mode_report <span class="ot">&lt;-</span> my_data <span class="sc">%&gt;%</span> </span>
<span id="cb137-17"><a href="statistical-analyses-of-a-single-variable.html#cb137-17" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise_if</span>(is.numeric, getmode)</span>
<span id="cb137-18"><a href="statistical-analyses-of-a-single-variable.html#cb137-18" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb137-19"><a href="statistical-analyses-of-a-single-variable.html#cb137-19" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb137-20"><a href="statistical-analyses-of-a-single-variable.html#cb137-20" aria-hidden="true" tabindex="-1"></a><span class="co">#combine the reports</span></span>
<span id="cb137-21"><a href="statistical-analyses-of-a-single-variable.html#cb137-21" aria-hidden="true" tabindex="-1"></a>centerreport <span class="ot">&lt;-</span> <span class="fu">as.data.frame</span>(<span class="fu">rbind</span>(mean_report, median_report, mode_report))</span>
<span id="cb137-22"><a href="statistical-analyses-of-a-single-variable.html#cb137-22" aria-hidden="true" tabindex="-1"></a><span class="fu">rownames</span>(centerreport) <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">&quot;Mean&quot;</span>,<span class="st">&quot;Median&quot;</span>,<span class="st">&quot;Mode&quot;</span>)</span>
<span id="cb137-23"><a href="statistical-analyses-of-a-single-variable.html#cb137-23" aria-hidden="true" tabindex="-1"></a>centerreport <span class="ot">&lt;-</span> centerreport[, <span class="sc">-</span><span class="dv">10</span>]</span></code></pre></div>
<div class="sourceCode" id="cb138"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb138-1"><a href="statistical-analyses-of-a-single-variable.html#cb138-1" aria-hidden="true" tabindex="-1"></a>knitr<span class="sc">::</span><span class="fu">kable</span>(</span>
<span id="cb138-2"><a href="statistical-analyses-of-a-single-variable.html#cb138-2" aria-hidden="true" tabindex="-1"></a>    <span class="fu">arrange</span>(centerreport), </span>
<span id="cb138-3"><a href="statistical-analyses-of-a-single-variable.html#cb138-3" aria-hidden="true" tabindex="-1"></a>    <span class="at">digits =</span> <span class="dv">0</span>,</span>
<span id="cb138-4"><a href="statistical-analyses-of-a-single-variable.html#cb138-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">booktabs =</span> <span class="cn">TRUE</span>,</span>
<span id="cb138-5"><a href="statistical-analyses-of-a-single-variable.html#cb138-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">caption =</span> <span class="st">&#39;Descriptive Statistics-mean,median,mode&#39;</span>, <span class="at">align =</span> <span class="st">&quot;l&quot;</span></span>
<span id="cb138-6"><a href="statistical-analyses-of-a-single-variable.html#cb138-6" aria-hidden="true" tabindex="-1"></a>) <span class="sc">%&gt;%</span></span>
<span id="cb138-7"><a href="statistical-analyses-of-a-single-variable.html#cb138-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">kable_styling</span>(<span class="at">font_size =</span> <span class="dv">9</span>)</span></code></pre></div>
<table class="table" style="font-size: 9px; margin-left: auto; margin-right: auto;">
<caption style="font-size: initial !important;">
<span id="tab:unnamed-chunk-46">Table 3.9: </span>Descriptive Statistics-mean,median,mode
</caption>
<thead>
<tr>
<th style="text-align:left;">
</th>
<th style="text-align:left;">
Users
</th>
<th style="text-align:left;">
New Users
</th>
<th style="text-align:left;">
Sessions
</th>
<th style="text-align:left;">
Bounce Rate
</th>
<th style="text-align:left;">
Pages / Session
</th>
<th style="text-align:left;">
Avg. Session Duration
</th>
<th style="text-align:left;">
Ecommerce Conversion Rate
</th>
<th style="text-align:left;">
Transactions
</th>
<th style="text-align:left;">
Revenue
</th>
<th style="text-align:left;">
ECR
</th>
<th style="text-align:left;">
OldUsers
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
Mean
</td>
<td style="text-align:left;">
5661
</td>
<td style="text-align:left;">
5163
</td>
<td style="text-align:left;">
7708
</td>
<td style="text-align:left;">
0
</td>
<td style="text-align:left;">
5
</td>
<td style="text-align:left;">
188
</td>
<td style="text-align:left;">
0
</td>
<td style="text-align:left;">
142
</td>
<td style="text-align:left;">
11539
</td>
<td style="text-align:left;">
114
</td>
<td style="text-align:left;">
499
</td>
</tr>
<tr>
<td style="text-align:left;">
Median
</td>
<td style="text-align:left;">
940
</td>
<td style="text-align:left;">
768
</td>
<td style="text-align:left;">
1162
</td>
<td style="text-align:left;">
0
</td>
<td style="text-align:left;">
5
</td>
<td style="text-align:left;">
194
</td>
<td style="text-align:left;">
0
</td>
<td style="text-align:left;">
3
</td>
<td style="text-align:left;">
131
</td>
<td style="text-align:left;">
22
</td>
<td style="text-align:left;">
116
</td>
</tr>
<tr>
<td style="text-align:left;">
Mode
</td>
<td style="text-align:left;">
22
</td>
<td style="text-align:left;">
0
</td>
<td style="text-align:left;">
118241
</td>
<td style="text-align:left;">
0
</td>
<td style="text-align:left;">
6
</td>
<td style="text-align:left;">
228
</td>
<td style="text-align:left;">
0
</td>
<td style="text-align:left;">
0
</td>
<td style="text-align:left;">
0
</td>
<td style="text-align:left;">
0
</td>
<td style="text-align:left;">
3412
</td>
</tr>
</tbody>
</table>
<p>It is interesting to find the huge discrepancies between different central tendency measurements. This also indicates reporting results of different central tendency analyses can provide a more comprehensive understanding of the data distribution. For example, the mean value of Users (5661) is much higher than the median (940) and mode (22), indicating a skewed data distribution due to the existence of some large-value outliers.</p>
<p><strong>Weighted Mean</strong> is a special mean where some data points contribute more than others. To calculate the weighted mean, we need to consider the weight for each data point. For example, we can calculate the weighted mean of the E-commerce Conversion Rate by taking the number of users as weight. The more users each data point has, the larger weight for its E-commerce Conversion Rate (ECR). In R, we can use the function of <strong>weighted.mean</strong> as below to get the weighted mean of the ECR of the Google Store:</p>
<div class="sourceCode" id="cb139"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb139-1"><a href="statistical-analyses-of-a-single-variable.html#cb139-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Calculated the weighted mean for ECR</span></span>
<span id="cb139-2"><a href="statistical-analyses-of-a-single-variable.html#cb139-2" aria-hidden="true" tabindex="-1"></a><span class="fu">weighted.mean</span>(my_data<span class="sc">$</span><span class="st">`</span><span class="at">Ecommerce Conversion Rate</span><span class="st">`</span>, my_data<span class="sc">$</span>Users)</span></code></pre></div>
<pre><code>## [1] 0.01783514</code></pre>
<p>When taking the number of users into consideration, the weighted mean of the E-commerce Conversation Rate is almost 18 per 10,000 sessions, which is a bit higher than the normal mean, 11 per 10,000 sessions (Table above). This also indicates that the data points with high E-commerce Conversion Rates had more users than those with low rates.</p>
</div>
<div id="data-variation" class="section level2 hasAnchor" number="3.9">
<h2><span class="header-section-number">3.9</span> Data Variation<a href="statistical-analyses-of-a-single-variable.html#data-variation" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>If two data sets have the same center points, does that mean they
have the same data distribution? Let’s look at two small datasets:</p>
<div class="sourceCode" id="cb141"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb141-1"><a href="statistical-analyses-of-a-single-variable.html#cb141-1" aria-hidden="true" tabindex="-1"></a>Score1 <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="fu">c</span>(<span class="dv">110</span>, <span class="dv">90</span>,<span class="dv">70</span>,<span class="dv">50</span>,<span class="dv">30</span>))</span>
<span id="cb141-2"><a href="statistical-analyses-of-a-single-variable.html#cb141-2" aria-hidden="true" tabindex="-1"></a>Score2 <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="fu">c</span>(<span class="dv">75</span>, <span class="dv">70</span>,<span class="dv">70</span>,<span class="dv">70</span>,<span class="dv">65</span>))</span>
<span id="cb141-3"><a href="statistical-analyses-of-a-single-variable.html#cb141-3" aria-hidden="true" tabindex="-1"></a><span class="fu">colnames</span>(Score1) <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">&quot;Score1&quot;</span>)</span>
<span id="cb141-4"><a href="statistical-analyses-of-a-single-variable.html#cb141-4" aria-hidden="true" tabindex="-1"></a><span class="fu">colnames</span>(Score2) <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">&quot;Score2&quot;</span>)</span></code></pre></div>
<div class="sourceCode" id="cb142"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb142-1"><a href="statistical-analyses-of-a-single-variable.html#cb142-1" aria-hidden="true" tabindex="-1"></a>knitr<span class="sc">::</span><span class="fu">kable</span>(</span>
<span id="cb142-2"><a href="statistical-analyses-of-a-single-variable.html#cb142-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">list</span>(</span>
<span id="cb142-3"><a href="statistical-analyses-of-a-single-variable.html#cb142-3" aria-hidden="true" tabindex="-1"></a>    <span class="fu">head</span>(<span class="fu">arrange</span>(Score1, <span class="fu">desc</span>(Score1))), </span>
<span id="cb142-4"><a href="statistical-analyses-of-a-single-variable.html#cb142-4" aria-hidden="true" tabindex="-1"></a>    <span class="fu">head</span>(<span class="fu">arrange</span>(Score2, <span class="fu">desc</span>(Score2)))), </span>
<span id="cb142-5"><a href="statistical-analyses-of-a-single-variable.html#cb142-5" aria-hidden="true" tabindex="-1"></a>  <span class="at">booktabs =</span> <span class="cn">TRUE</span>,</span>
<span id="cb142-6"><a href="statistical-analyses-of-a-single-variable.html#cb142-6" aria-hidden="true" tabindex="-1"></a>  <span class="at">caption =</span> <span class="st">&#39;Two Small Data Sets with the Same Mean and Median&#39;</span></span>
<span id="cb142-7"><a href="statistical-analyses-of-a-single-variable.html#cb142-7" aria-hidden="true" tabindex="-1"></a>) <span class="sc">%&gt;%</span></span>
<span id="cb142-8"><a href="statistical-analyses-of-a-single-variable.html#cb142-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">kable_styling</span>(<span class="at">font_size =</span> <span class="dv">14</span>)</span></code></pre></div>
<table class="kable_wrapper table" style="font-size: 14px; margin-left: auto; margin-right: auto;">
<caption style="font-size: initial !important;">
<span id="tab:unnamed-chunk-49">Table 3.10: </span>Two Small Data Sets with the Same Mean and Median
</caption>
<tbody>
<tr>
<td>
<table>
<thead>
<tr>
<th style="text-align:right;">
Score1
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:right;">
110
</td>
</tr>
<tr>
<td style="text-align:right;">
90
</td>
</tr>
<tr>
<td style="text-align:right;">
70
</td>
</tr>
<tr>
<td style="text-align:right;">
50
</td>
</tr>
<tr>
<td style="text-align:right;">
30
</td>
</tr>
</tbody>
</table>
</td>
<td>
<table>
<thead>
<tr>
<th style="text-align:right;">
Score2
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:right;">
75
</td>
</tr>
<tr>
<td style="text-align:right;">
70
</td>
</tr>
<tr>
<td style="text-align:right;">
70
</td>
</tr>
<tr>
<td style="text-align:right;">
70
</td>
</tr>
<tr>
<td style="text-align:right;">
65
</td>
</tr>
</tbody>
</table>
</td>
</tr>
</tbody>
</table>
<p>Although they have the same mean (70) and median (70), the detailed data distributions vary significantly in a way that indicates the data in data set 1 were more spread out. This indicates that the mere central tendency measures cannot 100% accurately represent distribution. While the central tendency is the key to data description and prediction, variation is used to evaluate the quality of central tendency measures, and it plays an essential role in explaining statistical contribution.</p>
<p><strong>Variation Ratio</strong> reflects the proportion of cases that are not in the mode category. For example, from Table 3.9, the mode for Session is 3787. But this mode contains only two cases. Since the number of observations is 96, The variation ratio for Session is: (96-2)/96 = .98 or 98%, indicating the mode of 3787 is not a very representative indicator of sessions. To the contrary, for the variable of Transaction, the mode was 0 with 53 data points taking this value. The variation ratio of transaction is: (96-53)/96 = .45 or 45%, indicating “0” demonstrated relatively strong representativeness of transaction. This variation ratio also reflects the need for improvements of conversions for a variety of channels for the Google Merchandise Store.</p>
<p><strong>Range</strong> is the difference between the highest and lowest scores of a distribution. In our dataset, the range in class sizes is 237-17=220.</p>
<p><strong>Inter-ranges</strong> drops off a specified highest and lowest percentage of data points and then calculates the range of the remaining data points. The most popular inter-ranges are <em>inter-decile range</em>, <em>inter-quintile range</em>, and <em>inter-quartile range</em>, which drop off the highest and the lowest 10%, 20%, and 25% of the data points, respectively, and reflect the range of the remaining data points.</p>
<p>Table 3.11 lists the <strong>range</strong> and <strong>Inter-quartile range (IQR)</strong> for the number of users and new users, number of sessions, e-commerce conversion rate, transaction, and revenue for the Google analytics dataset.</p>
<div class="sourceCode" id="cb143"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb143-1"><a href="statistical-analyses-of-a-single-variable.html#cb143-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Calculate range for each col</span></span>
<span id="cb143-2"><a href="statistical-analyses-of-a-single-variable.html#cb143-2" aria-hidden="true" tabindex="-1"></a>range_report <span class="ot">&lt;-</span> my_data <span class="sc">%&gt;%</span> </span>
<span id="cb143-3"><a href="statistical-analyses-of-a-single-variable.html#cb143-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise_if</span>(is.numeric, range)</span>
<span id="cb143-4"><a href="statistical-analyses-of-a-single-variable.html#cb143-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb143-5"><a href="statistical-analyses-of-a-single-variable.html#cb143-5" aria-hidden="true" tabindex="-1"></a><span class="co">#Calculate Inter quartile range (IQR) for each col</span></span>
<span id="cb143-6"><a href="statistical-analyses-of-a-single-variable.html#cb143-6" aria-hidden="true" tabindex="-1"></a>range_report_interquartile <span class="ot">&lt;-</span> my_data <span class="sc">%&gt;%</span> </span>
<span id="cb143-7"><a href="statistical-analyses-of-a-single-variable.html#cb143-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise_if</span>(is.numeric, IQR)</span>
<span id="cb143-8"><a href="statistical-analyses-of-a-single-variable.html#cb143-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb143-9"><a href="statistical-analyses-of-a-single-variable.html#cb143-9" aria-hidden="true" tabindex="-1"></a><span class="co">#aggreate center report with range and IQR report</span></span>
<span id="cb143-10"><a href="statistical-analyses-of-a-single-variable.html#cb143-10" aria-hidden="true" tabindex="-1"></a>stats_report <span class="ot">&lt;-</span> <span class="fu">bind_rows</span>(centerreport,range_report, range_report_interquartile)</span>
<span id="cb143-11"><a href="statistical-analyses-of-a-single-variable.html#cb143-11" aria-hidden="true" tabindex="-1"></a><span class="fu">rownames</span>(stats_report) <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">&quot;mean&quot;</span>,<span class="st">&quot;median&quot;</span>,<span class="st">&quot;mode&quot;</span>,<span class="st">&quot;min&quot;</span>,<span class="st">&quot;max&quot;</span>,<span class="st">&quot;IQR&quot;</span>)</span>
<span id="cb143-12"><a href="statistical-analyses-of-a-single-variable.html#cb143-12" aria-hidden="true" tabindex="-1"></a>stats_report <span class="ot">&lt;-</span> stats_report[, <span class="sc">-</span><span class="dv">12</span>]</span></code></pre></div>
<div class="sourceCode" id="cb144"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb144-1"><a href="statistical-analyses-of-a-single-variable.html#cb144-1" aria-hidden="true" tabindex="-1"></a>knitr<span class="sc">::</span><span class="fu">kable</span>(</span>
<span id="cb144-2"><a href="statistical-analyses-of-a-single-variable.html#cb144-2" aria-hidden="true" tabindex="-1"></a>    <span class="fu">arrange</span>(stats_report), </span>
<span id="cb144-3"><a href="statistical-analyses-of-a-single-variable.html#cb144-3" aria-hidden="true" tabindex="-1"></a>    <span class="at">digits =</span> <span class="dv">0</span>,</span>
<span id="cb144-4"><a href="statistical-analyses-of-a-single-variable.html#cb144-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">booktabs =</span> <span class="cn">TRUE</span>,</span>
<span id="cb144-5"><a href="statistical-analyses-of-a-single-variable.html#cb144-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">caption =</span> <span class="st">&#39;Descriptive Statistics&#39;</span>, <span class="at">align =</span> <span class="st">&quot;l&quot;</span></span>
<span id="cb144-6"><a href="statistical-analyses-of-a-single-variable.html#cb144-6" aria-hidden="true" tabindex="-1"></a>) <span class="sc">%&gt;%</span></span>
<span id="cb144-7"><a href="statistical-analyses-of-a-single-variable.html#cb144-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">kable_styling</span>(<span class="at">font_size =</span> <span class="dv">9</span>)</span></code></pre></div>
<table class="table" style="font-size: 9px; margin-left: auto; margin-right: auto;">
<caption style="font-size: initial !important;">
<span id="tab:unnamed-chunk-51">Table 3.11: </span>Descriptive Statistics
</caption>
<thead>
<tr>
<th style="text-align:left;">
</th>
<th style="text-align:left;">
Users
</th>
<th style="text-align:left;">
New Users
</th>
<th style="text-align:left;">
Sessions
</th>
<th style="text-align:left;">
Bounce Rate
</th>
<th style="text-align:left;">
Pages / Session
</th>
<th style="text-align:left;">
Avg. Session Duration
</th>
<th style="text-align:left;">
Ecommerce Conversion Rate
</th>
<th style="text-align:left;">
Transactions
</th>
<th style="text-align:left;">
Revenue
</th>
<th style="text-align:left;">
ECR
</th>
<th style="text-align:left;">
OldUsers
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
mean
</td>
<td style="text-align:left;">
5661
</td>
<td style="text-align:left;">
5163
</td>
<td style="text-align:left;">
7708
</td>
<td style="text-align:left;">
0
</td>
<td style="text-align:left;">
5
</td>
<td style="text-align:left;">
188
</td>
<td style="text-align:left;">
0
</td>
<td style="text-align:left;">
142
</td>
<td style="text-align:left;">
11539
</td>
<td style="text-align:left;">
114
</td>
<td style="text-align:left;">
499
</td>
</tr>
<tr>
<td style="text-align:left;">
median
</td>
<td style="text-align:left;">
940
</td>
<td style="text-align:left;">
768
</td>
<td style="text-align:left;">
1162
</td>
<td style="text-align:left;">
0
</td>
<td style="text-align:left;">
5
</td>
<td style="text-align:left;">
194
</td>
<td style="text-align:left;">
0
</td>
<td style="text-align:left;">
3
</td>
<td style="text-align:left;">
131
</td>
<td style="text-align:left;">
22
</td>
<td style="text-align:left;">
116
</td>
</tr>
<tr>
<td style="text-align:left;">
mode
</td>
<td style="text-align:left;">
22
</td>
<td style="text-align:left;">
0
</td>
<td style="text-align:left;">
118241
</td>
<td style="text-align:left;">
0
</td>
<td style="text-align:left;">
6
</td>
<td style="text-align:left;">
228
</td>
<td style="text-align:left;">
0
</td>
<td style="text-align:left;">
0
</td>
<td style="text-align:left;">
0
</td>
<td style="text-align:left;">
0
</td>
<td style="text-align:left;">
3412
</td>
</tr>
<tr>
<td style="text-align:left;">
min
</td>
<td style="text-align:left;">
22
</td>
<td style="text-align:left;">
0
</td>
<td style="text-align:left;">
31
</td>
<td style="text-align:left;">
0
</td>
<td style="text-align:left;">
2
</td>
<td style="text-align:left;">
13
</td>
<td style="text-align:left;">
0
</td>
<td style="text-align:left;">
0
</td>
<td style="text-align:left;">
0
</td>
<td style="text-align:left;">
0
</td>
<td style="text-align:left;">
2
</td>
</tr>
<tr>
<td style="text-align:left;">
max
</td>
<td style="text-align:left;">
81822
</td>
<td style="text-align:left;">
76251
</td>
<td style="text-align:left;">
118241
</td>
<td style="text-align:left;">
1
</td>
<td style="text-align:left;">
13
</td>
<td style="text-align:left;">
583
</td>
<td style="text-align:left;">
0
</td>
<td style="text-align:left;">
4315
</td>
<td style="text-align:left;">
332772
</td>
<td style="text-align:left;">
1250
</td>
<td style="text-align:left;">
5571
</td>
</tr>
<tr>
<td style="text-align:left;">
IQR
</td>
<td style="text-align:left;">
2729
</td>
<td style="text-align:left;">
2262
</td>
<td style="text-align:left;">
3787
</td>
<td style="text-align:left;">
0
</td>
<td style="text-align:left;">
2
</td>
<td style="text-align:left;">
130
</td>
<td style="text-align:left;">
0
</td>
<td style="text-align:left;">
18
</td>
<td style="text-align:left;">
1149
</td>
<td style="text-align:left;">
150
</td>
<td style="text-align:left;">
364
</td>
</tr>
</tbody>
</table>
<p><strong>IQR</strong> is important for finding the <strong>outlier</strong> of an abnormal distance from other values in a data set. We use the quartile to divide observations into four intervals with an equal number of data points: the first quartile includes the lowest 25% of data points; the second quartile covers data points between 25.1% and 50%, which corresponds to the median; the third quartile includes data points above the median between 50.1% and 75%; the fourth quartile has the highest 25% of numbers.</p>
<p>All data points that are above q0.75+1.5×IQR or below q0.25-1.5×IQR are considered as potential outliers. Here, q0.25 and q0.75 refers to the first and third quartile, respectively.</p>
<p>For data from digital and social media, outliers represent important opportunities for improving audience conversion and engagement.Let take a look at how to find outlier using code.</p>
<div class="sourceCode" id="cb145"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb145-1"><a href="statistical-analyses-of-a-single-variable.html#cb145-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Histogram: a simple way to detect outliers is to draw a histogram of the data.</span></span>
<span id="cb145-2"><a href="statistical-analyses-of-a-single-variable.html#cb145-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb145-3"><a href="statistical-analyses-of-a-single-variable.html#cb145-3" aria-hidden="true" tabindex="-1"></a><span class="co">#using ggplot2(https://www.colorbook.io/hexcolors/view/0C4C8A)</span></span>
<span id="cb145-4"><a href="statistical-analyses-of-a-single-variable.html#cb145-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb145-5"><a href="statistical-analyses-of-a-single-variable.html#cb145-5" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(my_data) <span class="sc">+</span></span>
<span id="cb145-6"><a href="statistical-analyses-of-a-single-variable.html#cb145-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">aes</span>(<span class="at">x =</span> Transactions) <span class="sc">+</span></span>
<span id="cb145-7"><a href="statistical-analyses-of-a-single-variable.html#cb145-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_histogram</span>(<span class="at">binwidth =</span> <span class="dv">2000</span>, <span class="at">fill =</span> <span class="st">&quot;#8A1537&quot;</span>) <span class="sc">+</span></span>
<span id="cb145-8"><a href="statistical-analyses-of-a-single-variable.html#cb145-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span></code></pre></div>
<p><img src="bookdownproj_files/figure-html/unnamed-chunk-52-1.png" width="672" /></p>
<div class="sourceCode" id="cb146"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb146-1"><a href="statistical-analyses-of-a-single-variable.html#cb146-1" aria-hidden="true" tabindex="-1"></a><span class="co">#TRY MORE THEME:https://ggplot2.tidyverse.org/reference/ggtheme.html</span></span></code></pre></div>
<div class="sourceCode" id="cb147"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb147-1"><a href="statistical-analyses-of-a-single-variable.html#cb147-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Boxplot: in addition to histograms, boxplots are also useful to detect potential outliers.</span></span>
<span id="cb147-2"><a href="statistical-analyses-of-a-single-variable.html#cb147-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb147-3"><a href="statistical-analyses-of-a-single-variable.html#cb147-3" aria-hidden="true" tabindex="-1"></a><span class="fu">boxplot</span>(my_data<span class="sc">$</span>Transactions,</span>
<span id="cb147-4"><a href="statistical-analyses-of-a-single-variable.html#cb147-4" aria-hidden="true" tabindex="-1"></a>          <span class="at">ylab =</span> <span class="st">&quot;Transactions&quot;</span>)</span></code></pre></div>
<p><img src="bookdownproj_files/figure-html/unnamed-chunk-53-1.png" width="672" /></p>
<div class="sourceCode" id="cb148"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb148-1"><a href="statistical-analyses-of-a-single-variable.html#cb148-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Define Outlier</span></span>
<span id="cb148-2"><a href="statistical-analyses-of-a-single-variable.html#cb148-2" aria-hidden="true" tabindex="-1"></a>find_outlier <span class="ot">&lt;-</span> <span class="cf">function</span>(x) {</span>
<span id="cb148-3"><a href="statistical-analyses-of-a-single-variable.html#cb148-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">return</span>(x <span class="sc">&lt;</span> <span class="fu">quantile</span>(x, .<span class="dv">25</span>) <span class="sc">-</span> <span class="fl">1.5</span><span class="sc">*</span><span class="fu">IQR</span>(x) <span class="sc">|</span> x <span class="sc">&gt;</span> <span class="fu">quantile</span>(x, .<span class="dv">75</span>) <span class="sc">+</span> <span class="fl">1.5</span><span class="sc">*</span><span class="fu">IQR</span>(x))</span>
<span id="cb148-4"><a href="statistical-analyses-of-a-single-variable.html#cb148-4" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb148-5"><a href="statistical-analyses-of-a-single-variable.html#cb148-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb148-6"><a href="statistical-analyses-of-a-single-variable.html#cb148-6" aria-hidden="true" tabindex="-1"></a><span class="co">#add new column to data frame that indicates if each observation is an outlier</span></span>
<span id="cb148-7"><a href="statistical-analyses-of-a-single-variable.html#cb148-7" aria-hidden="true" tabindex="-1"></a>my_data_outlier <span class="ot">&lt;-</span> my_data <span class="sc">%&gt;%</span></span>
<span id="cb148-8"><a href="statistical-analyses-of-a-single-variable.html#cb148-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(<span class="sc">!</span>Channel <span class="sc">%in%</span> <span class="fu">c</span>(<span class="st">&#39;Direct&#39;</span>, <span class="st">&#39;(Other)&#39;</span>)) <span class="sc">%&gt;%</span> </span>
<span id="cb148-9"><a href="statistical-analyses-of-a-single-variable.html#cb148-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(Age) <span class="sc">%&gt;%</span></span>
<span id="cb148-10"><a href="statistical-analyses-of-a-single-variable.html#cb148-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">outlier =</span> <span class="fu">ifelse</span>(<span class="fu">find_outlier</span>(Transactions), Transactions, <span class="cn">NA</span>))</span>
<span id="cb148-11"><a href="statistical-analyses-of-a-single-variable.html#cb148-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb148-12"><a href="statistical-analyses-of-a-single-variable.html#cb148-12" aria-hidden="true" tabindex="-1"></a><span class="co">#create box plot of points by age and label outliers</span></span>
<span id="cb148-13"><a href="statistical-analyses-of-a-single-variable.html#cb148-13" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(my_data_outlier, <span class="fu">aes</span>(<span class="at">x=</span>Age, <span class="at">y=</span>Transactions)) <span class="sc">+</span></span>
<span id="cb148-14"><a href="statistical-analyses-of-a-single-variable.html#cb148-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>() <span class="sc">+</span></span>
<span id="cb148-15"><a href="statistical-analyses-of-a-single-variable.html#cb148-15" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_text</span>(<span class="fu">aes</span>(<span class="at">label=</span>outlier), <span class="at">na.rm=</span><span class="cn">TRUE</span>, <span class="at">hjust=</span><span class="sc">-</span>.<span class="dv">5</span>)</span></code></pre></div>
<p><img src="bookdownproj_files/figure-html/unnamed-chunk-54-1.png" width="672" /></p>
<div class="sourceCode" id="cb149"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb149-1"><a href="statistical-analyses-of-a-single-variable.html#cb149-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Try to use a different group - Channel</span></span>
<span id="cb149-2"><a href="statistical-analyses-of-a-single-variable.html#cb149-2" aria-hidden="true" tabindex="-1"></a>my_data_outlier <span class="ot">&lt;-</span> my_data <span class="sc">%&gt;%</span></span>
<span id="cb149-3"><a href="statistical-analyses-of-a-single-variable.html#cb149-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(<span class="sc">!</span>Channel <span class="sc">%in%</span> <span class="fu">c</span>(<span class="st">&#39;Direct&#39;</span>, <span class="st">&#39;(Other)&#39;</span>)) <span class="sc">%&gt;%</span> </span>
<span id="cb149-4"><a href="statistical-analyses-of-a-single-variable.html#cb149-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(Channel) <span class="sc">%&gt;%</span></span>
<span id="cb149-5"><a href="statistical-analyses-of-a-single-variable.html#cb149-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">outlier =</span> <span class="fu">ifelse</span>(<span class="fu">find_outlier</span>(Transactions), Transactions, <span class="cn">NA</span>))</span>
<span id="cb149-6"><a href="statistical-analyses-of-a-single-variable.html#cb149-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb149-7"><a href="statistical-analyses-of-a-single-variable.html#cb149-7" aria-hidden="true" tabindex="-1"></a><span class="co">#create box plot of points by Channel and label outliers</span></span>
<span id="cb149-8"><a href="statistical-analyses-of-a-single-variable.html#cb149-8" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(my_data_outlier, <span class="fu">aes</span>(<span class="at">x=</span>Channel, <span class="at">y=</span>Transactions)) <span class="sc">+</span></span>
<span id="cb149-9"><a href="statistical-analyses-of-a-single-variable.html#cb149-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>() <span class="sc">+</span></span>
<span id="cb149-10"><a href="statistical-analyses-of-a-single-variable.html#cb149-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_text</span>(<span class="fu">aes</span>(<span class="at">label=</span>outlier), <span class="at">na.rm=</span><span class="cn">TRUE</span>, <span class="at">hjust=</span><span class="sc">-</span>.<span class="dv">5</span>)</span></code></pre></div>
<p><img src="bookdownproj_files/figure-html/unnamed-chunk-55-1.png" width="672" />
For the above figures, data points related to the channels of “direct” and “other” were removed from the dataset since they might be classified due to the failure of channel detection in Google Analytics. For the paid search channel and referral channel, the audience in the age group of 25 to 34 had much more transactions compared to other age groups. This indicates the importance of using paid search and referral activities to drive more audiences in the age group of 25 to 34 to visit and shop at the store.</p>
<p><strong>Standard Deviation</strong>
Another term for analyzing data variance is Standard Deviation. It is a measure of the amount of variation in data, or simply put, it measures the extent to which your data is spread-out. It reflects the average squared distance from the mean.</p>
<p>Suppose we have two variables: the first one contains five units whose values are 2, 3, 3, 3, 4; and the second one contains five units as well, with the values being 1, 2, 3, 4, 5. Although these two variables have the same mean value (Mean = 3), you can clearly see that the latter one is more spread-out than the first one, indicating a bigger standard deviation.</p>
<p>Below illustrates the calculations of standard deviation for the Google analytics’ transactions data.</p>
<div class="figure">
<img src="images/5_sd.png" alt="" />
<p class="caption">Calculations of Standard Deviation</p>
</div>
<p>The mean of transactions is 7. We first calculated the distance of each observation’s transactions from the mean, then took the squared distance because some of the distances are positive values and others are negative. Without taking the square of these distances first, if we added all distances together, they might cancel each other out, failing to indicate the real variation of the data set. Once we get the sum of all the squared distances, we divide the sum by the number of observations (n= 96) minus 1, and then take the square root of this value to bring the distance back to the original standard scale, which gives us the standard deviation. Usually, a low standard deviation indicates that most of the data points are close to the average, while a high standard deviation means that the data points are spread out.</p>
<p>The codes for calculating standard deviation is easy.</p>
<div class="sourceCode" id="cb150"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb150-1"><a href="statistical-analyses-of-a-single-variable.html#cb150-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Calculate sd for each col</span></span>
<span id="cb150-2"><a href="statistical-analyses-of-a-single-variable.html#cb150-2" aria-hidden="true" tabindex="-1"></a>sd_report <span class="ot">&lt;-</span> my_data <span class="sc">%&gt;%</span> </span>
<span id="cb150-3"><a href="statistical-analyses-of-a-single-variable.html#cb150-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise_if</span>(is.numeric, sd)</span>
<span id="cb150-4"><a href="statistical-analyses-of-a-single-variable.html#cb150-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb150-5"><a href="statistical-analyses-of-a-single-variable.html#cb150-5" aria-hidden="true" tabindex="-1"></a><span class="co">#aggregate sd to the stats_report</span></span>
<span id="cb150-6"><a href="statistical-analyses-of-a-single-variable.html#cb150-6" aria-hidden="true" tabindex="-1"></a>Descriptive_Statistics <span class="ot">&lt;-</span> <span class="fu">bind_rows</span>(stats_report, sd_report)</span>
<span id="cb150-7"><a href="statistical-analyses-of-a-single-variable.html#cb150-7" aria-hidden="true" tabindex="-1"></a><span class="fu">rownames</span>(Descriptive_Statistics) <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">&quot;mean&quot;</span>,<span class="st">&quot;median&quot;</span>,<span class="st">&quot;mode&quot;</span>,<span class="st">&quot;min&quot;</span>,<span class="st">&quot;max&quot;</span>,<span class="st">&quot;IQR&quot;</span>, <span class="st">&quot;sd&quot;</span>)</span>
<span id="cb150-8"><a href="statistical-analyses-of-a-single-variable.html#cb150-8" aria-hidden="true" tabindex="-1"></a>Descriptive_Statistics <span class="ot">&lt;-</span> Descriptive_Statistics[,<span class="sc">-</span><span class="dv">12</span>]</span></code></pre></div>
<div class="sourceCode" id="cb151"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb151-1"><a href="statistical-analyses-of-a-single-variable.html#cb151-1" aria-hidden="true" tabindex="-1"></a>knitr<span class="sc">::</span><span class="fu">kable</span>(</span>
<span id="cb151-2"><a href="statistical-analyses-of-a-single-variable.html#cb151-2" aria-hidden="true" tabindex="-1"></a>    <span class="fu">arrange</span>(Descriptive_Statistics), </span>
<span id="cb151-3"><a href="statistical-analyses-of-a-single-variable.html#cb151-3" aria-hidden="true" tabindex="-1"></a>    <span class="at">digits =</span> <span class="dv">0</span>,</span>
<span id="cb151-4"><a href="statistical-analyses-of-a-single-variable.html#cb151-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">booktabs =</span> <span class="cn">TRUE</span>,</span>
<span id="cb151-5"><a href="statistical-analyses-of-a-single-variable.html#cb151-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">caption =</span> <span class="st">&#39;Descriptive Statistics&#39;</span>, <span class="at">align =</span> <span class="st">&quot;l&quot;</span></span>
<span id="cb151-6"><a href="statistical-analyses-of-a-single-variable.html#cb151-6" aria-hidden="true" tabindex="-1"></a>) <span class="sc">%&gt;%</span></span>
<span id="cb151-7"><a href="statistical-analyses-of-a-single-variable.html#cb151-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">kable_styling</span>(<span class="at">font_size =</span> <span class="dv">9</span>)</span></code></pre></div>
<table class="table" style="font-size: 9px; margin-left: auto; margin-right: auto;">
<caption style="font-size: initial !important;">
<span id="tab:unnamed-chunk-57">Table 3.12: </span>Descriptive Statistics
</caption>
<thead>
<tr>
<th style="text-align:left;">
</th>
<th style="text-align:left;">
Users
</th>
<th style="text-align:left;">
New Users
</th>
<th style="text-align:left;">
Sessions
</th>
<th style="text-align:left;">
Bounce Rate
</th>
<th style="text-align:left;">
Pages / Session
</th>
<th style="text-align:left;">
Avg. Session Duration
</th>
<th style="text-align:left;">
Ecommerce Conversion Rate
</th>
<th style="text-align:left;">
Transactions
</th>
<th style="text-align:left;">
Revenue
</th>
<th style="text-align:left;">
ECR
</th>
<th style="text-align:left;">
OldUsers
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
mean
</td>
<td style="text-align:left;">
5661
</td>
<td style="text-align:left;">
5163
</td>
<td style="text-align:left;">
7708
</td>
<td style="text-align:left;">
0
</td>
<td style="text-align:left;">
5
</td>
<td style="text-align:left;">
188
</td>
<td style="text-align:left;">
0
</td>
<td style="text-align:left;">
142
</td>
<td style="text-align:left;">
11539
</td>
<td style="text-align:left;">
114
</td>
<td style="text-align:left;">
499
</td>
</tr>
<tr>
<td style="text-align:left;">
median
</td>
<td style="text-align:left;">
940
</td>
<td style="text-align:left;">
768
</td>
<td style="text-align:left;">
1162
</td>
<td style="text-align:left;">
0
</td>
<td style="text-align:left;">
5
</td>
<td style="text-align:left;">
194
</td>
<td style="text-align:left;">
0
</td>
<td style="text-align:left;">
3
</td>
<td style="text-align:left;">
131
</td>
<td style="text-align:left;">
22
</td>
<td style="text-align:left;">
116
</td>
</tr>
<tr>
<td style="text-align:left;">
mode
</td>
<td style="text-align:left;">
22
</td>
<td style="text-align:left;">
0
</td>
<td style="text-align:left;">
118241
</td>
<td style="text-align:left;">
0
</td>
<td style="text-align:left;">
6
</td>
<td style="text-align:left;">
228
</td>
<td style="text-align:left;">
0
</td>
<td style="text-align:left;">
0
</td>
<td style="text-align:left;">
0
</td>
<td style="text-align:left;">
0
</td>
<td style="text-align:left;">
3412
</td>
</tr>
<tr>
<td style="text-align:left;">
min
</td>
<td style="text-align:left;">
22
</td>
<td style="text-align:left;">
0
</td>
<td style="text-align:left;">
31
</td>
<td style="text-align:left;">
0
</td>
<td style="text-align:left;">
2
</td>
<td style="text-align:left;">
13
</td>
<td style="text-align:left;">
0
</td>
<td style="text-align:left;">
0
</td>
<td style="text-align:left;">
0
</td>
<td style="text-align:left;">
0
</td>
<td style="text-align:left;">
2
</td>
</tr>
<tr>
<td style="text-align:left;">
max
</td>
<td style="text-align:left;">
81822
</td>
<td style="text-align:left;">
76251
</td>
<td style="text-align:left;">
118241
</td>
<td style="text-align:left;">
1
</td>
<td style="text-align:left;">
13
</td>
<td style="text-align:left;">
583
</td>
<td style="text-align:left;">
0
</td>
<td style="text-align:left;">
4315
</td>
<td style="text-align:left;">
332772
</td>
<td style="text-align:left;">
1250
</td>
<td style="text-align:left;">
5571
</td>
</tr>
<tr>
<td style="text-align:left;">
IQR
</td>
<td style="text-align:left;">
2729
</td>
<td style="text-align:left;">
2262
</td>
<td style="text-align:left;">
3787
</td>
<td style="text-align:left;">
0
</td>
<td style="text-align:left;">
2
</td>
<td style="text-align:left;">
130
</td>
<td style="text-align:left;">
0
</td>
<td style="text-align:left;">
18
</td>
<td style="text-align:left;">
1149
</td>
<td style="text-align:left;">
150
</td>
<td style="text-align:left;">
364
</td>
</tr>
<tr>
<td style="text-align:left;">
sd
</td>
<td style="text-align:left;">
13326
</td>
<td style="text-align:left;">
12438
</td>
<td style="text-align:left;">
18566
</td>
<td style="text-align:left;">
0
</td>
<td style="text-align:left;">
2
</td>
<td style="text-align:left;">
96
</td>
<td style="text-align:left;">
0
</td>
<td style="text-align:left;">
592
</td>
<td style="text-align:left;">
47461
</td>
<td style="text-align:left;">
206
</td>
<td style="text-align:left;">
976
</td>
</tr>
</tbody>
</table>
<p>The high standard deviations of all variables indicate high variations between values and abnormal distributions for data.</p>
</div>
<div id="assignment-analyzing-a-single-variable" class="section level2 hasAnchor" number="3.10">
<h2><span class="header-section-number">3.10</span> Assignment: Analyzing a Single Variable<a href="statistical-analyses-of-a-single-variable.html#assignment-analyzing-a-single-variable" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p><strong>Learning Objectives</strong>: Apply the grouped frequency, relative frequency, percentage change, percentage point, rate, ratio, mean, median, mode, weighted mean, variation ratio, range, outlier, and standard deviation analysis to the process of analyzing of a single variable</p>
<p><strong>Step 1</strong> Download the google analytic data from UA-Google Merchandise Store (Acquisition – All Traffic – Channels). Add the secondary dimension of your choice (e.g., Age). Select the data for two “whole years” (e.g., 2010 &amp; 2011). Download each year’s full data set from Google analytics as a .xlsx.</p>
<p><strong>Step 2</strong> Open the two .xlsx data sets and clean the data sets by removing the extra sheets.</p>
<p><strong>Step 3</strong> Import the two data sets in RStudio</p>
<p><strong>Step 4</strong> Using the codes of case study 2 – import data and data cleaning to import, clean, re-organize your data, then, develop your own codes for analyzing a single variable (or several variables) of your choice using the statistics of</p>
<p><em>a. Grouped frequency</em>
<em>b. Relative frequency</em>
<em>c. Percentage Change</em>
<em>d. Percentage Points</em>
<em>e. Rate</em>
<em>f. Ratio</em>
<em>g. Mean</em>
<em>h. Median</em>
<em>i. Mode</em>
<em>j. Weighted Mean</em>
<em>k. Variation Ratio</em>
<em>l. Range</em>
<em>m. Outlier</em>
<em>n. Standard Deviation</em></p>
<p><strong>Step 5</strong> Discuss with your group members to interpret the results. (Storytelling)</p>
<p><strong>Step 6</strong> Orally present your research in class. Your grade will be evaluated by three factors: <strong>a) Cover the analysis of all metrics, b) present meaningful insights from the results of data analysis.</strong></p>

</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="manipulating-data.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="statistical-analyses-of-two-variables.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"whatsapp": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": "https://github.com/jennyjiangke/book/edit/master/03-Statistical_Analyses_of_a_Single_Variable.Rmd",
"text": "Edit"
},
"history": {
"link": null,
"text": null
},
"view": {
"link": "https://github.com/jennyjiangke/book/blob/master/03-Statistical_Analyses_of_a_Single_Variable.Rmd",
"text": null
},
"download": null,
"search": {
"engine": "fuse",
"options": null
},
"toc": {
"collapse": "subsection"
}
});
});
</script>

</body>

</html>
